### ISSUE TITLE
Unable to edit/change Invoice status from AUTHORISED to VOIDED

### ISSUE THREAD

**Issue by suryakantcaax** [XeroAPI/Xero-NetStandard#102]
Invoices xs = await aapi.GetInvoiceAsync(lc.xero_access_token, lc.xero_tenant_id, new Guid(xero_invoice_id));
        Guid xID = new Guid(xero_invoice_id);
        Invoice cre = xs._Invoices.FirstOrDefault();

cre.Status = Invoice.StatusEnum.VOIDED;
                    invoices._Invoices= new List<Invoice>();
                    invoices._Invoices.Add(cre); // = new Contact();
                    await aapi.UpdateInvoiceAsync(lc.xero_access_token, lc.xero_tenant_id, xID, invoices);

when execute last line  , system is hang, and nothing to return

Note: same below code working fine with creditnote
 CreditNotes xs = await aapi.GetCreditNoteAsync(lc.xero_access_token, lc.xero_tenant_id, new Guid(xero_invoice_id));
        Guid xID = new Guid(xero_invoice_id);
        CreditNote cre = xs._CreditNotes.FirstOrDefault();

cre.Status = CreditNote.StatusEnum.VOIDED;
                    creditnotes._CreditNotes = new List<CreditNote>();
                    creditnotes._CreditNotes.Add(cre); // = new Contact();
                    await aapi.UpdateCreditNoteAsync(lc.xero_access_token, lc.xero_tenant_id, xID, creditnotes);

**Comment by jenksguo** [comment]
Addressed in v0.2.0 release.

**Comment by chrissfoot** [comment]
I'm seeing this same issue in the current version
