### ISSUE TITLE
Authorize an app without oAuth2

### ISSUE THREAD

**Issue by Tomi-15** [XeroAPI/Xero-NetStandard#109]
**SDK you're using**
 - Version [e.g. 0.1.0]

I think a useful feature would be authenticate individual Xero accounts, without creating Apps. For example, I need a custom integration of Xero with my ASP.NET Core web server, and I don't want to click on "Login with Xero", to authorize it.

**Comment by jenksguo** [comment]
Hi @Tomi-15, the xero oauth 2.0 has implemented [code authorization grant type](https://oauth.net/2/grant-types/) and no other types are implemented at the moment. 

Screen less application will still need to at least go through the login and authorization flow once. 

We have recently made an CLI tool to make the retrieval of the tokens easier and extended the lifetime of refresh token from 30 days to 60 days to make the life of apps without UIs. 

Please feel free to have a read here: 
https://developer.xero.com/documentation/api-guides/machine-2-machine
