### ISSUE TITLE
Library does not ConfigureAwait(false) causing potential deadlocks

### ISSUE THREAD

**Issue by shellicar** [XeroAPI/Xero-NetStandard#111]
**SDK you're using (please complete the following information):**
 - Version Xero.NetStandard.OAuth2 0.1.0

**Describe the bug**
Async methods do not ConfigureAwait(false)

**To Reproduce**
Calling any Async method in a UI thread with Wait, or GetAwaiter().GetResult, or .Result deadlocks.

**Expected behavior**
No deadlock should occur.

**Additional context**
As this is an SDK/library, I would expect all await calls to ConfigureAwait(false) to prevent this situation from occurring.
I would also expect non-Async calls to not call Async methods with .Result, as this will likely result in deadlocks. (ApiClient.Get<> for example)

Alternatively non-Async methods can be provided.
While ideally all applications would be designed to consume Async methods without issue, this is not always the case, especially with existing applications that use the previously synchonrous calls from UI code have issues when using the new methods.

Changing existing non-async methods to async causes different behaviour, especially with UI applications that have calls during a form load or navigation.

There is a great article here about it, as well as an old article on the issue.
https://devblogs.microsoft.com/dotnet/configureawait-faq/
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html#preventing-the-deadlock

**Comment by jenksguo** [comment]
Hi @shellicar, thanks for raising this issue to use. 

We understand that our async methods presents many challenges to some developers doing UI applications. 

We will investigate the proposed solutions and consider introducing it in the new releases. Since this will involved in structural changes in how we use OpenAPI generator to generate the SDK, this will take some time.

**Comment by jenksguo** [comment]
Hi @shellicar, will the following work for your application? 

 ```var response = await instance.CreateCreditNotesAsync(accessToken, xeroTenantId, creditNotes, summarizeErrors).ConfigureAwait(false);```

**Comment by shellicar** [comment]
Hi Jenks, thanks for the response.

I will provide an example of why that won't work tonight.

But briefly: The issue is due to (existing synchronous blocking) API calls being done in a void Form OnLoad method.
Therefore I am unable to await Async methods.
If I change the method to async void, it introduces side effects and changes the behaviour of the application's loading, as the method call returns immediately while the execution is done in the background.
If I force the code to run in a separate thread using Task.Run, I run into issues if I try to access UI elements in the separate thread, which is likely with the newly required interactive login.

Is there a way for you to provide the script/cli arguments you use to generate the library code using the tool?
I didn't see any in the repository, although I may have overlooked it.

**Comment by shellicar** [comment]
Sorry about the long delay.
The following demonstrates why this is an issue for existing forms (or any UI) applications that move from using sync blocking methods to async methods that do not configure await.

For a VB.Net Forms app (or any WinForms)


```
public class AsyncResults
{
    public async Task<string> GetConfigure()
    {
        await Task.Delay(1).ConfigureAwait(false);
        return "hello world";
    }

    public async Task<string> GetWithoutConfigure()
    {
        await Task.Delay(1);
        return "hello world";
    }
}
```

```
Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim c1 = new AsyncResults()

        Dim result1 = c1.GetConfigure().Result
        MsgBox(result1)

        Dim result2 = c1.GetWithoutConfigure().ConfigureAwait(false).GetAwaiter().GetResult()
        MsgBox(result2)
    End Sub
End Class
```

The first calls works because of the ConfigureAwait inside the called method. In fact the top level method doesn't even need to call ConfigureAwait.
The second call deadlocks.

Changing the Form1_Load method to async causes side effects and behaviour change, as it is a Sub (void) method.

**Comment by jenksguo** [comment]
@shellicar , thanks for the example. I will try to replicate this error on my end.

**Comment by jenksguo** [comment]
Hi @shellicar, it has taken some time for us to investigate this. We have now removed the dependency that might have caused this issue in the authentication flow in[ v1.0.0 of OAuth2Client package](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.0.0). 

To introduce synchronous methods is a big change to the main SDK, we are currently considering making the changes. 

For now, I found the following solution using Task.Run().Result method to force the async method act like as a sync method. 

first: 
`using System.Threading.Tasks;`

for method returns an response (like an GET API call): 
`var response = Task.Run(async () => await AccountingApi.GetInvoicesAsync(xeroToken, TenantId)).Result;`

for method returns void (like delete connections): 
`Task.Run(async () => await client.DeleteConnectionAsync(xeroToken, xeroToken.Tenants[0]));`

Please let me know if this unlocks you from your development.

**Comment by jenksguo** [comment]
Closing this issue for now, please re-open this issue if any UI developer struggle with using async methods.

**Comment by mar72vin** [comment]
I am struggling with this now. Sometimes works. Sometimes doesn't. Any news on Xero providing Sync methods?

These Async methods have been such a breaking change. Lots of other issues to but I won't add them here. 

Neither of these options work and tend to hang an MVC application. 

client.RefreshAccessTokenAsync(_xeroOAuth2Token).Result;
await client.RefreshAccessTokenAsync(_xeroOAuth2Token).ConfigureAwait(false)
