### ISSUE TITLE
DeletePaymentAsync() fails

### ISSUE THREAD

**Issue by channeladam** [XeroAPI/Xero-NetStandard#113]
The documentation (https://developer.xero.com/documentation/api/payments#POST) states that:
 _"In order to delete a payment, you must POST to the resource ID for the payment. e.g POST /Payments/b05466c8-dc54-4ff8-8f17-9d7008a2e44b "_

However, that alone doesn't actually work - you need to follow the example and also post a body of:

```
{
  "Status": "DELETED"
}
```

The DeletePaymentAsync() method signature is weird, doesn't do that status, and requires a Payments object. This shouldn't be necessary at all - and it caused me a document validation error that prevented the delete from being successful.

**Comment by SidneyAllen** [comment]
@channeladam 

Thanks for the feedback. We have improved this in version 2.0.5 of our OpenAPI spec.
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.0.5

This change will be included in the next version of Xero-NetStandard.

DeletePaymentAsync will accept a new object "PaymentDelete" which has one property (Status) which has a default value of DELETED.

The API does not support use of the DELETE verb, so we need to use the above approach when deleting Payments.

**Comment by jenksguo** [comment]
@channeladam 

This is now addressed in [release 0.4.2](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.4.3).

Thanks for reporting this issue!
