### ISSUE TITLE
ManualJournalLineID is missing and should be provided in the ManualJournalLine class

### ISSUE THREAD

**Issue by ngvtien** [XeroAPI/Xero-NetStandard#114]
*Xero.NetStandard.OAuth2 v0.1.0*

**Describe the solution you'd like**
ManualJournalLineID should be included in ManualJournalLine class similar to 
JournalLineID property in JournalLine 

**Describe alternatives you've considered**

**Additional context**

**Comment by jenksguo** [comment]
Hi @ngvtien , could you please elaborate on this? Our ManualJournal endpoint doesnot take or return ManualJournalLineID actually.

**Comment by ngvtien** [comment]
Sorry I meant it doesn't return the ManualJournalLineID, not sure if that was by design.

**Comment by SidneyAllen** [comment]
Hi @ngvtien 

I'm sorry but the API does not return the ManualJournalLineID

https://developer.xero.com/documentation/api/manual-journals
