### ISSUE TITLE
AccountingApi.GetRepeatingInvoicesAsync(accessToken: accessToken, xeroTenantId: tenantId); return null where value was expected

### ISSUE THREAD

**Issue by ngvtien** [XeroAPI/Xero-NetStandard#115]
**SDK you're using (please complete the following information):**
Xero.NetStandard.OAuth2
 - Version [0.1.0]

**Describe the bug**
Calling AccountingApi.GetRepeatingInvoicesAsync(accessToken: accessToken, xeroTenantId: tenantId);  with valid accesstoken and xeroTenantId keep return null where value was expected

**Comment by ngvtien** [comment]
**Exception throws**

*Xero.NetStandard.OAuth2.Client.ApiException
  HResult=0x80131500
  Message=Error converting value "DELETED" to type 'Xero.NetStandard.OAuth2.Model.RepeatingInvoice+StatusEnum'. Path 'RepeatingInvoices[16].Status', line 933, position 25.
  Source=Xero.NetStandard.OAuth2
  StackTrace:
   at Xero.NetStandard.OAuth2.Client.CustomJsonCodec.Deserialize(IRestResponse response, Type type) in D:\work\Projects\Xero-NetStandard\Xero.NetStandard.OAuth2\Client\ApiClient.cs:line 134
   at Xero.NetStandard.OAuth2.Client.CustomJsonCodec.Deserialize[T](IRestResponse response) in D:\work\Projects\Xero-NetStandard\Xero.NetStandard.OAuth2\Client\ApiClient.cs:line 75
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)*

**Comment by SidneyAllen** [comment]
@ngvtien - I've looked at our OpenAPI spec and added "DELETED" as a status for RepeatingInvoice. You should see this change in the next release of our SDKs.

**Comment by ngvtien** [comment]
Thanks @SidneyAllen, yeah that was what I did as a work-around for now.

**Comment by jenksguo** [comment]
@ngvtien this is now addressed in v0.4.3. Thanks for reporting the issue. 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/RepeatingInvoice.cs#L93
