### ISSUE TITLE
AccountingApi.GetExpenseClaimAsync for voided ExpenseClaim fails with JsonSerializationException

### ISSUE THREAD

**Issue by timurka-xalien** [XeroAPI/Xero-NetStandard#119]
Calling AccountingApi.GetExpenseClaimAsync for voided ExpenseClaim fails with
Newtonsoft.Json.JsonSerializationException: 'Error converting value "VOIDED" to type 'Xero.NetStandard.OAuth2.Model.Receipt+StatusEnum'. Path 'ExpenseClaims[0].Receipts[0].Status', line 24, position 28.'

The reason is that Receipt.StatusEnum doesn't contain VOIDED value.

**Comment by SidneyAllen** [comment]
@timurka-xalien - I've confirmed this is missing from our OpenAPI spec we use to generate our models.  I've made the change and it will appear in the next release of our SDKs.

**Comment by jenksguo** [comment]
@timurka-xalien, VOIDED enum has now been added to v0.3.0 of the SDK now.
