### ISSUE TITLE
Integrate to ASP.NET Webform

### ISSUE THREAD

**Issue by HemanthGali** [XeroAPI/Xero-NetStandard#120]
Hi,
Could you please share the sample solution to integrate to ASP.NET webforms.

Thanks,
Hemanth Gali.

**Comment by mohideensa** [comment]
Hi,
I am also need the same. (sample solution to integrate to ASP.NET webforms)

**Comment by shereenfathima** [comment]
Hi
I also looking for ASP .NET MVC sample.

**Comment by jenksguo** [comment]
Webforms will not be supported in ASP.NET Core. MVC will be the solutions forward. 

We will release an start/sample app to demonstrate the core MVC integration.

**Comment by shereenfathima** [comment]
Hi @jenksguo 
Could you please share the ASP .NET MVC sample (Without .net Core). I have trouble in using IHttpClientFactory variable in .net MVC

**Comment by jenksguo** [comment]
Re-opened this issue as I am working on an sample code for .NET Framework. 

@shereenfathima could you please let me know which version of .NET Framwork you are using? Is it net v4.5.2?

**Comment by mohideensa** [comment]
Hi @jenksguo,

I am also looking sample code for .NET Framework (MVC). If you prepare code with net v4.5, hope it will support for v4.5 and higher. ( i am using 4.6.1)

Thanks for your support.

**Comment by shereenfathima** [comment]
@jenksguo we are using .net 4.6. Agreed with @mohideensa idea.

**Comment by HemanthGali** [comment]
@shereenfathima 
please find the attached file, I have implemented it in the following manner in webform.
On click of a button, I'm authenticating the user and then posting the details to Xero.
xeroConfiguration --> Model class with required account details

[XeroOAuth20.txt](https://github.com/XeroAPI/Xero-NetStandard/files/4248708/XeroOAuth20.txt)

**Comment by shereenfathima** [comment]
@jenksguo can we have the update on NET Framework (MVC) OAUTH2 SDK?
