### ISSUE TITLE
oAuth2 to include selected Organisation that was just granted

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#123]
So I have a couple of apps where there are multiple organisations that need to be authorised.

When you hit grant access it adds a record in your tenant db and sends back a code for me to use that is associated with the user. So I store user/token to the db with a link from the organisation to the user. When calling the api I need to include the tenantId.  After linking I need to work out what tenantId is associated with the organisation. At the moment I have to loop through the connections to work out the most recently updated and associate that tenant with the organisation.

I can imagine a scenario where someone connecting multiple organisations at one time. 
They may ask a friend to use their account which may mean that using the latest date could be pointless and the wrong company may be connected, which could cause a big data security issue.  If there is anything I have learnt about users, they will do this :grin: 

For time being I am putting a confirmation screen after the accept to confirm what xero organisation to link and selecting the most recent one as default. It feels like an unnecessary step and a bad user experience but necessary in case of a user doesn't use the system as expected and I'm sure there are more scenarios than the one just given.

Could there be something in the access token that includes the TenantId just granted?

**Comment by jenksguo** [comment]
Hi @markogrady, in OAuth 2.0 access tokens are tied to the User and not to a specific org any more. (tenantId = orgnisation ID, you don't have to store it against an org, they are the same guid). 

One user can connect more than one organisation, but if two users both have access to the same org, they will be issued two difference access tokens. So the mapping of users and organisation connection need to be designed carefully. 

You can however, enforce the 1 user to 1 org connection by using the authorised time check for the latest. Then use the OAuth 2.0 disconnection function to remove older connections. 

Typically, we advise apps to provide a config screen (e.g. drop down) so use is able to choose the right Xero org they want to interact with. 

I hope this provides you with some ways of resolving this. 

Let me know if you have some improvement suggestions on how this could be improved. We thought of returning tenant ID along with callback of access token, however this will meant we will have to return every tenant IDs which is not feasible. Perhaps we can do the selected tenant ID in the future as an improvement.

**Comment by markogrady** [comment]
I understand the design choice which works well if you want to create a
mobile interface or similar over the top of the API. But if you are
creating app where additioanal data is stored in a database which I imagine
is most integration it means some odd steps. I've not seen any other oauth2
API implemented this way apart from HMRC but at least we know the VAT reg
number.
