### ISSUE TITLE
statusattribute 'WARNING' but no warnings included

### ISSUE THREAD

**Issue by SerenaHen** [XeroAPI/Xero-NetStandard#125]
When creating invoices the statusattribute can be returned as 'WARNING' but the warnings collection that was available in OAuth1.0a is absent. It would be useful if the warning status populated the validation errors collection or had it's own collection again so that we can flag issues up for our users.

**Comment by SidneyAllen** [comment]
@SerenaHen - which version of the Xero-NetStandard SDK are you running?

**Comment by SerenaHen** [comment]
I actually have no idea, Package version is 1.0.0?! I last took a copy from here on 11/02 if that helps or tell me where to look for the number you need.

**Comment by jenksguo** [comment]
Hi @SerenaHen, as per our OpenAPI spec definition, the array of validation errors will be returned as **_ValidationErrors_** not as **_Warnings_**.
