### ISSUE TITLE
CreateInvoice updates invoices

### ISSUE THREAD

**Issue by SerenaHen** [XeroAPI/Xero-NetStandard#127]
Is there any distinction between CreateInvoice and UpdateInvoice calls? Create used to return an 'invoice # already exists' error, now it updates invoices which was unexpected as it seems like the UpdateInvoice calls should do this. Is CreateInvoice meant to update invoices too?

**Comment by SidneyAllen** [comment]
@SerenaHen - I'd recommend updating to version 0.3.0.

We needed to refactor our OpenAPI specs and have removed the "singular" create methods.

To create an invoice you'll use "createInvoices" and pass an array of invoice objects (1 to N)
PUT /Invoices

The implementation for createInvoice was incorrect - that path/verb was intended for "updateOrCreateInvoices" where you pass an array of Invoices and if the invoice exists then update, if it does not exist, then create it.  You'll want to read about using "summarizeError" boolean to return either either ALL invoices (success and failures) or just failed invoices.
https://developer.xero.com/documentation/api/requests-and-responses

POST /Invoices

The updateMethod is for updating a single invoice

POST /Invoices/{ID}
