### ISSUE TITLE
UpdateOrCreateItems hangs and returns StatusCode 0 if TaxType is null

### ISSUE THREAD

**Issue by SerenaHen** [XeroAPI/Xero-NetStandard#129]
version 0.3.0

If you try to create items with the taxtype set to null the request times out and returns statuscode 0, invalid taxtypes return ok with a 'taxrate not found'.

**Comment by jenksguo** [comment]
Hi @SerenaHen 

The API does allow the taxtype of items to be null. This will still create the item in Xero. 

The current behaviour of item with invalid taxtype is it creates the item but leaves taxtype as " - " in UI.
