### ISSUE TITLE
Where clause in GetAccountsAsync not returning error for null account code

### ISSUE THREAD

**Issue by marco-fiumara** [XeroAPI/Xero-NetStandard#130]
Version 0.1.0

When adding a method (ToUpper() in my case) to a where clause in a request to get accounts, I found that an account code can be null in the chart of accounts. This caused the method to error with no meaningful message making it difficult to diagnose.

I have not yet updated to the latest version, so I'm unsure if this issue has been fixed yet.

**Comment by jenksguo** [comment]
Hi @marco-fiumara, the account code is a string that cannot be empty or missed when created. 

Could you please share more information so it can be investigated?

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Account.cs#L313

**Comment by Callum-Mackay** [comment]
Hi @jenksguo , had a similar scenario recently. Bank accounts are not required to have a nominal / account code. These are exposed via the Accounts endpoint too. 

![image](https://user-images.githubusercontent.com/65557528/82238013-8066fd80-992e-11ea-9f20-03d7d57cdc95.png)

Hope this helps with investigation, could be Xero "functionality" rather than a bug.

**Comment by jenksguo** [comment]
@marco-fiumara @Callum-Mackay, yes, you are both right, BankAccount's account code can be null. 

But I am afraid this improvement cant be done.

The current SDK targets NetStandard 2.0 which uses C# 7.3. In C# 7.3 there is no nullable reference type of string?, the string type itself can always be nullable. 

So to make it nullable we will require the SDK to be updated to NetStandard 2.1 which means it will stop supporting older version so dotnet core and dotnet framework. 

I would suggest checking if the code string is null first before trying to manipulate it.

**Comment by jenksguo** [comment]
Hi @Callum-Mackay @marco-fiumara, without changing the target framework, you can possibly use String.IsNullOrEmpty(str) as a condition first before changing them to upper case? 

Please let me know if this still is causing issue.

**Comment by Callum-Mackay** [comment]
Hi @jenksguo no longer an issue for us, bank accounts weren't required, so ignored if code was null originally. 

Thanks for investigating.

**Comment by jenksguo** [comment]
Thanks for getting back to me @Callum-Mackay. 👍
