### ISSUE TITLE
GetTaxRatesAsync returns null

### ISSUE THREAD

**Issue by elev8sam** [XeroAPI/Xero-NetStandard#131]
**SDK you're using (please complete the following information):**
 Xero.NetStandard.OAuth2 v0.3.0

**Describe the bug**
GetTaxRatesAsync returns null. This only just stopped working today (that I know of), it was working fine in the past, then I noticed the error today. I thought it might be related to the new sdk, so I upgraded from v.0.2.0 and I am still getting no results.

**To Reproduce**
var taxrates = Task.Run(() => xeroClient.GetTaxRatesAsync(_accessToken, _tenantId)).Result;

**Comment by elev8sam** [comment]
The SDK returns null because of the following error (which was previously reported).

Error converting value "GSTONCAPITALIMPORTS" to type 'Xero.NetStandard.OAuth2.Model.TaxRate+ReportTaxTypeEnum'. Path 'TaxRates[7].ReportTaxType', line 157, position 44."

**Comment by jenksguo** [comment]
Investigating, I think it might be due to the face this parameter is not nullable.

**Comment by redware** [comment]
I get no tax rates with the Australian version but UK Version is OK,

**Comment by jenksguo** [comment]
Hi @elev8sam & @redware

Thanks for reporting. This issue is now addressed in the new release v0.4.3. 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/TaxRate.cs#L225

**Comment by davidfarrellza** [comment]
Hi there
I'm seeing this same error connecting to the South African version of Xero. Clearly making the field "ReportTaxType" an enum is a mistake, because Xero is constantly adding new Report Tax Types. Please can you fix this as I cannot get tax rates from the API due to the error.
