### ISSUE TITLE
.NET MVC sample without using the .Net Core

### ISSUE THREAD

**Issue by shereenfathima** [XeroAPI/Xero-NetStandard#132]
Could you please share the ASP .NET MVC sample (Without .net Core). I have trouble in using IHttpClientFactory variable in .net MVC

**Comment by jenksguo** [comment]
Hi @shereenfathima, the SDK officially only supports .NET Core (WebAPI & MVC). 

However, we will look into how to support .NET Framework and come up with an example in the near future.

**Comment by tqrecords** [comment]
Ran into the same issue and referenced the fix here:

https://github.com/XeroAPI/Xero-NetStandard/issues/136

**Comment by jenksguo** [comment]
Hi @shereenfathima & @tqrecords, the SDK has a [target framework of netstandard2.0 ](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)so it should work with .NET Framework 4.6.1 and above. 

Here is an example with no Dependency Injection, I hope this can help with your implementation:

```
using System;
using System.Configuration;
using System.Web.Mvc;
using System.Net.Http;
using Xero.NetStandard.OAuth2.Client;
using Xero.NetStandard.OAuth2.Config;
using Microsoft.Extensions.DependencyInjection;

namespace NetStandardApp_net461.Controllers
{
    public class AuthorizationController : Controller
    {

        // GET: Authorization
        public ActionResult Index()
        {

            var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
            var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();

            XeroConfiguration XeroConfig = new XeroConfiguration
            {
                ClientId = ConfigurationManager.AppSettings["XeroClientId"],
                ClientSecret = ConfigurationManager.AppSettings["XeroClientId"],
                CallbackUri = new Uri(ConfigurationManager.AppSettings["XeroCallbackUri"]),
                Scope = ConfigurationManager.AppSettings["XeroScope"],
                State = ConfigurationManager.AppSettings["XeroState"]
            };

            var client = new XeroClient(XeroConfig, httpClientFactory);

            return Redirect(client.BuildLoginUri());
        }
    }
}
```

**Comment by shereenfathima** [comment]
@jenksguo Thanks. I have successfully managed to get the connection. However, we have used XeroCoreApi to retrieve objects (e.g. Contacts, Invoices) from Xero. Can we utilize the same core API to retrieve Xero objects?
