### ISSUE TITLE
GetAccountsAsync Error converting value "CISLABOUR" to type 'Xero.NetStandard.OAuth2.Model.Account+SystemAccountEnum'

### ISSUE THREAD

**Issue by elev8sam** [XeroAPI/Xero-NetStandard#133]
**SDK you're using (please complete the following information):**
 - 0.1.0

**Describe the bug**
When calling GetAccountsAsync, the SDK returns null because of the following error :

Newtonsoft.Json.JsonSerializationException: 'Error converting value "CISLABOUR" to type 'Xero.NetStandard.OAuth2.Model.Account+SystemAccountEnum'. Path 'Accounts[317].SystemAccount', line 5452, position 34.'

ArgumentException: Requested value 'CISLABOUR' was not found.

**Comment by jenksguo** [comment]
Hi @elev8sam, investigating, the CIS related SystemAccount enums were included in the latest [OpenAPI Spec 2.0.1](https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L17646-L17650). However the last generation did not interpret them faithfully. 

Expect an patch coming soon for this.

**Comment by jenksguo** [comment]
@elev8sam confirmed. This is now addressed in version v0.3.0 of the SDK. 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Account.cs#L267
