### ISSUE TITLE
Initialising lists in the constructor

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#134]
- Version Latest

Could lists be initialised in the constructor

```
 [JsonConstructor]
    public ManualJournal()
    {
    }

    [DataMember(EmitDefaultValue = false, Name = "Narration")]
    public string Narration { get; set; }

    [DataMember(EmitDefaultValue = false, Name = "JournalLines")]
    public List<ManualJournalLine> JournalLines { get; set; }
```
Would be turned into 
```
 [JsonConstructor]
    public ManualJournal()
    {
JournalLines  = new List<ManualJournalLine>();
    }

    [DataMember(EmitDefaultValue = false, Name = "Narration")]
    public string Narration { get; set; }

    [DataMember(EmitDefaultValue = false, Name = "JournalLines")]
    public List<ManualJournalLine> JournalLines { get; set; }
```
It would just solve having to initialise it everywhere in code and checking for nulls.

I'm happy to start going through and adding them.

**Comment by jenksguo** [comment]
Hi @markogrady, thanks for reporting it. 

This is generated via an openapi generator template, if indeed mistaken, this will be in every places. The templates are not public yet, so I will confirm and go through the template, fix and re-generate a new patch.

**Comment by markogrady** [comment]
Hi @jenksguo Not sure I quite understand. Does that mean once the API is public then you will go through and init the lists? 

Will the generator be run regularly and remove the constructors each time?

**Comment by jenksguo** [comment]
Hi @markogrady, we have made an improvements to the bulk creation methods to include Lists now. 

For creating a single item, it will also be wrapped in an Json array which will be a list type in c#.

**Comment by SidneyAllen** [comment]
@jenksguo - any update on this change to our .NET templates to add this init in the constructor?

**Comment by appetere** [comment]
I've just run into this too in Xero.NetStandard.OAuth2 v3.0.
Trying to use `Items`, `CreditNotes`, `Invoices`, `Allocations`, `BankTransactions`.  All need the inner List<T> collection manually initialising, which really should be done in the constructor.

**Comment by jenksguo** [comment]
Hi @markogrady @appetere, I think this had been addressed already, please kindly check the latest versions to confirm.

**Comment by jenksguo** [comment]
Please re-open if there is anymore to discuss.
