### ISSUE TITLE
Value cannot be null. Parameter name: httpClientFactory

### ISSUE THREAD

**Issue by tqrecords** [XeroAPI/Xero-NetStandard#136]
**SDK you're using (please complete the following information):**
 - Version 0.4.0

**Describe the bug**
I cannot initialize XeroClient(). Using the exact example as outlined in the original readme. Getting the error:

```
Value cannot be null.
Parameter name: httpClientFactory
```
How do I define httpClientFactory? I'd like to be able to initialize XeroClient by using a config file for the settings, however I cannot get passed the httpClientFactory parameter.

**To Reproduce**
Use the same code from XeroOauth2Controller as outlined in the readme.

**Comment by tqrecords** [comment]
After a lot of searching I ended up implementing it a different way. This might help for anyone else using .NET 4.7:

`
var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();
`

**Comment by mycodeclub** [comment]
Sorry, I tested for   .NET Framework 4.6.1 and 4.7.2
But it didn't work for any of the above :(
Getting same error 
 'ServiceCollection' does not contain a constructor that takes 0 arguments.

Any Solution 
Please Suggest
