### ISSUE TITLE
Error getting organization details for Norwegian companies

### ISSUE THREAD

**Issue by tqrecords** [XeroAPI/Xero-NetStandard#137]
**SDK you're using (please complete the following information):**
 - Version [0.4.0]

**Describe the bug**
Cannot retrieve organization details for Norwegian companies using the following code:

`var result = await api.GetOrganisationsAsyncWithHttpInfo(accessToken, tenantId.ToString());`

The following error is retrieved: 

`Error converting value "NO" to type 'Xero.NetStandard.OAuth2.Model.CountryCode'. Path 'Organisations[0].CountryCode', line 15, position 25.`

**To Reproduce**
1. Add a new organization
2. In the drop down 'Where does your organisation pay taxes?', choose Norway
3. Try to run the above code on the new organization

**Expected behavior**
Retrieve organization details.

**Comment by SidneyAllen** [comment]
@jenksguo this is an interesting bug.  I've confirmed the countryCode "NO" exists and performs correctly in the Java SDK.  Wondering is .NET is interpreting "NO" as a boolean?  

Bug should be investigated and validated.

**Comment by tqrecords** [comment]
> @jenksguo this is an interesting bug. I've confirmed the countryCode "NO" exists and performs correctly in the Java SDK. Wondering is .NET is interpreting "NO" as a boolean?
> 
> Bug should be investigated and validated.

I checked the following class from the .NET SDK: 

`Xero.NetStandard.OAuth2\Model\CountryCode.cs`

The CountryCode "NO" is not defined?

**Comment by jenksguo** [comment]
@SidneyAllen this one is tricky, the "- NO" enum option seemed to have been integrated as a logical operation which resulted this to be missing from generated csharp code.

![image](https://user-images.githubusercontent.com/41350731/76156618-20472480-6151-11ea-867e-9891f1c05ef4.png)

This is not really documented in the [openapi spec documentation](https://swagger.io/specification/#dataTypes).  e.g. - null means a nullable parameter

I suggest we make this update to address this issue:
![image](https://user-images.githubusercontent.com/41350731/76156662-9c416c80-6151-11ea-8063-6ac29235fd09.png)

**Comment by SidneyAllen** [comment]
@jenksguo - I have updated the OAS with this change.

**Comment by jenksguo** [comment]
@SidneyAllen The solution works. This will be address on the next codegen. 

![image](https://user-images.githubusercontent.com/41350731/76590641-f1aabe80-6541-11ea-9dbe-4716628ff78e.png)

**Comment by jenksguo** [comment]
@tqrecords addressed in 0.4.2. Thanks for reporting the issue again.
