### ISSUE TITLE
Unable to deploy package in azure cloud service

### ISSUE THREAD

**Issue by HemanthGali** [XeroAPI/Xero-NetStandard#138]
I have included the nuget package to my solution, when The solution runs fine in my local. When I try to deploy in azure cloud service, the publish fails with below error.

"Your role instances have recycled a number of times during an update or upgrade operation. This indicates that the new version of your service or the configuration settings you provided when configuring the service prevent the role instances from running. Verify your code does not throw unhandled exceptions and that your configuration settings are correct and then start another update or upgrade operation."

Installed-Package Xero.NetStandard.OAuth2 (latest version)
Installed-Package Xero.NetStandard.OAuth2Client (latest version)

@jenksguo @SidneyAllen  please help to fix this issue.

**Comment by jenksguo** [comment]
Hi @HemanthGali, this doesn't look like a SDK related issue. I recommend getting some help from Azure online forum or technical support.
