### ISSUE TITLE
Always return 401 status code when uploading invoice attachment.

### ISSUE THREAD

**Issue by Hoangpnse62077** [XeroAPI/Xero-NetStandard#140]
![image](https://user-images.githubusercontent.com/27847678/75665668-1af85e80-5ca7-11ea-9cc0-5570010a664b.png)

I try to add invoice attachment but result is always return 401 while accesstoken and tenantId are right.

![image](https://user-images.githubusercontent.com/27847678/75665825-5c890980-5ca7-11ea-9b08-a42f4c219628.png)

**Comment by SidneyAllen** [comment]
@Hoangpnse62077 - can you check that your scopes include **accounting.attachments**

https://developer.xero.com/documentation/oauth2/scopes

**Comment by jenksguo** [comment]
@Hoangpnse62077 If the same accessToken and tenantId works for other calls, the scope might be the reason. 

Please re-open this issue if you still are unable to resolve this.
