### ISSUE TITLE
Return access token information without login redirect callback url.

### ISSUE THREAD

**Issue by Hoangpnse62077** [XeroAPI/Xero-NetStandard#141]
Currently, I'm migrating from oAuth 1.0 to oAuth 2.0, i need the xero api return token info without redirect to xero authentication page because I'm using webapi without user interface.

Thanks a alot.

**Comment by jenksguo** [comment]
Hi @Hoangpnse62077, with the deprecation of OAuth 1.0a and private app integration methods. All apps will require an step to use a browser to login and authorise to get a token. The token then can be exchanged programmatically thereafter. 

access token lives for 30 minutes, refresh token lives for 60 days. 

For machine to machine API integration, please read more here:
https://developer.xero.com/documentation/api-guides/machine-2-machine
