### ISSUE TITLE
GetPurchaseOrderAsync missing Param for PurchaseOrderNumber

### ISSUE THREAD

**Issue by brendansaunders** [XeroAPI/Xero-NetStandard#144]
The GetPurchaseOrderAsync method is missing a way to be able to get a purchase order using the PurchaseOrderNumber as per the API documentation by specify an individual record by appending the value to the endpoint.

https://developer.xero.com/documentation/api/purchase-orders

**Comment by SidneyAllen** [comment]
@brendansaunders - thanks for the feedback - we will update the OpenAPI specs and include this change in an upcoming release.

**Comment by SidneyAllen** [comment]
@brendansaunders  - this was added to our OpenApi Spec version 2.0.3 release
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.0.3

GetPurchaseOrderByNumberAsync is now available in AccountingApi class.

Give it a whirl in version 0.4.3 of Xero-NetStandard
