### ISSUE TITLE
Should all the money values be decimal rather than float

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#146]
I've always used decimals for money because they are more accurate because floating point numbers can be sometime unpredictable.

I've found an example 
https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

**Comment by markogrady** [comment]
I've seen a similar issue

**Comment by jenksguo** [comment]
@markogrady taking on your advice, in v3.0.0 we have improved OpenAPI spec to be able to identify money and money related fields in API and allowed the use of decimal data type. 

Thanks for your advice in the first place.
