### ISSUE TITLE
Xero POST Invoice Discount rate validation error

### ISSUE THREAD

**Issue by eternalcoffee** [XeroAPI/Xero-NetStandard#147]
https://community.xero.com/developer/discussion/39048510/

This issue was originally posted in 2016 and I can confirm that it has not been fixed as of now: 3/11/20

This looks like its not only exclusive to the Discount rate being 100% with the line amount being sent.

If LineAmount rounded to 2 dp is equal to 0.00 AND LineAmount is supplied, Xero API will try to validate if the line amount is correct and will fail at doing so.

Here is an example of a line failing with 60% discount and one passing with 99.9%

e.g. 1
Quantity = 1, Unit = 0.01, DiscountRate = 50%
1 * 0.01 *((100 - 50)/100) = 0.004
// Fails - "The line total -0.01 does not match the expected line total 0.00"

e.g. 2
Quantity = 1, Unit = 5.5, DiscountRate = 99.9%
1 * 5.5 *((100 - 99.9)/100) = 0.0055
// Passes because 0.0055 rounds to $0.01

**Comment by SidneyAllen** [comment]
@eternalcoffee 

Thanks for the feedback - we'll raise this with the API team.  This isn't an SDK issue, so I'll be closing it as this can't be addressed in the SDK.
