### ISSUE TITLE
Missing CurrencyCode ZMK

### ISSUE THREAD

**Issue by ThirstyJarek** [XeroAPI/Xero-NetStandard#148]
SDK:
- Xero.NetStandard.OAuth2 v0.4.0

BUG:
We are calling the GetAccountsAsync() method in the Xero Api for a specific organisation. The account data is being returned as null. By retrieving the raw data from the Xero Api and serialising it manually to the Accounts model, we are getting the following error:

Error converting value "ZMK" to type 'Xero.NetStandard.OAuth2.Model.CurrencyCode'. 

This is obviously caused by one of the accounts having the ZMK Currency Code, which is missing [from the api model](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/CurrencyCode.cs).

ADDITIONAL:
Also to note, I've added a pull request for this same api, that has been ignored? It's for a similar issue to this one, but this organisation has a CurrencyCode value of "" (empty string). I didn't create this organisation, but somehow they've ended up with an empty Currency Code value. This fails de-serialise just like above. Could you add an empty string as a value to the CurrencyCode model for now? Or fix the data on your side?

**Comment by SidneyAllen** [comment]
@ThirstyJarek - I've added the following ENUMs to the currencyCode in the spec and will be released in version 2.0.5

- ZMK
- ""

@jenksguo

**Comment by ThirstyJarek** [comment]
Good to hear!

You're also missing the 'ARPREPAYMENT' Enum type from the Invoice TypeEnum field, as i'm still getting this error:

Error converting value "ARPREPAYMENT" to type 'Xero.NetStandard.OAuth2.Model.Invoice+TypeEnum'.

I mentioned this in my original pull request and can see you added 2/3 of the missing Invoice enums, but you seem to have missed this one (for reference: https://github.com/XeroAPI/Xero-NetStandard/pull/112/commits/e2b826264e53fffbf72f4e14dcf99405c91e07ec).

**Comment by SidneyAllen** [comment]
@ThirstyJarek - thanks - got it

**Comment by SidneyAllen** [comment]
@ThirstyJarek 

Fixed in OpenAPi Spec version 2.0.5
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.0.5

This will be addressed in the next release of Xero-NetStandard SDK

**Comment by jenksguo** [comment]
@ThirstyJarek 

Hi this is addressed in [0.4.3 release](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.4.3). 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/CurrencyCode.cs#L1009

Thanks for reporting the issue.
