### ISSUE TITLE
Refresh Token does not seems to be working 

### ISSUE THREAD

**Issue by barkamlesh** [XeroAPI/Xero-NetStandard#151]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2Client - 0.0.3

**Describe the bug**
When trying to refresh the token API throws an error Invalid grant type. I look further into code and to refresh code grant type **refresh_token** required which is not being passed when making a request which throws error of invalid grant type.

**Comment by jenksguo** [comment]
Hi @barkamlesh , invalid grant usually means the token you are using to refresh are not the latest pair. 

I have tested again myself the refresh method works fine. 

Please ensure you are using the latest access and refresh token to refresh.
