### ISSUE TITLE
'StatusAttributeString' property is missing from 'CreditNote' model class

### ISSUE THREAD

**Issue by adamsadler** [XeroAPI/Xero-NetStandard#152]
SDK Version: 0.4.2 (Nuget package - latest stable)

It appears that the 'StatusAttributeString' property is missing from the 'Xero.NetStandard.OAuth2.Model.CreditNote' class in the wrapper library.

When bulk-creating credit notes - with 'summarizeErrors' set to false - 'StatusAttributeString' is being returned in the JSON response, but because of the missing class property, this status is lost.

Not sure this fully qualifies as a bug, but it's not really a feature request either.

I can see this same property was added to some other classes in recent updates, so I suspect there may be more classes that are also missing this property.

**Comment by adamsadler** [comment]
In addition to this, I've discovered one or two missing facilities around the same kind of problem - i.e. that require updates to the underlying API spec.

Would it be best to raise an issue here or in the actual Xero Open API (https://github.com/XeroAPI/Xero-OpenAPI) repo?

**Comment by SidneyAllen** [comment]
@adamsadler - yes create issues on Xero-OpenAPI repo so we can review the request.

We are creating new releases of our OpenAPI specs every week or two and building against the specs.

**Comment by adamsadler** [comment]
Brilliant. I'll add them over there instead 😃 

I'm currently developing an integration and slowly coming up against these little bits and bobs as I go through!

Since I started this development, I've seen the regular updates coming through. Thanks for the continuing work on the API - especially in the current climate!

**Comment by SidneyAllen** [comment]
@adamsadler - I've added this property to the CreditNote and will merge next week with other updates.

It will be included in release 2.0.7 or our OpenAPI Spec.  Watch for the next build of Xero-NetStandard in the next week or two.

Take care and stay safe.

**Comment by jenksguo** [comment]
Hi @adamsadler, thanks for reporting the issue. The latest SDK addressed this issue. 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/CreditNote.cs#L255
