### ISSUE TITLE
GetContacts Error 

### ISSUE THREAD

**Issue by ldsenow** [XeroAPI/Xero-NetStandard#153]
**SDK you're using (please complete the following information):**
 - Nuget Version:
Xero.NetStandard.OAuth2 v0.4.1
Xero.NetStandard.OAuth2Client v0.0.3

**Describe the bug**
For a specific client, we always receive this error below and we believe the token is not expired.

"ExceptionType": "Xero.NetStandard.OAuth2.Client.ApiException",
"Source": "Xero.NetStandard.OAuth2",
"Message": "Error calling GetContacts: ",
"StackTrace": " at Xero.NetStandard.OAuth2.Api.AccountingApi.GetContactsAsyncWithHttpInfo(String accessToken, String xeroTenantId, Nullable`1 ifModifiedSince, String where, String order, List`1 iDs, Nullable`1 page, Nullable`1 includeArchived)\r\n at Xero.NetStandard.OAuth2.Api.AccountingApi.GetContactsAsync(String accessToken, String xeroTenantId, Nullable`1 ifModifiedSince, String where, String order, List`1 iDs, Nullable`1 page, Nullable`1 includeArchived)

Our client contacted us and we looked at our error log. We found the error above.
Since we dont have our client's account, we cant debug the error. Not sure what had gone wrong.

We believe token and tenant id are both valid. Could you think of any thing we could miss?

**Comment by jenksguo** [comment]
Hi @ldsenow, it is difficult for me to tell what is wrong by looking at a Stacktrace. It seems to be complaining about an optional parameter that is passed into the GetContactsAsync method. I would suggest to check the filter application. 

Do you have any code snippet that you have corresponding to this message?

**Comment by jenksguo** [comment]
@ldsenow closing this as I cannot replicate the error with the SDK. 

Here is an simple example of an implementation:

```
      string accessToken = xeroToken.AccessToken;
      string xeroTenantId = xeroToken.Tenants[0].TenantId.ToString();

      var AccountingApi = new AccountingApi();
      var response = await AccountingApi.GetContactsAsync(accessToken, xeroTenantId);
```
