### ISSUE TITLE
Understanding which object has failed if you submit in bulk 

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#156]
- Version 0.3.0 

Here is a video to explain the issue.

https://www.youtube.com/watch?v=f6tZmuF1gdQ

If I was to submit 20 invoices and 2 fail. I receive an 2 ValidationErrors 

Must be a unique 
examples like must be a unique number 
or 
account code does not exist.

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Element.cs

In Element in returns an invoiceId which has no use because it was not on the invoice before it was entered and was generated by xero and you can not call it.

This is the actual response

`{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "Type": "ACCREC",
      "InvoiceID": "9ac9f4c4-9c7f-478f-be3a-39c0c82b32f3",
      "InvoiceNumber": "559",
      "Reference": "",
      "Prepayments": [],
      "Overpayments": [],
      "AmountDue": 5.00,
      "AmountPaid": 0.00,
      "SentToContact": false,
      "CurrencyRate": 1.000000,
      "IsDiscounted": false,
      "HasErrors": true,
      "Contact": {
        "ContactID": "e00e5d0d-3e85-4ca7-b91b-1bef7189ef11",
        "ContactStatus": "ACTIVE",
        "Name": "TEST",
        "EmailAddress": "",
        "BankAccountDetails": "",
        "Addresses": [
          {
            "AddressType": "STREET",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          },
          {
            "AddressType": "POBOX",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          }
        ],
        "Phones": [
          {
            "PhoneType": "DEFAULT",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "DDI",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "FAX",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "MOBILE",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          }
        ],
        "UpdatedDateUTC": "\/Date(1585236672457+0000)\/",
        "ContactGroups": [],
        "IsSupplier": false,
        "IsCustomer": true,
        "SalesTrackingCategories": [],
        "PurchasesTrackingCategories": [],
        "ContactPersons": [],
        "HasValidationErrors": false
      },
      "DateString": "2020-04-02T00:00:00",
      "Date": "\/Date(1585785600000+0000)\/",
      "Status": "DRAFT",
      "LineAmountTypes": "Exclusive",
      "LineItems": [
        {
          "Description": "TEST",
          "UnitAmount": 50.00,
          "LineAmount": 5.00,
          "Tracking": [],
          "Quantity": 0.1000,
          "LineItemID": "f245e71d-ee60-43ca-b22d-1d57cae67376",
          "ValidationErrors": []
        }
      ],
      "SubTotal": 5.00,
      "TotalTax": 0.00,
      "Total": 5.00,
      "CurrencyCode": "GBP",
      "ValidationErrors": [
        {
          "Message": "Invoice # must be unique."
        }
      ],
      "Warnings": [
        {
          "Message": "Account code '6000' has been removed as it does not match a recognised account."
        }
      ]
    },
    {
      "Type": "ACCREC",
      "InvoiceID": "d2841e5b-0f81-4bbf-978a-89a2258d7a68",
      "InvoiceNumber": "551",
      "Reference": "",
      "Prepayments": [],
      "Overpayments": [],
      "AmountDue": 5.00,
      "AmountPaid": 0.00,
      "SentToContact": false,
      "CurrencyRate": 1.000000,
      "IsDiscounted": false,
      "HasErrors": true,
      "Contact": {
        "ContactID": "e00e5d0d-3e85-4ca7-b91b-1bef7189ef11",
        "ContactStatus": "ACTIVE",
        "Name": "TEST",
        "EmailAddress": "",
        "BankAccountDetails": "",
        "Addresses": [
          {
            "AddressType": "STREET",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          },
          {
            "AddressType": "POBOX",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          }
        ],
        "Phones": [
          {
            "PhoneType": "DEFAULT",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "DDI",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "FAX",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "MOBILE",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          }
        ],
        "UpdatedDateUTC": "\/Date(1585236672457+0000)\/",
        "ContactGroups": [],
        "IsSupplier": false,
        "IsCustomer": true,
        "SalesTrackingCategories": [],
        "PurchasesTrackingCategories": [],
        "ContactPersons": [],
        "HasValidationErrors": false
      },
      "DateString": "2020-04-02T00:00:00",
      "Date": "\/Date(1585785600000+0000)\/",
      "Status": "DRAFT",
      "LineAmountTypes": "Exclusive",
      "LineItems": [
        {
          "Description": "TEST",
          "UnitAmount": 50.00,
          "LineAmount": 5.00,
          "Tracking": [],
          "Quantity": 0.1000,
          "LineItemID": "c687353a-66ed-4bd5-9e11-4cf71d9f9338",
          "ValidationErrors": []
        }
      ],
      "SubTotal": 5.00,
      "TotalTax": 0.00,
      "Total": 5.00,
      "CurrencyCode": "GBP",
      "ValidationErrors": [
        {
          "Message": "Invoice # must be unique."
        }
      ],
      "Warnings": [
        {
          "Message": "Account code '6000' has been removed as it does not match a recognised account."
        }
      ]
    }
  ]
}`

Should Element have a generic type which you can pass each element to return in the response?

**Comment by jenksguo** [comment]
@SidneyAllen This will need some investigation with you on how our OpenAPI spec is written.

**Comment by SidneyAllen** [comment]
@markogrady 

Hey  Mark - watched your video.  I noticed a couple issues.  If you are creating an Invoice you can not set the InvoiceID Guid, this is generated by Xero.  You can set the Invoice Number.

You should upgrade to version .04.3 of the NetStandard SDK and you'll see the createInvoices method has a new param called "summarizeErrors" boolean.  Set this to false, and the API will return a 200ok with an array that include BOTH successfully created invoices and those with validation errors.  Loop over the array and inspect the "hasErrors" property on the invoice to determine which invoices succeeded and which ones failed.

Give that a try, and let us know how you get on.

This is an example of a Contact with validation error - obviously not an invoice, but illustrates the point.

 ```{
      "ContactID": "00000000-0000-0000-0000-000000000000",
      "Name": "Xero 6",
      "EmailAddress": "x@x.com",
      "Addresses": [],
      "Phones": [],
      "ContactGroups": [],
      "ContactPersons": [],
      "HasValidationErrors": true,
      "StatusAttributeString": "ERROR",
      "ValidationErrors": [
        {
          "Message": "The contact name Xero 6 is already assigned to another contact. The contact name must be unique across all active contacts."
        }
      ]
    }```

**Comment by markogrady** [comment]
Hi @SidneyAllen 

> Hey Mark - watched your video. I noticed a couple issues. If you are creating an Invoice you can not set the InvoiceID Guid, this is generated by Xero. You can set the Invoice Number.

I did know this and I understand why, I didn't make it clear in my video. What is the point in having an ID which has no correlation to anything in the response and putting that on the Element object?

That summary issue has resolved my problem. thanks. I have an outstanding pull request, I'm not sure whether it is needed.
