### ISSUE TITLE
How to create POST request to create new invoice?

### ISSUE THREAD

**Issue by karthikrkaranth** [XeroAPI/Xero-NetStandard#160]
Hello.. I am integrating xero OAuth in C# application. 
I am not getting how to use POST request to create new invoice. Can anybody please help me with this?

**Comment by jenksguo** [comment]
Hi @karthikrkaranth, I have an example of creating contact in this repo. This can help to understand how to create an invoice. 

https://github.com/XeroAPI/xero-netstandard-oauth2-starter-dotnet-core
