### ISSUE TITLE
GetContacts Authentication Error

### ISSUE THREAD

**Issue by CobusMO** [XeroAPI/Xero-NetStandard#161]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2 v0.4.4
- Xero.NetStandard.OAuth2Client v0.0.3

**Describe the bug**
I receive the following error when trying to call GetContacts. I am however Authenticated, as I am using the exact accesstoken and tenant id in calls before and after this one. 

![image](https://user-images.githubusercontent.com/63375562/78838495-98c22f00-79f6-11ea-8209-d60f47326b6e.png)

Code I am using
Contacts (Not Working)
var contacts = await _accountingApi.GetContactsAsync(accessToken, tenantId, System.DateTime.Parse(xeroTenantExecutionDate),null,null,null,pageNo,true);

BankTransactions (Working Great)
var banktransactions = await _accountingApi.GetBankTransactionsAsync(accessToken, tenantId, System.DateTime.Parse(xeroTenantExecutionDate), null, null, pageNo);

**Comment by SidneyAllen** [comment]
@CobusMO - have you added the accounting.contacts scope to your authorization flow?
https://developer.xero.com/documentation/oauth2/scopes

You may need to login and navigate to the Connect App screen to disconnect your app, then perform the oauth2 flow again to get that scope added to your access token.

**Comment by CobusMO** [comment]
Good Day @SidneyAllen 

Thank you for your quick response. I managed to add the accounting.contacts to my scope and all is working great now thanks. 

Kind  Regards
