### ISSUE TITLE
Xero app oauth2 .net mvc api

### ISSUE THREAD

**Issue by aman860** [XeroAPI/Xero-NetStandard#163]
**SDK you're using (please complete the following information):**
 - Version [e.g. 0.1.0]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SidneyAllen** [comment]
Does not appear to be a question here @aman860 - closing but you can open an new issue if needed
