### ISSUE TITLE
I am unable to find the code for  XERO auth2.0 implementation in MVC c# (.net platform 5.2 and VS2015)

### ISSUE THREAD

**Issue by AdeshMishra1** [XeroAPI/Xero-NetStandard#174]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SidneyAllen** [comment]
@AdeshMishra1 - we have two starter apps with the code needed for OAuth 2 using Xero-NetStandard

.NET Core
https://github.com/XeroAPI/xero-netstandard-oauth2-starter-dotnet-core

.NET Framework 4.6.1 and higher
https://github.com/XeroAPI/xero-netstandard-oauth2-starter-app-dotnet-framework

**Comment by AdeshMishra1** [comment]
@SidneyAllen thanks for sending through. 
As the client is not prefered .net core for now. so currently, I have been set up the project in .nrt framework 5.2 and working on visual studio 2015. Can I get the code for same?
