### ISSUE TITLE
GetBankTransactionAsync fail

### ISSUE THREAD

**Issue by john-do3** [XeroAPI/Xero-NetStandard#175]
We have a few bank transactions those cannot be achieved using BankTransactions API. For example, calling GetBankTransactionAsync(accessToken, xeroTenantId, Guid.Parse("21332dec-cd3f-47ae-9926-ef7e4e4415eb"))) lead to "Error calling GetBankTransaction: The resource you're looking for cannot be found" exception.

These transactions haven't green mark before 'Reconciled' label:
![Xero+_+View+Transaction](https://user-images.githubusercontent.com/2835620/80991903-67941d80-8e41-11ea-86de-4505ffac01ba.png)

Can we get such transactions using GetBankTransactionAsync() calls somehow?

**Comment by jenksguo** [comment]
Hi @john-do3 , I see why now. The SDK method is working correctly and you got an 404 resource not found response.  

The BankTransaction can only get the transitions that user uploaded or created. The actual bank transactions from an actual bank feed cannot be retrieved via the API regardless of the status of reconciliation. 

Getting real bank feed transaction is not available via the AP unfortunately.

**Comment by jenksguo** [comment]
Closing the issue on SDK as it is related to API not the SDK tool itself.

**Comment by john-do3** [comment]
@jenksguo thanks for clarification!
