### ISSUE TITLE
Xero Accounting Sdk Core: authentication error

### ISSUE THREAD

**Issue by erossini** [XeroAPI/Xero-NetStandard#176]
I'm implementing an internal procedure to generate invoices from my database. In using `.NET Core`. I installed the `Xero.Api.SDK.Core` v. 1.1.4

I find the Xero documentation quite difficult to understand and a bit up to date. I took a look to the Github repository and they refer only to OAuth 2.0. In my case I don't want any user interaction because I want a background process.

I created an account as developer and a demo company for test.

![image](https://user-images.githubusercontent.com/9497415/81486496-0e672800-924d-11ea-9c21-81d567053285.png)

I googled a bit and I found in a site an example how to connect to the api (I couldn't find any details in the Xero documentation).

```
X509Certificate2 cert = new X509Certificate2(@"public_privatekey.pfx", "password");

var api = new Xero.Api.Example.Applications.Private.PrivateAuthenticator(cert);

var private_app_api = new XeroCoreApi("https://api.xero.com", 
                                      new PrivateAuthenticator(cert),
                                      new Consumer("ClientId", "ClientSecret"), 
                                      null, null);
```

Now, I thought, I should use the api. I tried to read the list of contacts:

```
var contacts = private_app_api.Contacts;
var list = contacts.FindAsync().Result;
```

The result is the following error:

> System.AggregateException: 'One or more errors occurred. (oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer%20key%20was%20not%20recognised)'
>
>Inner Exception UnauthorizedException: >oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer%20key%20was%20not%20recognised

Then, I downloaded the repository from Github. I copy and paste the ClientId and ClientSecret and run the tests. No one test is passed!

![image](https://user-images.githubusercontent.com/9497415/81486501-16bf6300-924d-11ea-85c9-bcc25685a53a.png)

My goal is to create a contact or find one in the list, create an invoice and save the invoice in PDF format in my storage.

How can I do that? Is there any example for that?

**Comment by jenksguo** [comment]
Hi @erossini, sorry to learn about your confusion on our documentation. 

We are in a transition period where we are migrating everyone from OAuth 1.0a to OAuth 2.0. The creation of any OAuth 1.0a on our developer portal has been stopped and OAuth 2.0 apps are the new way of connecting to Xero API going forward. 

The Xero.NetStandard.OAuth2 SDK is fully supporting OAuth 2.0 application you have just created. This won't be needing any certificate signing as all security is delegated to https. 

Have a look at our sample apps [here](https://github.com/XeroAPI/xero-netstandard-oauth2-starter-dotnet-core) and [there](https://github.com/XeroAPI/xero-netstandard-oauth2-starter-app-dotnet-framework) so you can understand the usage of our new SDK. 

Event for scripting, the initial step is still to direct user to Xero login for authorisation, however after you have obtained the access token and refresh token, the script can update and refresh tokens in the background to keep the API connections open. 

We have some [guides and tools](https://developer.xero.com/documentation/api-guides/machine-2-machine) made for your use cases.

**Comment by jenksguo** [comment]
Hi @erossini, thanks for building to Xero API. I am closing this one but please feel free to re-open this issue if you need. :-)
