### ISSUE TITLE
AccountingApi.GetAccountsAsync() is returning 'Unauthorized' (HTTP 401) error.

### ISSUE THREAD

**Issue by mobilewares** [XeroAPI/Xero-NetStandard#178]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2 2.2.0  (C#)

**Describe the bug**
AccountingApi.GetAccountsAsync() method is returning 'Unauthorized (401)' error (for code based oAuth2).  I've tried with and without a where clause (ie.  Type="BANK").
Same issue exists when calling the URL Endpoint directly (with valid headers). It's working when using the Online Xero API Previewer however.
Note that other queries (such as Getting Invoices) is working fine in same context - so believe it's a bug and not an auth issue.

**To Reproduce**
Call API method with Oauth2 (code) authenticated client.

**Expected behavior**
Should return populated Accounts instance.

**Additional context**
I'm currently using the json output from the Xero Api Previewer due to bug (as workaround) - would prefer to be getting this live so I have latest set of Accounts.

**Comment by mobilewares** [comment]
Solved : figured out why - the 'accounting.settings' scope needed to be included to get the list of Accounts.

Request : Would really help if you could please include the pre-requisite scopes in your SDK documentation (where each GET/PUT/POST etc) method is described - would avoid some confusion with this.

**Comment by MJMortimer** [comment]
@mobilewares There is a page outlining all the scopes and what they allow here: https://developer.xero.com/documentation/oauth2/scopes

**Comment by mbrightenfield** [comment]
I have been running into the same issue with **GetOrganisationsAsync** and **GetTrackingCategoriesAsync**.  I do include _accounting.settings_ in the scope but still receive a 401 for these requests.

Currently using **Xero.NetStandard.OAuth2 3.0.0 (C#)**

Other methods I am using that are working successfully:
- GetInvoicesAsync
- UpdateOrCreateContactsAsync
- UpdateOrCreateInvoicesAsync
- CreatePaymentsAsync
- CreateCreditNotesAsync

However, I appear to be receiving 401 on all API methods that require the accounting.settings scope even when I provide it in the config.  Might there be something else I'm missing here?
