### ISSUE TITLE
Delete method should be add in this interface

### ISSUE THREAD

**Issue by bpadhiyar4** [XeroAPI/Xero-NetStandard#179]
https://github.com/XeroAPI/Xero-NetStandard/blob/da13b9876d4c847799ae5e2fd9bfe61c4c53ee97/Xero.NetStandard.OAuth2Client/src/Client/IXeroClient.cs#L17

Declaration of Delete method is missing in interface IXeroClient.

**Comment by jenksguo** [comment]
Hi @bpadhiyar4, I think you might be using an older version of the Xero.NetStandard.OAuth2Client SDK. The delete function has been added in the v0.0.4 now. :-) 

See my response [here](https://github.com/XeroAPI/Xero-NetStandard/issues/181). 

Any other issues please feel free to raise it here again.

**Comment by bpadhiyar4** [comment]
Hii @jenksguo , surely you have added the DeleteConnection method in XeroClient but I'm talking about the declaration of this method in IXeroClient so we can use it by DI.

**Comment by bpadhiyar4** [comment]
@jenksguo kindly refer this pull request #180 .

**Comment by jenksguo** [comment]
Doh, thanks for the reply. I have reopened the issue and will fix this in the next release.

**Comment by jenksguo** [comment]
Hi @bpadhiyar4 I have just released a[ new Oauth2Client v0.0.5](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/0.0.5).

Please let me know if there is any other issues.

**Comment by bpadhiyar4** [comment]
@jenksguo Thank you
