### ISSUE TITLE
Delete Method Not Added in IXeroClient.

### ISSUE THREAD

**Issue by jennyPatel** [XeroAPI/Xero-NetStandard#181]
Delete method is not being added in xero client interface and only added in class. So I am not able to access it .
Kindly resolve it as soon as possible.
Hope you will make it sooner.
Thanks

**Comment by jenksguo** [comment]
Hi @jennyPatel, thanks for raising this. Could I please get you to confirm the version of the Xero.NetStandard.OAuth2Client SDK you are using?

I have added a **_DeleteConnectionAsync_** method in version v0.0.4 so you can perform this delete action. If you are not using the latest one, you should be able to upgrade to this patch and use the disconnection. See updated release note [here](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v2.1.0). 

We also have updated the Xero.NetStandard.Oauth2 main SDK to include a set of identity APIs, you can also use the method there [to delete a connection](https://github.com/XeroAPI/Xero-NetStandard#identity-apis).

**Comment by jennyPatel** [comment]
Hello,
I was facing an issue because delete method is added in class but not in
interface. I am using latest version. So kindly add that method in
interface too so I can use it!
Hope you will resolve issues asap!
Thanks & Regards
Janvi.

**Comment by jenksguo** [comment]
Hi Jenny, another dev reported this issue have told me this as well. I will get it fixed as soon as possible.

**Comment by jenksguo** [comment]
@jennyPatel Just released a new [Oauth2Client v0.0.5](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/0.0.5). 

Please let me know if there is any other issues.

**Comment by jennyPatel** [comment]
Thank you!!
