### ISSUE TITLE
SDK not passing back exception on 429 too many request repsonse

### ISSUE THREAD

**Issue by jenksguo** [XeroAPI/Xero-NetStandard#183]
Raising on behalf of an developer's feedback via email: 

**Describe the bug**
"The server returns the 429 (too many requests) response, but your C# SDK swallows the exception and does not even put it in the InnerException of the exception the SDK returns. "

**To Reproduce**
make more than 60 api calls in a rolling 60 sec window

**Expected behavior**
Descriptive exception being passed back.

**Comment by glensow** [comment]
The oAuth1.0 API threw a Xero.Api.Infrastructure.Exceptions.RateExceededException, which made it easy to detect, pause and retry.  Something like this would be great.

**Comment by jenksguo** [comment]
Hi @glensow , thanks for your feedback, we are looking into adding the throttling in the SDK in the near future.

**Comment by chameleon67** [comment]
Hi @jenksguo 
Any update on this "Feature Request"?

We are also experiencing intermittent issues with 429 (too many requests) responses. This can happen when sending a single invoice or 10 invoices (which we batch into a single request).
However the server response does not provide us with the detail to resolve the issue as per the docs https://developer.xero.com/documentation/oauth2/limits

**Comment by jeffvictorino** [comment]
I have been working around this bug since  I started working on Oauth2 client. My app is a microservice and having to deal with this exception **reactively** is  proving too difficult. In the meantime, i had to wrap the API clients with a repository that tracks  the remaining limit which throttles the request based on the previous request's response headers.

It would be great  if the exception is thrown so we can **reactively** handle throttling on the current request.

**Comment by jenksguo** [comment]
Hi @jeffvictorino @chameleon67, thanks for commenting on the issue. I am looking at how our errors are handled in general. I agree this rate limit error response should throw an exception for an easier trigger for retries.  

It will be looked at this week, but to speed it up, would you be able to collaborate with me and suggest a solution on the existing code? 

Many thanks.

**Comment by MatthewSteeples** [comment]
We've made a spike of our own implementation of some of these details if anyone is interested. Things like automatically respecting rate limits before issuing requests, automatically renewing AccessTokens before they expire etc (not yet implemented). Also not having to pass the tenant id and access token in to every request.

I'm more than happy to talk it through with anyone, but it won't be possible to keep it backward compatible so people would have to make some changes to adapt to it.

**Comment by jeffvictorino** [comment]
@jenksguo, my repository work around works for now, but its more of a stop gap measure.

I believe Xero API returns the correct HTTP error codes, but we need to handle it in the C# client. I was about to dig into the source code, but one thing that prevented me from doing that is it seems the API client is generated? 

I'm not aware of your workflow whenever there are changes to Xero API, but handling error messages is something that can get  overwritten everything you update to the latest API?

**Comment by jenksguo** [comment]
Hi @jeffvictorino, thanks for looking into it. 

Yes, it is generated based on the template provided here. We have tweaked it quite a bit, it is not open-source yet but we do have a plan to make it available for contribution once the template is more stable. 

It would be good if you could recommend a solution if not a PR, happy to try your solution, test and release. :-) 

This is on our road map to fix, your collaboration can hopefully bring this in earlier.

**Comment by JWealthall** [comment]
Hi @jenksguo,

I have the same request.  At the moment, to create a stable solution, I would have to track my usage across an application (and store the last _limits details_ after every call) and put some kind of limiter in.  That would be a huge overhead when developing an application. Being able to get the limit figures (and _next retry in_) after an error has occurred would be easier to develop with.

Could we also have _uniform_ exception messages across this API.  In some instances you have to look at the error code (when hitting a limit) and in others the information is in the message (when a client id isn't supplied in a token refresh).

**Comment by jenksguo** [comment]
Hi @JWealthall @MatthewSteeples @jeffvictorino @chameleon67 @glensow,  the team have made an improvement on how 429 gets handled in the [v3.10.0 SDK](https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.10.0
). 

Instead of giving no content, we now provide some templated messages to tell you which limit got hit. 

See release note with examples [here](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.9.0). 

Code details [here](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Client/Configuration.cs#L57)

**Comment by jenksguo** [comment]
If you have any other issues related to 429 errors please feel free to reopen the issue.

**Comment by JWealthall** [comment]
Hi @jenksguo, thank you for the update.  I'll pull the SDK and incorporate it into the development.

**Comment by LucasRodriguez0302** [comment]
Is there a plan to include something similar to the previous RateLimiter class, to avoid having custom implementations in code?
