### ISSUE TITLE
Connection machine to machine

### ISSUE THREAD

**Issue by erossini** [XeroAPI/Xero-NetStandard#188]
How can I have a connection machine to machine? At the moment I have to create a token from Postman and then refresh the token every 30 minutes.

**Comment by jenksguo** [comment]
Hi @erossini, in OAuth 2.0, all of the tokens expires 30 minutes there is no permanent token unfortunately. 

I would recommend building logic to refresh to token Pre-req script to detect expired token and refresh. 

https://www.youtube.com/watch?v=agZjgOteaa0&t=240s

**Comment by jenksguo** [comment]
@erossini Closing the issue due to lack of response. Please kindly re-open if there is any more questions/issues. :-)
