### ISSUE TITLE
Payment Type Enum value conflict

### ISSUE THREAD

**Issue by shereenfathima** [XeroAPI/Xero-NetStandard#190]
We are trying to interpret the PaymentTypeEnum constant values against Old API. The constant values have been changed from the old SDK to the new SDK but the API is still referring to the OLD SDK values. 

![2020-06-11_1115](https://user-images.githubusercontent.com/61031435/84329624-45788280-abd9-11ea-8bae-2166c7b0c6ee.png)

When we try to get the Invoice payments the API is giving out 0 value for Payment type which cannot be found in the PaymenetType Enum.
![2020-06-11_1204](https://user-images.githubusercontent.com/61031435/84330867-a5245d00-abdc-11ea-9be6-6064f507807e.png)

**Comment by jenksguo** [comment]
Hi @shereenfathima, thanks for reporting issues. 

Could you please expand on "_but the API is still referring to the OLD SDK_" , did you meant that new SDK enum is not being accepted by Xero API and return a validation error?

**Comment by shereenfathima** [comment]
@jenksguo new SDK values are accepted but the values returned from the API are not the expected values.

I have created an Invoice in Xero and add the payments to it. When I try to get the Payments via API the API returned 0 value for Payment Type. There is no corresponding value in the new SDK Enum.

**Comment by shereenfathima** [comment]
@jenksguo any feedback????

**Comment by benedict-odonovan** [comment]
Same issue here. 

To reproduce it you can add create an invoice, add a payment to it, and call the Get functions for Invoice and Payment separately. The Invoice function returns a nested Payment entity with a StatusEnum of 0 (which doesn't correspond to anything in the enum), while the payment function returns an entity with a StatusEnum of 1 (Authorised).

`
(await Api.GetInvoiceAsync(AccessToken, XeroTenantId, InvoiceGuid.Value))._Invoices;
`
vs.
`
(await (Api.GetPaymentAsync(AccessToken, XeroTenantId, PaymentID.Value));
`

**Comment by jenksguo** [comment]
@shereenfathima @benedict-odonovan Sorry about the delay. 

Thanks for details and the way to replicate it. 

I will look into this early next week and make a fix quickly.

**Comment by jenksguo** [comment]
Hi @shereenfathima @benedict-odonovan, that took me embarrassing long to respond. 

I have investigated this and found paymentTypes returns and sends quite normally with the existing enums. 

![image](https://user-images.githubusercontent.com/41350731/93014941-85943a80-f5f8-11ea-8f4b-08765968e6ac.png)

The old SDK also has the ENUMs as the new ones. See here: https://github.com/XeroAPI/Xero-NetStandard/blob/oauth1/Xero.Api/Core/Model/Types/PaymentType.cs

Our API documentation also confirms it: 
https://developer.xero.com/documentation/api/types#PaymentTypes

Would you be able to provide the responses of the API to me so I can take a closer look at how the SDK mis-behaved?

**Comment by MatthewSteeples** [comment]
@benedict-odonovan The nested entities are not designed to have all of their properties populated. The 0 value isn't meant to indicate it's using the value from the old Enum, it's that there is no data there

**Comment by jenksguo** [comment]
Thanks @MatthewSteeples, hey @benedict-odonovan @shereenfathima let me know if you are fine with this. I will close this issue in a week.

**Comment by shereenfathima** [comment]
@jenksguo It is still returning zero value if I check the payments using the xeroInvoice.Payments. list.

**Comment by jenksguo** [comment]
Hi @shereenfathima sorry about the delay it took me sometime to figure out as I was getting payments. 

When getting invoices, Xero API does not really return the paymentType so .NET default the value to 0. 

E.g. when Xero API returns invoice with payments without PaymentType: 

```csharp
        "Payments": [
        {
          "PaymentID": "7f82af19-11cf-403a-8b26-743178e52ca1",
          "Date": "\/Date(1605139200000+0000)\/",
          "Amount": 150.00,
          "CurrencyRate": 1.000000,
          "HasAccount": false,
          "HasValidationErrors": false
        },
        {
          "PaymentID": "b118cfcb-d9cd-4e37-b648-731438283467",
          "Date": "\/Date(1605139200000+0000)\/",
          "Amount": 500.00,
          "CurrencyRate": 1.000000,
          "HasAccount": false,
          "HasValidationErrors": false
        }
      ], 
```

SDK will return default value 0: 

![image](https://user-images.githubusercontent.com/41350731/98897379-62561080-24ff-11eb-90f6-fa274695f418.png)

I would recommend using the **_GetPaymentAsync_** method instead if you really need the value. 

Let me know if this can work for you.
