### ISSUE TITLE
Types mismatch

### ISSUE THREAD

**Issue by pavlodenys** [XeroAPI/Xero-NetStandard#193]
Version 3.0.0

There are some mismatch types in [EarningRates.cs](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollAu/EarningsRate.cs), in old version [EarningRates.cs](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Payroll/Australia/Model/EarningsRate.cs) AccrueLeave has type bool, in new version AccrueLeave is decimal?, so response from GetPayItemsAsync is null. Also in [LeaveType.cs](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollAu/LeaveType.cs) NormalEntitlement  has type int?, in old version [NormalEntitlement.cs](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Payroll/Australia/Model/LeaveType.cs) has decimal. 

**To Reproduce**
1. call GetPayItemsAsync method
2. Response = null

**Expected behavior**
1. Response is valid object

https://developer.xero.com/documentation/payroll-api/payitems#EarningsRatesEdit
https://developer.xero.com/documentation/payroll-api/payitems#LeaveTypesEdit

**Comment by SidneyAllen** [comment]
Addressed in version 2.2.5 of Xero OpenAPI spec
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.2.5
