### ISSUE TITLE
Payroll AU: GetPayItemsAsync not returning data

### ISSUE THREAD

**Issue by RodrigoCamposM** [XeroAPI/Xero-NetStandard#196]
**SDK you're using:**
package id="Xero.NetStandard.OAuth2" version="3.1.0" targetFramework="net461" 
package id="Xero.NetStandard.OAuth2Client" version="0.0.5" targetFramework="net461" 

**Describe the bug**
We are having some problems using the available Xero SDK for OAuth2 for the API: Payroll AU.
When calling the method ‘GetPayItemsAsync’, we are getting a null result, but as you can see at the right of the image (refer to below image please), the API is returning data.

![PayrollAU1](https://user-images.githubusercontent.com/67598557/86031473-dc2fa680-ba03-11ea-9b25-17fcf3ce598b.png)

**Comment by pavlodenys** [comment]
@RodrigoCamposM I had similiar issue, please take a look to to #193, I suppose we need to wait until next release, or you can build  dll locally before new version.

**Comment by jenksguo** [comment]
Hey @pavlodenys thanks for linking this one with your issue. Did you issue get addressed by the end?

**Comment by nickbeentjes** [comment]
Hi ... LeaveTypes.LeaveLoadingRate also needs to be changed to double

**Comment by pavlodenys** [comment]
@jenksguo I fix Xero-NetStandard locally and will update lib with new version.

**Comment by shereenfathima** [comment]
@pavlodenys Is this fixed in 3.1.0?

**Comment by pavlodenys** [comment]
@shereenfathima No.

**Comment by jenksguo** [comment]
Hi @RodrigoCamposM @pavlodenys, sorry about the delay in this fix. 

We have updated the NormalEntitlement which I believe is what caused the failure.  Check out [v3.2.0](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.2.0)

Thanks for pointing out the LeaveLoadingRate also needed to be changed to double. 

I will make a PR to our OpenAPI Spec and release a new version to address this.

**Comment by jenksguo** [comment]
Hi @RodrigoCamposM @pavlodenys, issue have been addressed in [v3.2.1](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.2.1) patch.

I will leave this issue open for another week. Let me know if you are able to get unblocked from this.

**Comment by jenksguo** [comment]
Please re-open if there is any other issues.
