### ISSUE TITLE
Doesn't work with newer version of RestSharp

### ISSUE THREAD

**Issue by paulallington** [XeroAPI/Xero-NetStandard#198]
**SDK you're using (please complete the following information):**
 - Version 3.1.0

**Describe the bug**
Error while getting connections: Method not found: 'Void RestSharp.RestClient.AddHandler(RestSharp.Deserializers.IDeserializer, System.String[])'.
RestSharp dependency is >= 106.6.7
The installed version was 106.11.4
(Works if downgraded to 106.6.7)

**To Reproduce**
var identityApi = new Xero.NetStandard.OAuth2.Api.IdentityApi();
var connections = await identityApi.GetConnectionsAsync(club.XeroSettings.Token.AccessToken);
With latest version (currently 106.11.4) of RestSharp added

**Expected behavior**
To return connections without exception

**Comment by jenksguo** [comment]
@paulallington Thanks for that, in the new release I will lock that in.

**Comment by jenksguo** [comment]
@paulallington Just got around to this one. 

Even the latest openAPI generator template is only using 106.10.1 and not 106.11. I am afraid this will take a long time before we can confidently upgrade to 106.11. 

Can we collaborate on this. What kind of code changes is required between .10 and .11?

**Comment by JayB-robert** [comment]
Any update on the this upgrading to latest RestSharp version?

**Comment by JayB-robert** [comment]
Hi @jenksguo thank you. I'll wait for the next release as the v106.10.1 still breaks some of our internal codes.

**Comment by jenksguo** [comment]
Hey @JayB-robert, making the change to the next version has quite a large implication on how we generate it. Would you please provide some more details of it to justify going to a higher version?

**Comment by JayB-robert** [comment]
@jenksguo this is missing in v106.10.1 - https://github.com/restsharp/RestSharp/issues/1450 and our internal codes use this heavily .

**Comment by jenksguo** [comment]
Thanks @JayB-robert for your solution. I have tested and released it in v3.5.0 now. 

@paulallington v3.5.0 addressed this issue. 

Please re-open if there is anything further.
