### ISSUE TITLE
Missing enum value on a Quote object

### ISSUE THREAD

**Issue by ThirstyJarek** [XeroAPI/Xero-NetStandard#200]
Hi Jenks,

**SDK you're using (please complete the following information):**
 - Version 3.1.0

**Describe the bug**
Missing enum value for the 'QuoteStatusCodes' on a Quote object. The 'DELETED' enum is missing. Interestingly the value is documented in the [API documentation]( https://developer.xero.com/documentation/api/types#QuotesStatuses), but missing from [the C# SDK](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/QuoteStatusCodes.cs).

**To Reproduce**
1. Make an api call to GetQuotesAsync using the C# SDK for any batch of quotes that contains a quote with a QuoteStatusCodes value of 'DELETED'.
2. It fails to deserialise the list of quotes correctly, resulting in the api call data being NULL.

**Expected behavior**
Deserialisation of JSON to the Quote object to work.

**Comment by jenksguo** [comment]
Thanks @ThirstyJarek, I have found DELETE missing from OpenAPI spec. We will cover this on the next code generation release. 

@SidneyAllen I will make a pull request to the spec today.

**Comment by ThirstyJarek** [comment]
Thanks for the quick response Jenks!

**Comment by jenksguo** [comment]
@ThirstyJarek new release planned next week.

**Comment by jenksguo** [comment]
Hi @ThirstyJarek, DELETE for QuoteStatusCode is in release [v3.2.0](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.2.0) now. 

Please re-open if there is any issue found.
