### ISSUE TITLE
Many parities asked by a developer

### ISSUE THREAD

**Issue by jenksguo** [XeroAPI/Xero-NetStandard#202]
Raising on behalf of a community developer. 

**SDK you're using (please complete the following information):**
 - Version 3.1.0

**Describe the bug**
We are in the process of moving to oauth2 and encountering a few issues and discrepancies between APIs and SDK

1. In old Xero.Api.Core.Model.Line class AccountId, AccountName, AccountType  were present and used in our application. In new Xero.NetStandard.OAuth2.Model.Accounting.ManualJournalLine those values are missing also I do not see them on API documentation https://developer.xero.com/documentation/api/manual-journals I only see AccountCode. Can you advise what can I do in my situation? I mean should I fetch account details separately? (This could be problematic because account endpoint expects AccountID + would add much load to our application)

2. In old Xero.Api.Core.Model.CreditNote class there was a DueDate filed and it is missing in new Xero.NetStandard.OAuth2.Model.Accounting.CreditNote and documentation.

3. In old Xero.Api.Payroll.Australia.Model.Employee class there was Occupation and PayrollCalendarName fileds and also they are missing in corresponding Australian model returned from c# SDK.

4. Same situation with Xero.Api.Payroll.Australia.Model.LeaveLine FullTimeNumberOfUnitsPerPeriod filed.

**Expected behavior**
Parity with old Xero.Api SDK.

**Comment by Beczka** [comment]
@jenksguo do we have any progress here?

**Comment by jenksguo** [comment]
Hi @Beczka, sorry it had been a while on this. I have closed a few other issues and made SDK more up to date. This is next on my agenda now. :-)

**Comment by jenksguo** [comment]
Hi @Beczka, sorry for the late response. 

I took a few testing and found the API and SDK is working for LeaveLine, but the behaviour is different from the previous SDK. 

Getting all employees will only give you some high level details so **_LeaveLines_** is empty and **_PayTemplate_** will be null.

When getting the employee information,  you will need to used **_GetEmployeeAsync_** (by EmplyeeID) to see leaveLines objects and **_FullTimeNumberofUnitsPerPeriod_** in the **_PayTemplate_** object: 
![image](https://user-images.githubusercontent.com/41350731/98903206-3e003100-250b-11eb-8854-7859890c5b7b.png)

![image](https://user-images.githubusercontent.com/41350731/98903140-1a3ceb00-250b-11eb-8e69-2e59966de148.png)

Please let me know if this explained the behaviour well enough.

**Comment by jenksguo** [comment]
Update on the issues: 

1. The older SDK does one more API call to retrieve the account ID. We have decided not to replicate that in the new SDK as the template treats API calls separately so prevents us from doing so.

2. The DueDate is now in the CreditNote object https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/CreditNote.cs#L140

3. Occupation we can't find this field in our API. I think the closest you can get to is the JobTitle. One can get this by doing GetEmployeeAsync(emplyeeID).
This is the same situation as 1. payroll calendar name can be retrieved via payroll calendars type. 

4. Answered above. 

Closing the issue as all are answered. Please re-open if you need.
