### ISSUE TITLE
Add PurchaseOrder Attachments endpoints

### ISSUE THREAD

**Issue by techtoniq** [XeroAPI/Xero-NetStandard#203]
Currently there's no ability to add attachments to Purchase orders through this package.  The old .net API package had this functionality. Would be good if Purchase Order attachments CRUD endpoints were available.

**SDK you're using (please complete the following information):**
 - Version 1.0.0

**Comment by jenksguo** [comment]
Hi @techtoniq, thanks for bring this up. We will look into adding this once more prioritised issues are resolved. :-)

**Comment by jenksguo** [comment]
Hi @techtoniq, I will need to get this operation created in our OpenAPI spec first before generating it. Please stay tuned for this.

**Comment by jenksguo** [comment]
@SidneyAllen, I think we need to add the following methods to OAS: 

GetPurchaseOrderAttachmentByFileName
CreatePurchaseOrderAttachmentByFileName
UpdatePurchaseOrderAttachmentByFileName

I can create them, test and do a PR to OAS if you like?

**Comment by jenksguo** [comment]
Hi @techtoniq, thanks for reporting the issue, the latest [version 3.6.2](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.6.2) now has purchase order attachments. 😃
