### ISSUE TITLE
Question: Why do some models do not include a "List<ValidationError> Warnings" property?

### ISSUE THREAD

**Issue by wildhart** [XeroAPI/Xero-NetStandard#209]
**SDK you're using (please complete the following information):**
 - Version Xero.NetStandard.OAuth2 3.1.0

**Describe the bug**
Your [API Docs](https://developer.xero.com/documentation/api/requests-and-responses) state that when using `summarizeErrors`, the validation errors and warnings will be returned as:
```
  ...
  },{ 
    "InvoiceID": "5ceffde5-6786-4987-b03a-bf88d262c286",
    ...
    "StatusAttributeString": "WARNING",
    "Warnings": [{ 
      "Message": "Only AUTHORISED invoices may have SentToContact updated."
      }]
  },{ 
    "InvoiceID": "5ceffde5-6786-4987-b03a-bf88d262c286",
    ...
    "StatusAttributeString": "ERROR",
    "ValidationErrors": [{ 
      "Description": "Invoice not of valid type for creation"
      }]
  }]
```

However, in your library not all models include the `Warnings` parameter.  Eg, the [Invoice](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/Invoice.cs) and [Recipt](https://github.com/XeroAPI/Xero-NetStandard/blob/125a7db7e3ce5828ef4ca3228e0101608c51cbb0/Xero.NetStandard.OAuth2/Model/Accounting/Receipt.cs) models include:
```
[DataMember(Name="Warnings", EmitDefaultValue=false)]
public List<ValidationError> Warnings { get; set; }
```

but the [Contact](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/Contact.cs) and [Item](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/Item.cs) models do not.

Do we assume that models which don't have the `Warning` parameter cannot have warnings, only errors?

**Comment by jenksguo** [comment]
Hi @wildhart, you are correct, some of our endpoints don't return "Warnings" possibly because they don't support summarisedErrors flag. 

Our different API services returns different validation error object which presents a great challenge to the SDK project. This is next on my to do list. We might need to use a common error object for all API response that hopefully provide some certainty in dealing with validation errors. Stay tuned.

**Comment by wildhart** [comment]
Thanks for the response @jenksguo.

Until yesterday I hadn't actually experienced any occurrences of `StatusAttributeString == "WARNING"`.  But yesterday we were test importing some invoice payments where a payment already existed with the same `Reference` on the parent invoice, and we received a warning flag with no way to determine what the actual warning was.  This is in the Accounting API so should support the `summarisedErrors` flag, but the [Payment](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/Payment.cs) class doesn't include the `Warnings` list.

Staying tuned... Thanks.

**Comment by jenksguo** [comment]
Hey @wildhart, I will close this issue for now as you query was answered. Please feel free to re-open if there is more discussion. 

The work on improving general exception & error handling is under way now. :-)
