### ISSUE TITLE
Refresh access token in PKCE

### ISSUE THREAD

**Issue by ManvirDynamic** [XeroAPI/Xero-NetStandard#223]
We are using OidcClientOptions for credentials and login in PKCE and AccountingApi to access your API.

We have build a c# console app using PKCE and it seems to be working fine. Only problem is that we are not able to refresh access token.

Our code is as follows:

It is working fine till last where I get organisations, can you please tell how to refresh after that.

var options = new OidcClientOptions
{
Authority = "https://identity.xero.com",
ClientId = "",
Scope = "openid profile email offline_access files accounting.transactions accounting.contacts accounting.settings",
RedirectUri = "http://localhost:5000/signin-oidc",
FilterClaims = false,
Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
LoadProfile = true
};
options.Policy.Discovery.ValidateEndpoints = false;
var client = new OidcClient(options);
Process.Start(state.StartUrl);
var context = await http.GetContextAsync();
result = await client.ProcessResponseAsync(context.Request.Url.AbsoluteUri, state);
var accountingApi = new AccountingApi();
IXeroToken token = new XeroOAuth2Token();
token.AccessToken = result.AccessToken;
token.RefreshToken = result.RefreshToken;
token.ExpiresAtUtc = result.AccessTokenExpiration;
token.IdToken = result.IdentityToken;

var organisations = await accountingApi.GetOrganisationsAsync(token.AccessToken, XeroHelper.GetTenantId());

How to refresh token(i.e IXeroToken token) now???

In OAUTH2 we do as below, but that involves XeroConfiguration
XeroClient xeroClient = GetXeroClientInstance(xconfig);
var refreshToken = await xeroClient.RefreshAccessTokenAsync(tokenFromStorage); //use the latest token you have

However in above class "XeroClient" to get instance, we have to provide ClientSecret and PKCE does not have a client secret. So how we can refresh access token in PKCE?

**Comment by MJMortimer** [comment]
Hey @ManvirDynamic,

If I'm remembering right, in a refresh request the clientId and clientSecret are only used on basic auth when calling the refresh token endpoint (i.e. base64(clientId:clientSecret)). As you've said, PKCE clients don't have client secrets and so in the basic auth for refresh requests, clientSecret is essentially just omitted.

Can you please try using string.Empty in place of the clientSecret where necessary in your code and let me know if you have further issues?

**Comment by jenksguo** [comment]
Hey @ManvirDynamic, [this article](https://damienbod.com/2018/04/25/oauth-authentication-with-pkce-for-a-net-core-console-native-application/) seemed to have provided a solution on how to configure it for OPCE flow. 

Let us know if you still face issue with PCKE flow after trying this fix. 

```csharp
var options = new OidcClientOptions
    {
        Authority = _authority,
        ClientId = "native.code",
        RedirectUri = redirectUri,
        Scope = "openid profile native_api",
        FilterClaims = false,
        Browser = browser,
        Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
        ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
        LoadProfile = true
    };
 ```

**Comment by JWealthall** [comment]
I finally worked it out and it can all be done via the SDK (I couldn't find an example anywhere from Xero).   Below is my test code which allows you to seed the starting _token_ (use the data from XOAuth), but will use a saved token (if you've refreshed it).  At some point I will create a fully worked (and documented) example and post it up.

```
var accessToken = "<AccessToken>";
var identityToken = "<IdentityToken>";
var refreshToken = "<RefreshToken>";
var clientId = "<ClientId>";

var xconfig = new XeroConfiguration();
xconfig.ClientId = clientId;

var client = new XeroClient(xconfig) ;

IXeroToken token = null;

if (System.IO.File.Exists("Token.json"))
{
    string savedJson = System.IO.File.ReadAllText("Token.json");
    token = JsonConvert.DeserializeObject<XeroOAuth2Token>(savedJson);
}

if (token == null)
{
    token = new XeroOAuth2Token();
    token.AccessToken = accessToken;
    token.IdToken = identityToken;
    token.RefreshToken = refreshToken;
}

IXeroToken newToken = await client.RefreshAccessTokenAsync(token);
if (newToken != null)
    token = newToken;

string json = JsonConvert.SerializeObject(token, Formatting.Indented);
System.IO.File.WriteAllText("Token.json", json);
```
Once you've got a new token you can get a list of tenants (my example just uses the first in the list)

```
var tenantList = await client.GetConnectionsAsync(token);
var tenant = tenantList[0].TenantId.ToString();
```

Finally you can use the API itself using something like (with out the error checking you should include)

```
var api = new AccountingApi();

var response = await api.GetInvoicesAsync(accessToken, tenant);
var respInvoices = await api.GetInvoicesAsync(accessToken, tenant, page: 1, where: "");
var invDate = respInvoices._Invoices[0].Date;

var recurring = await api.GetRepeatingInvoicesAsync(accessToken, tenant);
var status = recurring._RepeatingInvoices[0].Status;
var schedule = recurring._RepeatingInvoices[0].Schedule;
```

**Comment by jenksguo** [comment]
I will be making a RequestRefreshtokenPkceAsync() to make this easier.

**Comment by jenksguo** [comment]
Hi @ManvirDynamic, apologies, I was confused earlier. For PKCE flow, the refresh access token method is exactly the same as the Code flow. You can use string.Empty for client secret. 

Closing this issue for now please reopen as needed.
