### ISSUE TITLE
AccountingApi.CreateContactsAsync doesn't respect ContactID

### ISSUE THREAD

**Issue by andrewgunn** [XeroAPI/Xero-NetStandard#226]
**SDK you're using (please complete the following information):**
 - Version 3.5.0

**Describe the bug**
I'm trying to create a Contact via this SDK. I need the ID of the Contact to be predictable so I'm specifying it before calling `CreateContactsAsync`. This method is actually doing a `PUT` call, which is possibly why the Contact ID is being ignored - the Xero API simply generates a new GUID. 

**To Reproduce**
1. Create a new `Contact` object
2. Set the `ContactID` field to a static GUID value
3. Call the `CreateContactsAsync` method on `AccountingApi`

**Expected behavior**
The Contact has an ID that matches the static GUID value.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by andrewgunn** [comment]
This also applies to creating Invoices, although it's unclear in the API docs whether the Invoice ID can be specified or not when creating one.

**Comment by jenksguo** [comment]
Hi @andrewgunn ContactID cannot be used when creating contact or invoice, it is a response that you will have to accept in our API response. 

Sorry there is no way to force assign an GUID, it is allocated by us for you to use. You will need to map it to a GUID on your data store and map it with Xero GUID. 

We use PUT to create new records and POST to update.

**Comment by andrewgunn** [comment]
That makes sense.

But your documentations for the HTTP API seems to suggest otherwise. That's what led me to believe it was possible.

![image](https://user-images.githubusercontent.com/722602/93815613-295f9500-fc4e-11ea-9714-10804b047626.png)

**Comment by jenksguo** [comment]
Hi @andrewgunn , I see. The example in the POST for update. 

The interpretation is: 
1. Include ContactID, then we treat this as an update operation
2. No ContactID, then we will create a new contact

**Comment by andrewgunn** [comment]
Ok, thanks 👍
