### ISSUE TITLE
Missing RepeatingInvoiceID field for Invoice model

### ISSUE THREAD

**Issue by jalley3** [XeroAPI/Xero-NetStandard#228]
**SDK you're using (please complete the following information):**
 - Version [e.g. 0.1.0]

**Is your feature request related to a problem? Please describe.**

Yes we need to be able to capture repeating invoice id's from invoices and this is being sent in the xero response, just not captured by this wrapper's object model.

**Describe the solution you'd like**

I have submitted PR with this fix in place.

**Comment by jalley3** [comment]
https://github.com/XeroAPI/Xero-NetStandard/pull/227

**Comment by jenksguo** [comment]
Hey @jalley3, thanks for reporting the issue. Were you creating or reading an invoice?

**Comment by jenksguo** [comment]
Hey @jalley3, never mind, I found it now. 

Thanks for contributing the the repository. All of the SDK is generated via an openapi generator template that is not yet public. We will close this PR but I will re-generate using your solution and credit to you.

**Comment by jenksguo** [comment]
@SidneyAllen, it looks like repeating invoice ID on invoice object is now supported by our API: 

![image](https://user-images.githubusercontent.com/41350731/93767051-c0cae500-fc5a-11ea-8d7e-b5c33761214b.png)

**Comment by jenksguo** [comment]
Hi @jalley3, I have just released version 3.6.1 which addressed this issue. 

Thanks for bringing this up. Now the fix would be propagated to SDKs for other languages too. 👍
