### ISSUE TITLE
Cannot get connections when using a migrated Xero token

### ISSUE THREAD

**Issue by jontymorris** [XeroAPI/Xero-NetStandard#229]
**SDK:**
 - Xero.XeroNetStandard.OAuth2 v3.2.1

**Describe the bug:**
When using a new Xero token (i.e. the user has just authorized our app with Xero) we can retrieve the token's connections using the accountingapi as expected. However, we have recently migrated our old Xero 1.0 connections and have run into some issues. For whatever reason, the connections API returns a null field for the authEventId field as shown below.
![Capture](https://user-images.githubusercontent.com/12991137/93706751-a53ddc80-fb7d-11ea-91ad-074b2be58479.PNG)

I'm not sure if the connections API is meant to return a null value here, but Newtonsoft.Json is unable to parse this into a valid GUID so the Xero-NetStandrad library throws an exception and we cannot get the connection details through code. I believe I have tracked the issue down to this line here https://github.com/XeroAPI/Xero-NetStandard/blob/35b49b1444a6a18bf37ebf82e6a4eb04e1337a90/Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs#L235

**To Reproduce**
1. You need an existing OAuth 1.0 partner app with working connections.
2. Migrate the old connection to using the [migration api](https://developer.xero.com/documentation/oauth2/migrate).
3. Now try to retrieve the migrated token's connections using the accounting API.
4. See Newtonsoft.Json throw a parsing error.

**Comment by jontymorris** [comment]
Unless this is a bug in Xero's connections API, I believe we should make the authEventId GUID property in the Tenant class nullable. Maybe then Newtonsoft.Json would be able to parse the request as expected.

**Comment by jenksguo** [comment]
Hey @jontymorris , thanks for collaborating with us and reporting this to us. 

I think the latest version of Xero.NetStandard.OAuth2Client's authEventId is a Guid? and nullable? 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2Client/src/Models/Tenant.cs#L8

Does it still occur an error if you are using [version 1.2.2](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.2.2)?

I think I missed 1.2.2, it had been on 1.2.1 the whole time.

**Comment by jontymorris** [comment]
@jenksguo oh excellent! I didn't realize how out of date of my Xero-NetStandard package was (v1.1.0) 🤦‍♂️
I went ahead and did some testing on both 1.2.1 and 1.2.2 and can confirm the bug has been fixed in both versions. Thanks for being on to it 👍

**Comment by jenksguo** [comment]
Thanks @jontymorris. Any other issues, please feel free to raise.
