### ISSUE TITLE
ApplicationSettings.cs - issues with extending configuration

### ISSUE THREAD

**Issue by saluton-mundo** [XeroAPI/Xero-NetStandard#23]
Hi,

Firstly, thanks for putting together a great API. I am currently working on an internal project to extend it's functionality and wasted a little time trying to resolve binding issues caused by naming. 

The issue involved the current strongly typed configuration entity Xero-NetStandard/Xero.Api/ApplicationSettings.cs. 

Can I respectfully suggest the following changes:

- Disambiguate the POCO name from "ApplicationSettings" to something like XeroApiSettings (as it's within the Xero.Api namespace)

- Add an optional string configSection to remove the requirement for host applications to use the hard coded value (use XeroApi as fallback if the string param is null):

        public ApplicationSettings(string path)
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile(path)
                .Build();

            ApiSettings = builder.GetSection("**XeroApi**");
        }

- Field names match the keys used in the configuration file:

        public string Key => ApiSettings["ConsumerKey"];

        public string Secret => ApiSettings["ConsumerSecret"];

        public string SigningCertificatePath => ApiSettings["SigningCertPath"];

        public string SigningCertificatePassword => ApiSettings["SigningCertPassword"];

Thanks for taking the time to consider the suggestions.

**Comment by gthompson121** [comment]
Firstly, I second saluton-mundo's praise for putting the API together. Very much appreciated.

If the proposed changes go ahead then `TokenStoreAuthenticatorBase` class will also require an update to include the `string path` parameter in the constructor to initialize `protected readonly ApplicationSettings ApplicationSettings = new ApplicationSettings();` with the new path parameter.

**Comment by MJMortimer** [comment]
Hey @saluton-mundo & @gthompson121,

Has this now been resolved with the release of PR #27 ?

**Comment by MJMortimer** [comment]
Apologies, I thought the PR had already been released but forgot there was still a small bit of ongoing discussion. I'll take another look when I get a chance

**Comment by MJMortimer** [comment]
This should now be resolved in #33. If you'd like some more enhancements to custom settings, please open a new issue with an updated description, cheers
