### ISSUE TITLE
GetExpenseClaimsAsync returns a null response if any claims have User.OrganisationRole=="REMOVED"

### ISSUE THREAD

**Issue by jeffpollard-aiimi** [XeroAPI/Xero-NetStandard#231]
**SDK you're using (please complete the following information):**
 - Version 3.6.0

**Describe the bug**
Any calls to the GetExpenseClaimsAsync endpoint, where the results are expected to contain any expense claims where the User.OrganisationRole=="REMOVED", incorrectly return a null response without any error being thrown.

**To Reproduce**

1.) Where a user has existing Expense Claims, set that User's Organisation Role to "REMOVED"
2.) Query the Expense Claims API endpoint with a call that is expected to include that user's Expense Claims:

- var MyExpenseClaims = MyXeroAPI.GetExpenseClaimsAsync(MyAPIToken, MyTenantID).Result; -> null response, no error thrown
- var MyExpenseClaims = MyXeroAPI.GetExpenseClaimsAsync(MyAPIToken, MyTenantID, null, "User.OrganisationRole=\"REMOVED\"").Result; -> null response, no error thrown
- Even if a newly removed user only has 1 expense claim in the system, a null response is still returned. In this example, the query is filtered on that specific user's email address (X@X.com). This query should return a single expense claim record, therefore API limiting does not seem to be the cause: var MyExpenseClaims = MyXeroAPI.GetExpenseClaimsAsync(MyAPIToken, MyTenantID, null, "User.EmailAddress=\"X@X.com\"").Result; -> null response, no error thrown

3.) Results can only be obtained from the GetExpenseClaimsAsync endpoint by specifically excluding removed users based on the User.OrganisationRole:

- var MyExpenseClaims = MyXeroAPI.GetExpenseClaimsAsync(MyAPIToken, MyTenantID, null, "User.OrganisationRole!=\"REMOVED\"").Result; -> results returned as expected, albeit without claims for removed users

**Expected behavior**
The endpoint should also return claims for removed users, in the same way as the API Previewer does:
[https://app.xero.com/Preview/expenseclaims](url)

**Comment by jenksguo** [comment]
@jeffpollard-aiimi Thanks for reporting the issue, we will test, confirm and fix as soon as possible.

**Comment by jamie-hoffmann-xero** [comment]
Hi @jeffpollard-aiimi, could you elaborate on `set that User's Organisation Role to "REMOVED"`. Specifically, what workflow do you follow in order to achieve this?

Would you be able to share your API response with us?

**Comment by jamie-hoffmann-xero** [comment]
Going to close this issue due to a lack of activity. However, feel free to reopen if you still need support. Thanks again for reporting the issue.
