### ISSUE TITLE
Shouldn't RepeatingInvoices have an UpdatedDateUTC field? 

### ISSUE THREAD

**Issue by czietsman** [XeroAPI/Xero-NetStandard#233]
**SDK you're using (please complete the following information):**
 - 3.6.0

**Is your feature request related to a problem? Please describe.**
No UpdatedDateUTC on RepeatingInvoice

**Describe the solution you'd like**
I would like to minimize the number of API calls I need to make. It looks like UpdatedDateUTC is usually paired with getting HistoryRecords, but this is missing for RepeatingInvoices

**Describe alternatives you've considered**
I'm assuming that history has always changed for RepeatingInvoices.

**Comment by jenksguo** [comment]
Hi @czietsman thanks for raising this. 

As you may have guessed, this is a limitation of our API. History record is the only place where you can get the updated time of the repeating invoice. 

I can provide this feedback to our API product team but this is going to be pretty low on our priority list, I am afraid. 

You can also raise your request here: https://xero.uservoice.com/

**Comment by jenksguo** [comment]
closing this since it had been there for a while. Please reopen if there is a need to discuss this again.
