### ISSUE TITLE
The Xero.NetStandard.OAuth2.Api.PayrollNzApi retuns null response

### ISSUE THREAD

**Issue by shereenfathima** [XeroAPI/Xero-NetStandard#235]
Version 3.6.0
Describe the bug:
The Payroll NZ API returns null respose for API calls. (e.g. GetEmployeesAsync,GetEarningsRatesAsync)

**Comment by deejcoder** [comment]
Hi

Just thought I'd contribute here, after investigating a little bit, with `GetEmployeesAsync` in particular, it seems it's a data related issue.

Gender is null, in my case as you can see in Postman,
![null_gender](https://user-images.githubusercontent.com/8052327/97794473-75dfbc80-1c5f-11eb-87ff-f4370ae40597.png)

The result is an error in the API response,
![null_gender_vs](https://user-images.githubusercontent.com/8052327/97794486-9c9df300-1c5f-11eb-894f-735f9235dc4f.png)

**Comment by azhilt** [comment]
Hi,
I get the same error. It seems Employee.Gender should be changed to nullable (GenderEnum? Gender).

**Comment by shereenfathima** [comment]
Version 3.10.0
Still null return for GetEmployeesAsync. Fetching one employee by Guid is fine. @jenksguo can you please look into this issue.

**Comment by shereenfathima** [comment]
@jenksguo can you please check on this issue

**Comment by jamie-hoffmann-xero** [comment]
Hi @shereenfathima, @azhilt, @deejcoder. Thanks for your patience on this issue. Optional enums have been a bit of a pain point for us, so we're working on building solutions that generalise well while also being safe.

Please be assured I'm actively working on this one -- I'll update again when I can.

**Comment by jamie-hoffmann-xero** [comment]
Hi @shereenfathima, @azhilt, @deejcoder. This issue should be fixed in SDK version 3.12.0.

In the above scenario, the `"Gender": null` property will be deserialised to the `0` enum value instead of throwing an exception.
This is the same behaviour as if `Gender` was omitted from the JSON altogether.

Thanks again for reporting and feel free to reopen if you need anything further.
