### ISSUE TITLE
Expose ApiClient's InteceptRequest And InterceptResponse.

### ISSUE THREAD

**Issue by xal1983** [XeroAPI/Xero-NetStandard#240]
**SDK you're using (please complete the following information):**
 - Version [e.g. 3.6.0]

**Is your feature request related to a problem? Please describe.**
When hitting rate limits, there is no clear indication that the rate limit is the cause of the error.
We're trying to develop a logging strategy to keep track of requests. The only option we have today is to fully reimplement ApiClient with both ISynchronousClient, IAsynchronousClient.

**Describe the solution you'd like**
The ApiClient class has 2 partial methods called "InteceptRequest" And "InterceptResponse" that seem like the perfect solution, but are not usable. Having those exposed as virtual methods that we could override (or as events) would be incredibly useful.

**Describe alternatives you've considered**
The different Api classes (such as AccountingApi) expose an ExceptionFactory. This could help with raising more specific errors when hitting the rate limits, but they don't provide context, just a response object with no request info. Also, it wouldn't help with logging every request, as it is only called when there is an error.

**Additional context**
There is another thing that makes this extra hard and that is the fact that Xero.NetStandard.OAuth2 and Xero.NetStandard.OAuth2Client use different technology for making requests. The former uses RestSharp and the latter uses HttpClient. HttpClient makes this remarkably simple to solve because you can create a custom HttpClientHandler to do all the work of analyzing request and response. When creating a new instance of the XeroClient, you can pass in an instance of the HttpClient. There's no way of doing this for AccountingApi/ApiClient.

Cheers,
Andrés

**Comment by bjcull** [comment]
Not sure how much control you have over the API code generator, but changing these partials to virtuals would be lovely. Same problem here, trying to implement logging, rate limiting and reactive token refresh.

**Comment by jamie-hoffmann-xero** [comment]
Hi @xal1983 and @bjcull, we have made these methods `protected virtual` in SDK version 3.10.0

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Client/ApiClient.cs#L186

https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.10.0
