### ISSUE TITLE
TimesheetStatus Enum doesn't contain all possible results - missing the enum for "REJECTED" and "REQUESTED"

### ISSUE THREAD

**Issue by phollida** [XeroAPI/Xero-NetStandard#241]
- Version 3.7.0

In Xero.NetStandard.OAuth2.Model.PayrollAu

Due to Issue #232 I am pulling my timesheets using a RestClient and deserializing into the Xero.NetStandard.OAuth2.Model.PayrollAu.Timesheet class using the Newtonsoft NuGet package.

So the code:

```
var responseObj = Newtonsoft.Json.JsonConvert.DeserializeObject<ResponseObj>(response.Content.ToString());
```
Where ResonseObj is:
```
        class ResponseObj
        {
            public string ID { get; set; }
            public string Status { get; set; }
            public string ProviderName { get; set; }
            public DateTime DateTimeUTC { get; set; }
            public List<Timesheet> Timesheets { get; set; }
        }
```

Fails with this error

```
Newtonsoft.Json.JsonSerializationException: Error converting value "REJECTED" to type 'Xero.NetStandard.OAuth2.Model.PayrollAu.TimesheetStatus'. Path 'Timesheets[48].Status', line 1, position 26685. 
---> System.ArgumentException: Requested value 'REJECTED' was not found. at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber) at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) 
```
Becasue there's no TimesheetStatus for REJECTED.  This is also the case for missing REQUESTED case. 

Adding Enums for "REJECTED" and "REQUESTED" will fix this.  

I am wondering if this may be one of the root causes of #232?

**Comment by phollida** [comment]
Included a Pull request to fix this issue above.

**Comment by jamie-hoffmann-xero** [comment]
Hi @phollida, thanks for your contribution. We generate our SDK using an OpenAPI generator, so we can't merge your PR, but your solution has been implemented and deployed.
I'm going to close this issue and the related PR -- feel free to reopen if you wish to discuss further.
