### ISSUE TITLE
Issue in creating List PayItem

### ISSUE THREAD

**Issue by AamilShohail** [XeroAPI/Xero-NetStandard#245]
I'm facing an issue **500 Internal Error An unhandled error with the Xero API - CX0010461032** 
Unable to resolve the issue "500 Internal Error An unhandled error with the Xero API - CX0010461032" even though I removed the outer square brackets to change the payload into an object type
### **This is the request body that I'm pushing to Xero**
```
{
  "EarningsRates": [
    {
      "EarningsType": "FIXED",
      "RateType": "FIXEDAMOUNT",
      "Name": "Ordinary Hours 123",
      "AccountCode": "477",
      "TypeOfUnits": "Hours",
      "IsExemptFromTax": true,
      "IsExemptFromSuper": false,
      "IsReportableAsW1": false,
      "CurrentRecord": true
    }
  ],
  "DeductionTypes": [
    {
      "Name": "Union Fees",
      "AccountCode": "826",
      "ReducesTax": false,
      "ReducesSuper": false,
      "IsExemptFromW1": false,
      "CurrentRecord": true
    }
  ],
  "LeaveTypes": [
    {
      "Name": "Casual Leave",
      "TypeOfUnits": "Hours",
      "NormalEntitlement": 3,
      "IsPaidLeave": false,
      "ShowOnPayslip": false,
      "CurrentRecord": true
    }
  ],
  "ReimbursementTypes": [
    { "Name": "Travel Costs", "AccountCode": "826", "CurrentRecord": true }
  ]
}
```

this is the json object I tried to push to xero.
Here is the code snippets that I used 
```
string iListPayItem = JsonConvert.SerializeObject(listObjResult);
                    var iPayItemList = JsonConvert.DeserializeObject<List<PayItem>>(iListPayItem);
                    foreach (var iPayItem in iPayItemList)
                    {
                        var ser = JsonConvert.SerializeObject(iPayItem);
                        var Jser = JsonConvert.DeserializeObject<PayItem>(ser);
                        var leaveType = new List<PayItem>() { Jser };
                        await PayrollAUApi.CreatePayItemAsync(accessToken, xeroTenantId, leaveType);
                    }
```
Can you tell me if there are any alternative ways for the approach ?

**Comment by jamie-hoffmann-xero** [comment]
Hi @AamilShohail, thanks for reporting this issue. I just wanted to get a bit more context about how to reproduce this error.

A few points to clarify:
1. What's the purpose of the repeated serialization/deserialization in your code snippet? 
2. Can you double check the types in your example? CreatePayItemAsync has the following signature: `Task<PayItems> CreatePayItemAsync (string accessToken, string xeroTenantId, PayItem payItem)` whereas in the code snippet we are passing a `List<PayItem>` as an argument. I was unable to compile this code.

**Comment by jenksguo** [comment]
Hi @AamilShohail , could you please help to clarify this bug so we can complete the investigation?

**Comment by AamilShohail** [comment]
Hi,
Apologies. Since I utilized the older version, it doesn't have a proper
function to populate each pay item. The latest version of Xero SDK had a
proper function. So I am pretty happy in populating payitem. Thanks a lot
for your continued support.
