### ISSUE TITLE
Access to the Limit and Next Retry information in API

### ISSUE THREAD

**Issue by JWealthall** [XeroAPI/Xero-NetStandard#246]
- Version 3.7.1 of Xero.NetStandard.OAuth2
 - Version 1.2.2 of Xero.NetStandard.OAuth2Client

I have been unable to get Limit information or Next Retry after an exception is thrown for hitting a limit from within the API (using the AccountingApi).

Would it be possible to expose the limit information (which is returned in the http headers) for both successful calls and ones where an exception has been thrown.

The alternative is for every integration to track that information in addition to the Xero API tracking the information.  It's a duplication of code and makes integrations to Xero significantly more complicated than just a _"wait for a bit and retry call"_.

One other alternative would be for the API itself to _wait and retry_ so long as the retry time was within definable parameters.

**Comment by czietsman** [comment]
You can supply your own ExceptionFactory and subclass ApiException. The
factory gets the response headers from which you can easily extract the
headers you want.

**Comment by JWealthall** [comment]
Hi Christo,

Thank you very much for the prompt reply. ☺

Do you have a working example of how to do this?  Or maybe a code snippet for it? (I have already spent some time trawling through the forums for this and it would be nice to save some time for my client)

Regards

John D Wealthall
Director
FRB Strategic Software Ltd
8 Hill View, Berkhamsted, Hertfordshire, HP4 1SA

Tel:
01442 870 361
Mobile:
07802 703 096
Email:
jdw@wealthall.com<mailto:jdw@wealthall.com>
Skype:
john.wealthall.home
Web:
www.wealthall.com<http://www.wealthall.com>

**Comment by JWealthall** [comment]
Don't worry Christo - I've downloaded the SDK and believe I have worked it out for myself.

**Comment by czietsman** [comment]
Hi John

This isn't a complete solution, but it is enough to get you going...

For every request you can get how many API calls remain. I wrapped
this up in a generic call and I rate limit my calls based on how many
API calls remain. We don't get a 'retry-after' header as far as I
know, but at least we know it won't be more than 60 seconds.

var minLimitRemaining =
response.Headers[X_MIN_LIMIT_REMAINING].FirstOrDefault();

The below will help you identify which rate limit you hit. I know
"X-Rate-Limit-Problem: minute" gets returned if you hit the minute
limit and I assume you'll get "X-Rate-Limit-Problem: day" if you hit
the day limit, but I haven't seen that yet. Maybe someone from Xero
can give us more detail.

I'm also not sure whether it is 60 seconds from the last call or if
rate limits get reset on the minute. I also don't know what the
behaviour is for the day limit.

Hope this helps.

Cheers,
Christo
private const string X_RATE_LIMIT_PROBLEM = "X-Rate-Limit-Problem";
private const string X_DAY_LIMIT_REMAINING = "X-DayLimit-Remaining";
private const string X_MIN_LIMIT_REMAINING = "X-MinLimit-Remaining";
private const string X_APP_MIN_LIMIT_REMAINING = "X-AppMinLimit-Remaining";


Exception ExceptionFactory(string methodName, IApiResponse response)
{
    var statusCode = (int) response.StatusCode;
    switch (statusCode)
    {
        case 400:
            return new XeroApiException(statusCode, $"Xero API 400
error calling {(object) methodName} :{(object)
response.Content.ToString()}", response.Headers, response.Content);
        default:
            return statusCode > 400 ? new XeroApiException(statusCode,
$"Xero API error calling {(object) methodName}: {(object)
response.Content.ToString()}", response.Headers, response.Content) :
(Exception) null;
    }
}

accountingApi = new AccountingApi
{
    ExceptionFactory = ExceptionFactory
};


private class XeroApiException : ApiException
{
    public XeroApiException(int errorCode, string message,
Multimap<string, string> headers, object errorContent = null) :
base(errorCode, message, errorContent)
    {
        Headers = headers;
    }

    internal Multimap<string, string> Headers { get; }
}

**Comment by JWealthall** [comment]
Thank you Christo, that definitely helps :)

**Comment by jamie-hoffmann-xero** [comment]
Hi @JWealthall and @czietsman. In light of Christo's helpful response and some recent improvements to error handling, I am going to close this issue -- feel free to reopen if needed. Thanks to you both for reporting and contributing.
