### ISSUE TITLE
Preventing Cross Site Request Forgery (XRSF) Attacks / AccountingApi Constructor 

### ISSUE THREAD

**Issue by steve34581133** [XeroAPI/Xero-NetStandard#248]
Hi all,

API support has suggested that I raise my issues here, so here goes...

1. How do we use the State property of the XeroConfiguration class found within the Xero.NetStandard.OAuth2.Config namespace to stop XRSF attacks? Currently we create and populate a new XeroConfiguration class and pass it to a new XeroClient class that is used to get a new refresh token but I am unable to find any code examples using the XeroClient.RefreshAccessTokenAsync method showing how the state is checked in the response. The response is by way of an instance of the XeroOAuth2Token class which does not contain a State property.
2. In what circumstances is the second constructor for the AccountingApi class (found within the Xero.NetStandard.OAuth2.Api namespace) used? The AccountingApi class  has two constructors. The default constructor takes no arguments but the second takes _basepath_ as a string argument. Is the second constructor for Xero users that have their own local Xero server or does Xero forsee the need change the current basepath in the future? All of the code examples found thus far use the default constructor. Both constructors have public scope so I'm assuming that they are both intended for developer use.

Any help in answering these questions is appreciated,

Regards,

Steve G

**Comment by jenksguo** [comment]
Hey @steve34581133, thanks for raising this here. 

1. very valid point. I should be able to add state to XeroOAuth2Token object on the next release. Perhaps allow an overloaded method for developers to pass in the original state to validate. (if you use oidc library like this example my colleague Matt M made [here](https://github.com/XeroAPI/xero-netstandard-oauth2-samples), it is handled automatically by the library) 

2. If you are referring to `public AccountingApi(String basePath)`, then this is for people who would like to not point the API calls to https://api.xero.com/api.xro/2.0 but rather going through a proxy address (e.g. in an very isolated network environment or behind a firewall). We use this to point my SDK to a sandbox API test endpoints so we can write our unit test cases. 

I will address 1 on the next release hopefully next week.

**Comment by jenksguo** [comment]
Hi @steve34581133, sorry for not getting back to you earlier. 

I will build an overload method something called BuildLoginUri(string state) & BuildLoginUriPkce(sting state) so it is easier to send state into the method.

**Comment by jenksguo** [comment]
Hi @steve34581133, in [v1.3.0](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.3.0), we included the methods mentioned above. 

Please let us know if this addressed the issue you raised.

**Comment by steve34581133** [comment]
Hi @jenksguo Thank you for this. I will pickup new version in the next 48 hours. I need to research how to test for XRSF(CSRF) attacks so may be a while before I can confirm issue has been addressed.

**Comment by jenksguo** [comment]
Hi @steve34581133 closing this for now. Please reopen if you find any issue with the solution.

**Comment by steve34581133** [comment]
Hi @jenksguo, I have a few follow-up questions before I make final code changes.

1. Your post dated 12/11/2020 indicated that you should be able to add a new state property to the XeroOAuthToken class. In the latest version of the API the class appears to be unchanged from the previous version Can I assume that the other changes you made removes the need for a new state property in the XeroOAuthToken class?
2. The grant type of our Xero App is **Auth code Web App**. Should I be using one of the overloaded BuildLoginUri methods and NOT one of the BuildLoginUriPkce methods?
3. Assuming a positive answer to question 2., two of the BuildLoginUri methods take string parameters. The first takes a parameter of **state** and the second takes parameters of **state** and **scope**. Previously I have populated a XeroConfiguration object with **state** and **scope** before passing it to the XeroClient constructor. Given that the **scope** property of the XeroConfiguration object has already been populated by the time the BuildLoginUri method of my XeroClient object is called, how should I be using the **scope** parameter of the BuildLoginUri method? 
4. After I have called the RefreshAccessTokenAsync method of my XeroClient object, should I then be calling the BuildLoginUri method to force verification of the value of state (in case there is an XRSF attack) and update the **scope** prior to further API calls (assuming a scenario where **scope** may have been restricted initially whilst acquiring new access and refresh tokens?
5. From your previous posts I am correct in assuming that an exception will be thrown automatically if there is a mismatch of states, caused by an XRSF attack? Can you point me to the exception that is thrown please?
6. The BuildLoginUri method returns a string which I assume to be a uri. Should I be using this uri when making subsequent API calls?
My apologies if I have misunderstood the intention behind the BuildLoginUri method or how these changes work. Code extract follows.
```
// Create a new Xero OAuth2 configuration to hold OAuth 2.0 credentials.
XeroConfiguration objXeroConfig = new XeroConfiguration
{
    ClientId = txtClientId.Text,
    ClientSecret = txtClientSecret.Text,
    CallbackUri = new Uri(m_sRedirectUri),
    Scope = m_sScope,
    State = m_sState
};
// Create a Xero client to get a Xero OAuth 2.0 Token using the previously retrieved refresh token (used later in API calls).
m_objXeroClient = new XeroClient(objXeroConfig);
m_objXeroOAuth2Token = new XeroOAuth2Token()
{
    RefreshToken = txtOldRefreshToken.Text
};
m_objXeroOAuth2Token = (XeroOAuth2Token)await m_objXeroClient.RefreshAccessTokenAsync(m_objXeroOAuth2Token);
<<---------------------------- INSERT BuildLoginUri METHOD HERE? ---------------------------->>
// Populate token fields for user to see.
txtNewAccessToken.Text = m_objXeroOAuth2Token.AccessToken;
txtNewRefreshToken.Text = m_objXeroOAuth2Token.RefreshToken;
// Get a list of tenants.
List<Tenant> lstTenants = await m_objXeroClient.GetConnectionsAsync(m_objXeroOAuth2Token);
foreach (Tenant tenant in lstTenants)
{
    lvwTenants.Items.Add(new ListViewItem(new string[] { tenant.TenantName, tenant.TenantId.ToString(), tenant.TenantType }));
}
// Now get a list of account contacts.
string sTenantId = m_objXeroOAuth2Token.Tenants[0].TenantId.ToString();
AccountingApi objAccountingApi = new AccountingApi();
var response = await objAccountingApi.GetContactsAsync(txtNewAccessToken.Text, sTenantId);
List<Contact> lstContacts = (List<Contact>)response._Contacts;
var response2 = await objAccountingApi.GetAccountsAsync(txtNewAccessToken.Text, sTenantId);
List<Account> lstAccounts = (List<Account>)response2._Accounts;
```

**Comment by steve34581133** [comment]
Hi @Talath, 
Have you been able to make any successful calls using the OAuth2.0 API yet? If you would find it useful I can post my Powershell script here together with the source code and instructions for the tool I use to get an initial refresh token (the tool is written in C#).
