### ISSUE TITLE
Contacts Nested Params

### ISSUE THREAD

**Issue by andre9405** [XeroAPI/Xero-NetStandard#250]
I am creating an app that takes user input to create a new contact to the connected org's xero contacts. I have managed to make it so that when you click on create contact it displays my contact form

I have used some of the code and added some. The API call posts the data of the primary person and the contact person . however the rest of the details such as address and phone is not being saved, would you be able to help with this please . I'm very new to developing . i am using the c# sdk

api history 
[code for contactsinfo controller.txt](https://github.com/XeroAPI/Xero-NetStandard/files/5508942/code.for.contactsinfo.controller.txt)

![mD1HRfdE](https://user-images.githubusercontent.com/67734867/98516164-d03ad780-2274-11eb-89a3-87ffef8d2de2.png)

**Comment by jenksguo** [comment]
Hi @andre9405, looks like the issue is that AddressType and PhoneType are missing. Our API will take the Contact object, but ignored the address and phone object. 

This call worked for me: 
```json
      "Addresses": [
        {
          "AddressType": "STREET",
          "AddressLine1": "32 blink street ",
          "City": "JHB",
          "PostalCode": "1739"
        }
      ],
      "Phones": [
        {
          "PhoneType": "DEFAULT",
          "PhoneNumber": "0631821153",
          "PhoneCountryCode": "27"
        }
      ]
```

In your code you will need to add the following at appropriate lines to select the correct type enums: 

```csharp
      contact.AddressType =  Address.AddressTypeEnum.STREET;

      phone.PhoneType = Phone.PhoneTypeEnum.DEFAULT;
```

I hope this can get you unstuck. :-)

**Comment by andre9405** [comment]
This helped me so much . I thank you kind sir
