### ISSUE TITLE
ETA for bank feeds

### ISSUE THREAD

**Issue by Nothing-Works** [XeroAPI/Xero-NetStandard#251]
Hi I know it's coming, just wondering do you have the ETA for it?

days? weeks? months?

Many thanks in advance.

**Comment by jenksguo** [comment]
Hi @Nothing-Works, thanks for expressing your demand on this endpoint. 

This will help up prioritise this piece of work and release it sooner rather than later. 

Once we have put this on our planning, I will let you know the ETA.

**Comment by jenksguo** [comment]
Hi @Nothing-Works, BankFeed API is now delivered. :-) 

Please check out any thing above v3.11.1

https://www.nuget.org/packages/Xero.NetStandard.OAuth2/

**Comment by Nothing-Works** [comment]
@jenksguo thank you very much.
