### ISSUE TITLE
NZ TaxSettings Model incorrect for PeriodUnits

### ISSUE THREAD

**Issue by mcopley-anzdrive** [XeroAPI/Xero-NetStandard#255]
**SDK you're using (please complete the following information):**
Version 3.7.2

**Describe the bug**
In this model file;

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollNz/TaxSettings.cs

The property PeriodUnits is an int? but should be a decimal?

**To Reproduce**
Try to deserialize a response from the Xero Api that has a value of 0.5 for the PeriodUnits.

**Expected behavior**
Should be able to deserialize responses from the Xero Api.

**Comment by JRising-Xero** [comment]
Hi @mcopley-anzdrive ,
We have changed periodUnits to decimal.

Please check out the new SDK version 3.9.0:
https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.9.0

You can view the change here:
https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollNz/TaxSettings.cs#L72
