### ISSUE TITLE
NZ PayRun Model incorrect for CalendarType

### ISSUE THREAD

**Issue by mcopley-anzdrive** [XeroAPI/Xero-NetStandard#256]
**SDK you're using (please complete the following information):**
Version 3.7.2

**Describe the bug**
In this model file;

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollNz/PayRun.cs

The values of the CalendarTypeEnum are incorrect. We are getting back a response from the Api where the value is 'TwiceMonthly'.

**To Reproduce**
Try to deserialize a response from the Xero Api that has a value of 'TwiceMonthly' for the CalendarType.

**Expected behavior**
Should be able to deserialize responses from the Xero Api.

**Comment by jenksguo** [comment]
@mcopley-anzdrive Hey there, thanks for reporting the missing enum, we will update Xero OpenAPI spec and regenerate and fix this on the next release. 

Hey @SidneyAllen, please expect an PR on Payrun Clendar Type  enums.

**Comment by jamie-hoffmann-xero** [comment]
Hi @mcopley-anzdrive , this bug has been addressed in version 3.8.0 of the .NET SDK.
https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.8.0
https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollNz/PayRun.cs#L140
