### ISSUE TITLE
oAuth2 in .Net framework 4.5.2

### ISSUE THREAD

**Issue by davarpanah** [XeroAPI/Xero-NetStandard#260]
.Net framework target version of our web application is 4.5.2, while for migration to oAuth2, it is required to be Core 3.1.
It is not possible for us to upgrade the framework. Any suggestions please?
I've found a app sample for version 4.6.1. Is it useful?
Thanks in advance.
Hashem

**Comment by mahesh139** [comment]
No, Xero-NetStandard does not force you to use .Net Core 3.1. you can use it with .NetFramework
https://github.com/XeroAPI/xero-netstandard-oauth2-starter-app-dotnet-framework

**Comment by jenksguo** [comment]
@davarpanah Unfortunately, the SDK only works with 4.6.1 and above.

**Comment by jenksguo** [comment]
Hi @davarpanah @mahesh139, I am closing this since it has been some time. :-)
