### ISSUE TITLE
The Xero.NetStandard.OAuth2.Api.PayrollNzApi.GetEmployeeSalaryAndWagesAsync retuns null response

### ISSUE THREAD

**Issue by azhilt** [XeroAPI/Xero-NetStandard#264]
**SDK you're using (please complete the following information):**
 - Version 3.9.0

PayrollNzApi.GetEmployeeSalaryAndWagesAsync returns null response because daysPerWeek is float in Xero response, but int in Xero.NetStandard: Input string '7.0000' is not a valid integer. Path 'salaryAndWages[0].daysPerWeek',

{"salaryAndWagesID":"11111111-1111-1111-1111-111111111111","earningsRateID":"11111111-1111-1111-1111-1111111111111","numberOfUnitsPerWeek":35.0000,"ratePerUnit":2.000000,"numberOfUnitsPerDay":5.0000,"daysPerWeek":7.0000,"effectiveFrom":"2020-10-04T00:00:00","annualSalary":null,"status":"Active","paymentType":"Hourly"}

**Comment by jenksguo** [comment]
Hi @azhilt, acknowledged. We should be able to release a fix this week.

**Comment by azhilt** [comment]
Thank you

**Comment by jamie-hoffmann-xero** [comment]
Hi @azhilt, we have released a fix for this issue in v3.12.0.

The `DaysPerWeek` property has been changed to a `decimal?` and can now be deserialised from your example payload.

The affected line is viewable here: https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollNz/SalaryAndWage.cs#L136

Thanks for reporting, and feel free to reopen if you need anything further.
