### ISSUE TITLE
Xero.NetStandard.OAuth2.Api.AccountingApi.GetReportBASorGSTAsync returning null response

### ISSUE THREAD

**Issue by davidmcgill-bf** [XeroAPI/Xero-NetStandard#265]
When using GetReportBASorGSTAsync I'm getting a null response. Checking the response in fiddler shows that the data is coming through. 

If I use GetReportBASorGSTAsyncWithHttpInfo, I can see that it returns the following error.
_Error converting value "ABN" to type 'System.Nullable`1[System.Guid]'. Path 'Reports[0].Fields[0].FieldID', line 27, position 26._

It appears the ReportFields.FieldID is expecting a Guid but is coming through as text string. The report fields being received and that are expected are similar to below.
```
"Fields": [
  {
    "FieldID": "ABN",
    "Description": "ABN",
    "Value": "00000000000"
  }
]
```
This is using Version 3.10.0

**Comment by jenksguo** [comment]
Hi @davidmcgill-bf, thanks for raising the issue. We will look into addressing this as soon as possible.

**Comment by jenksguo** [comment]
Hi @davidelsey thanks for reporting the issue and your PR. We have incorporated your solution into the SDK. 

[v3.11.1](https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.11.1) has this issue addressed.
