### ISSUE TITLE
Invoice date and due date are set to previous date

### ISSUE THREAD

**Issue by HarishDevadiga** [XeroAPI/Xero-NetStandard#269]
While creating invoices the date and due date object take in DateTime object and cannot be converted to string. If we set date using DateTime.Today, the date in invoices are set to previous date.

**Comment by HarishDevadiga** [comment]
While creating invoices the date and due date object take in DateTime object and cannot be converted to string. If we set date using DateTime.Today, the date in invoices are set to previous date.

**Comment by pauledrupt** [comment]
Same for manual journal entries. Date is show as one day earlier then what was entered.

**Comment by jenksguo** [comment]
@HarishDevadiga possibly due to local vs UTC time setting on the DateTime object. 

We are investigating and will get back to you soon.

**Comment by GraceYBR** [comment]
Hey @pauledrupt @HarishDevadiga could you please let us know which timezone you are based in, what region of the Xero product you are using and whether you are specifying your time in local or UTC time.

**Comment by HarishDevadiga** [comment]
We are based in New zealand and use Accounting api to generate invoices. We specify local time.

**Comment by Albert-Xero** [comment]
Hi @HarishDevadiga and @pauledrupt,
If you are setting the Date of the invoice using DateTime.Today, you will need to set the DateTimeKind property on the DateTime object.

For example, to create a date and due date for an invoice created today and due 30 days from now:

```
var invoiceDate = DateTime.Today;
var invoiceDueDate = DateTime.Today.AddDays(30);
```

And then when setting the dates on the Invoice:

```
var invoice = new Invoice();
invoice.Date = DateTime.SpecifyKind(invoiceDate, DateTimeKind.Utc);
invoice.DueDate = DateTime.SpecifyKind(invoiceDate, DateTimeKind.Utc);
```

I will now close this issue, please feel free to reopen if you are still having problems.
