### ISSUE TITLE
Submitted contact delivery address is not recorded

### ISSUE THREAD

**Issue by Matt-Roberts-mondaq** [XeroAPI/Xero-NetStandard#270]
- Version 3.10.0

**Describe the bug**
When updating or adding a contact to Xero through the API, STREET type addresses are recorded, but the same details for DELIVERY type addresses are not recorded.

**To Reproduce**
1. Create a Xero.NetStandard.OAuth2.Model.Accounting.Contact object
2. Attach an address with type DELIVERY, and an identical address with type of STREET, as well as any other details you need on the contact.
3. Submit the contact as part of a list using xeroAccountingApi.UpdateOrCreateContactsAsync()

**Expected behavior**
The returned Xero contact object should have 2 identical addresses save for the type - one of type STREET and one of type DELIVERY. Actual behaviour is that the STREET address is saved but the DELIVERY address appears to be discarded - the object returned from the API call has no delivery address and the same in the Xero admin zone.

**Screenshots**
The history on the MyApps developer area shows successful submission of both addresses:
![image](https://user-images.githubusercontent.com/75306025/100733437-155eaf00-33c6-11eb-9287-840b0e3487f2.png)

But the object returned had no delivery address:
![image](https://user-images.githubusercontent.com/75306025/100733392-05df6600-33c6-11eb-864e-cd86a994a6d0.png)

And the contact in the Xero admin area only has one address on it:
![image](https://user-images.githubusercontent.com/75306025/100733470-260f2500-33c6-11eb-9a0a-f643a2f6202e.png)

**Comment by jamie-hoffmann-xero** [comment]
Hi @Matt-Roberts-mondaq, unfortunately the DELIVERY address type is not supported for contacts and will only be returned from the GET Organisation endpoint. Please refer to this documentation page: https://developer.xero.com/documentation/api/types#Addresses

We will provide feedback to the API team regarding the lack of error message in this case.

Thanks for reporting this issue. Please feel free to re-open this issue if you encounter any further problems.

**Comment by Matt-Roberts-mondaq** [comment]
Thank you for your reply.

As far as I can tell, the delivery address is what's used to display a contact's address on invoices. If we are sending our contacts and invoices from our system to Xero using the API, how do you suggest we ensure all our invoices produced from Xero have addresses on them?
