### ISSUE TITLE
CISDeduction is not included in CreditNote.cs

### ISSUE THREAD

**Issue by JamesGrantTradify** [XeroAPI/Xero-NetStandard#273]
**SDK you're using (please complete the following information):**
 - Version 3.7.2

**Describe the bug**
CISDeduction property is not included in CreditNote.cs

**To Reproduce**
NA

**Expected behavior**
CISDeduction property IS included in CreditNote.cs

**Screenshots**
https://github.com/XeroAPI/Xero-NetStandard/blob/81206c42a024a98b20e30401b56d61fcb8854e09/Xero.NetStandard.OAuth2/Model/Accounting/CreditNote.cs

**Additional context**

**Comment by LucasRodriguez0302** [comment]
Hey team, here is the property missing in the file mentioned by James:

```
        /// <summary>
        /// CISDeduction withheld by the contractor to be paid to HMRC on behalf of subcontractor (Available for organisations under UK Construction Industry Scheme)
        /// </summary>
        /// <value>CISDeduction withheld by the contractor to be paid to HMRC on behalf of subcontractor</value>
        [DataMember(Name = "CISDeduction", EmitDefaultValue = false)]
        public decimal? CisDeduction { get; set; }
```

This is blocking our migration to OAuth2 as we have UK customers using the feature

**Comment by LucasRodriguez0302** [comment]
https://developer.xero.com/documentation/api/credit-notes
![image](https://user-images.githubusercontent.com/25647207/101304672-b0172c00-38a5-11eb-9116-2276237176ba.png)

**Comment by jenksguo** [comment]
Hi @LucasRodriguez0302 @JamesGrantTradify, we are working on this and it should be fixed over the next few days.

**Comment by LucasRodriguez0302** [comment]
Awesome @jenksguo, thanks for the quick turnaround

**Comment by JamesGrantTradify** [comment]
@jenksguo thank you :)

**Comment by JRising-Xero** [comment]
Hi @JamesGrantTradify and @LucasRodriguez0302
Thanks for reporting this issue. We have now added the CISDeduction attribute to CreditNote.cs

You can view the change [here](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/Accounting/CreditNote.cs#L176).

[v3.11.2](https://www.nuget.org/packages/Xero.NetStandard.OAuth2/3.11.2) has this issue addressed.
Feel free to reopen if you wish to discuss further.

**Comment by JamesGrantTradify** [comment]
@JRising-Xero Awesome . Thank you :)
