### ISSUE TITLE
OAuth2 State not returned in Callback

### ISSUE THREAD

**Issue by igobl** [XeroAPI/Xero-NetStandard#283]
Xero.NetStandard.OAuth2 v3.11.2
Xero.NetStandard.OAuth2Client v1.2.2

I am trying to follow along documentation to implement OAuth2. I have this working however I am trying to validate the state parameter that is passed as part of XeroConfiguration.

In the documentation it says that the callback method will have a code and state parameter.
````cs 
public async Task<ActionResult> Callback(string code, string state)
````

However in the newest versions of these libraries the parameters that are actually expected are
````cs
public async Task<ActionResult> Callback(string code, string scope, string session_state)
````

How do I validate that the state I set when calling BuildLoginUri, in my callback method. I have checked the request and I cannot see it being sent back. I am unable to find what I am doing wrong from the documentation as I believe it may be out of date with the latest versions. Below is some pseudocode from what I am doing. Any further info would be greatly appreciated.

````cs
 public async Task<IHttpActionResult> Auth()
 {     
     var config = new XeroConfiguration
     {
          ClientId = ,
          ClientSecret = ,
          CallbackUri = new Uri(),
          Scope = , 
          State = "Whatever_my_state_is"
      };
      
      this.client = new XeroClient(config, this.httpClientFactory.Client)
      string url = this.client.BuildLoginUri();
      return Redirect(url);
}

public async Task<IHttpActionResult> Callback(string code, string scope, string session_state)
{
    // Do a check here that the state set in Auth method matches what is sent back
}
````

**Comment by jenksguo** [comment]
Hey @igobl thanks for reporting the issues. 

I didn't managed to replicate the issue as either adding state into configuration object or to the appsettings.json returned states. 

We have made an improvements in the 1.3.0 (released just now) to allow  BuildRedirecUri(string state) so the state can be explicitly specified. 

Would you like to upgrade and try that to see if it work for you?

**Comment by igobl** [comment]
@jenksguo sure I will upgrade and try to replicate again today. Just to confirm, where should I expect the state the be returned in the Callback method?

**Comment by igobl** [comment]
@jenksguo have just had a look at the latest changes made for 1.3.0 and as you have said above, the existing code should be working for me even without upgrading to latest version (also fyi the new method signatures have not been included in IXeroClient for anyone that might be using it).

If it is working for you then I believe there must be something wrong in my setup. I think the likely cause could be the callback method that I was prompted to use. I was following along with the documentation and tried implementing:
````cs
public async Task<ActionResult> Callback(string code, string state)
````
However when I did that, there were errors while being redirected saying that I actually needed the below method instead.
`````cs
public async Task<ActionResult> Callback(string code, string scope, string session_state)
````
Would appreciate if you could confirm if this is expected, and if so where in the second method signature should we expect to receive the state? Thanks

**Comment by jenksguo** [comment]
@igobl, yes, you should be expecting the state to be in the callback, when Xero returns the authorisation code, it also returns the state you sent over in the url param, so you should capture it there. 

![image](https://user-images.githubusercontent.com/41350731/102280301-fdb82680-3f80-11eb-8571-89f1a90331bb.png)

I would recommend capturing the actual callback url from Xero via a breakpoint in the code or capturing via a browser to see if what the callback url looked like. 

Below is the callback function that worked for us: 

![image](https://user-images.githubusercontent.com/41350731/102280984-386e8e80-3f82-11eb-8964-ddebc9abd459.png)

I hope it helps with your debugging.

**Comment by igobl** [comment]
Ok but what I am saying is that Xero is not redirecting to a method with (string code, string state) as the parameters. When I have that method present I get the below error Xero is redirecting back to the callback method. Xero is trying to redirect to a method with (string code, string scope, string session_state) as the parameters. So there is no state.

![image](https://user-images.githubusercontent.com/67263637/102329351-36a3cb80-3f80-11eb-9ae7-76f454f3ffd8.png)

**Comment by jenksguo** [comment]
Hi @igobl, sorry we tested a few more time and could not generate the same callback you have presented here. 

If the state is being passed into correctly, Xero login usually will return it faithfully. I would recommend checking to see wether the redirect_uri in the Auth method to see if state is indeeded sent over to Xero.

**Comment by GraceYBR** [comment]
Hey @igobl, we're closing this as we've not heard back from you, hopefully you were able to resolve the problem you encountered. Please reopen if necessary.

**Comment by kiennk1995** [comment]
I also have a similar problem, I don't know why I Xero is not redirecting to a method with (string code, string state) as the parameters. I get session_state instead of state too ?

![image](https://user-images.githubusercontent.com/20517889/229268297-9c3a06d6-1568-47a9-9c14-19ba37a71b65.png)

![image](https://user-images.githubusercontent.com/20517889/229268196-64271d6b-05be-4c6e-8b60-0d1cff94e6de.png)

**Comment by maurodias** [comment]
same here and using ruby sdk
