### ISSUE TITLE
GetBankTransactionsAsync - never returns LineItems

### ISSUE THREAD

**Issue by KenYarborough** [XeroAPI/Xero-NetStandard#287]
Note that this correctly returns lineitems
* GetBankTransactionAsync

But that these don't (JSON segment is always "LineItems": [],")
* GetBankTransaction**s**Async
* GetBankTransaction**s**AsyncWithHttpInfo

**SDK you're using (please complete the following information):**

Xero.NetStandard.OAuth2
v4.0.30319

**Describe the bug**

GetBankTransactionsAsync - never returns LineItems

I'm using GetBankTransactionsAsync

Xero.NetStandard.OAuth2.Model.Accounting

I get all the information you'd expect,
* BankAccount.name
* BankAccount.id
* BankTransactionID
* Contact.name
...

but this is always empty
List &lt; LineItem &gt; LineItems

For example, I have a transaction that has two line items, but the LineItems count is zero

BankTransactionID: c910d102-6cff-4f95-b534-d8a8a8a28805
Contact Test2

**Expected behavior**

Return Tranasaction line items

               BankTransactions bankTransactions = await accountingApi.GetBankTransactionsAsync(accessToken, xeroTenantId);

                foreach (BankTransaction bankTransaction in bankTransactions._BankTransactions)
                {
                    Console.WriteLine(bankTransaction.LineItems.Count); // always zero
                }

**Screenshots**

**Additional context**

**Comment by KenYarborough** [comment]
See this section of code
XeroNetStandardApp\Controllers\BankTransactionsInfoController.cs

...
<code>    // GET: /BankTransactionsInfo/
    public async Task<ActionResult> Index()
    {
      var xeroToken = TokenUtilities.GetStoredToken();
      var utcTimeNow = DateTime.UtcNow;

      //if (utcTimeNow > xeroToken.ExpiresAtUtc)
      //{
        var client = new XeroClient(XeroConfig.Value, httpClientFactory);
        xeroToken = (XeroOAuth2Token)await client.RefreshAccessTokenAsync(xeroToken);
        TokenUtilities.StoreToken(xeroToken);
      //}

      string accessToken = xeroToken.AccessToken;
      string xeroTenantId = xeroToken.Tenants[0].TenantId.ToString();

      var AccountingApi = new AccountingApi();
      var response = await AccountingApi.GetBankTransactionsAsync(accessToken, xeroTenantId);
      var bankTransactions = response._BankTransactions;

      return View(bankTransactions);
    }
</code>
...
response._BankTransactions[0].LineItems.Count 
always zero

**Comment by jamie-hoffmann-xero** [comment]
Hi @KenYarborough, thanks for reporting this.
Not returning line items in the aggregate case is the expected behaviour defined by the API, though unfortunately the documentation [here](https://developer.xero.com/documentation/api/banktransactions#GET) is somewhat vague on this.

In order to get the LineItems, please use the `GetBankTransactionAsync` method. Feel free to reopen this issue if you need anything further.

**Comment by KenYarborough** [comment]
Please don't close this as a "feature" of banktransactions, as it contradicts the documentation and will mean thousand, perhaps millions of extra round trip if I have to individually get a transaction to get line items.

Note there's no vagueness in documentation:

From Xero's own supplied documentation:

https://developer.xero.com/documentation/api/banktransactions#GET

GET https://api.xero.com/api.xro/2.0/BankTransactions/d20b6c54-7f5d-4ce6-ab83-55f609719126
{
"BankTransactions": [{
"Contact": {
"ContactID": "6d42f03b-181f-43e3-93fb-2025c012de92",
"Name": "Wilson Periodicals"
},
"DateString": "2014-05-26T00:00:00",
"Date": "/Date(1401062400000+0000)/",
"Status": "AUTHORISED",
"LineAmountTypes": "Inclusive",
"LineItems": [{
"Description": "Monthly account fee",
"UnitAmount": "49.90",
"TaxType": "NONE",
"TaxAmount": "0.00",
"LineAmount": "49.90",
"AccountCode": "404",
"Quantity": "1.0000",
"LineItemID": "52208ff9-528a-4985-a9ad-b2b1d4210e38"
}],

**Comment by SidneyAllen** [comment]
Hi @KenYarborough - if you pass in the page parameter into the get BankTransactions method you will get 100 records at a time that include the line item details

e.g. page=1 will return the first 100.  So, you can retrieve 1,000 records in 10 API calls by incrementing the page number.

**Comment by KenYarborough** [comment]
Thank you

**Comment by KenYarborough** [comment]
Verified that Sidney Maestre is correct.

Set up a loop to get transactions, by incrementing page

                DateTime? ifModifiedSince = null;
                string where = null;
                string order = null;
                int? page = 1;
                int? unitdp = null;

                int bankTransactions_BankTransactions_Count = int.MaxValue;

                //---------------------------------------------------------------------------
                //Page is needed to get line items (no page means no line items)
                //page 1 = 100 transactions max
                //---------------------------------------------------------------------------

                while (bankTransactions_BankTransactions_Count != 0)
                {

                    BankTransactions bankTransactions = await accountingApi.GetBankTransactionsAsync(accessToken, xeroTenantId, ifModifiedSince, where, order, page, unitdp);

                    bankTransactions_BankTransactions_Count = bankTransactions._BankTransactions.Count;

                    if (bankTransactions_BankTransactions_Count != 0)
                        page++;
                }
