### ISSUE TITLE
NZ payroll API GetTimesheetsAsync retuning all the timesheets and ignoring the EmployeeID parameter

### ISSUE THREAD

**Issue by shereenfathima** [XeroAPI/Xero-NetStandard#288]
SDK  Version 3.12.0

Bug :
The below method retuning all the timesheets and not filtering the Employee.
payrollApi.GetTimesheetsAsync(accessToken, tenantID, curPage, employeeID)

Looks like it's ignoring the parameter EmployeeID

**Comment by jenksguo** [comment]
Hi @shereenfathima, thanks for reporting this issue. This bug had been confirmed. We will work on a solution and fix in the next release.

**Comment by GraceYBR** [comment]
Hey @shereenfathima, we had another look at the issue you raised and couldn't replicate it. 

It would be great for you to double check how you are providing the EmployeeID. Here's a snippet of how we did it:

```
var nzEmployeeID = Guid.Parse("f222b157-6a13-47df-8099-ecceaa99c727");
var employeeResponse = await PayrollNZApi.GetTimesheetsAsync(accessToken, xeroTenantId, 1, nzEmployeeID);
```

Our API call looked like this:
```
http://api-oauth2.xero.com/payroll.xro/2.0/Timesheets?employeeId=f222b157-6a13-47df-8099-ecceaa99c727&page=1
4:55
```
Note that the guid in the nzEmployeeID variable exactly matches the employeeId in the API call. 

If you want to check your API call history, you can view the History on your Xero OAuth 2.0 app. To do this go to developer.xero.com and login, navigate to the app you have connected your test org to and then click on the history tab. If you click on an API call you'll see the request path you used. 

You might also want to play around with the [API Explorer](http://api-explorer.xero.com/) too. 

I will close this issue but if you continue to have problems please reopen it.

**Comment by shereenfathima** [comment]
@GraceYBR  this is working now in updated SDK
