### ISSUE TITLE
GetBankTransactionsAsync - never returns LineItems

### ISSUE THREAD

**Issue by KenYarborough** [XeroAPI/Xero-NetStandard#290]
Please don't close this as a "feature" of <b>banktransactions</b>, as it contradicts the documentation and will mean thousand, perhaps millions of extra round trip if I have to individually get a transaction to get line items.

Note there's no vagueness in documentation:

From Xero's own supplied documentation:

https://developer.xero.com/documentation/api/<b>banktransactions</b>#GET

GET https://api.xero.com/api.xro/2.0/<b>BankTransactions</b>/d20b6c54-7f5d-4ce6-ab83-55f609719126
{
  "BankTransactions": [{
    "Contact": {
      "ContactID": "6d42f03b-181f-43e3-93fb-2025c012de92",
      "Name": "Wilson Periodicals"
    },
    "DateString": "2014-05-26T00:00:00",
    "Date": "\/Date(1401062400000+0000)\/",
    "Status": "AUTHORISED",
    "LineAmountTypes": "Inclusive",
    <b>"LineItems": [{
      "Description": "Monthly account fee",
      "UnitAmount": "49.90",
      "TaxType": "NONE",
      "TaxAmount": "0.00",
      "LineAmount": "49.90",
      "AccountCode": "404",
      "Quantity": "1.0000",
      "LineItemID": "52208ff9-528a-4985-a9ad-b2b1d4210e38"
    }],</b>

**Comment by KenYarborough** [comment]
Verified that Sidney Maestre is correct.

Set up a loop to get transactions, by incrementing page

                DateTime? ifModifiedSince = null;
                string where = null;
                string order = null;
                int? page = 1;
                int? unitdp = null;

                int bankTransactions_BankTransactions_Count = int.MaxValue;

                //---------------------------------------------------------------------------
                //Page is needed to get line items (no page means no line items)
                //page 1 = 100 transactions max
                //---------------------------------------------------------------------------

                while (bankTransactions_BankTransactions_Count != 0)
                {

                    BankTransactions bankTransactions = await accountingApi.GetBankTransactionsAsync(accessToken, xeroTenantId, ifModifiedSince, where, order, page, unitdp);

                    bankTransactions_BankTransactions_Count = bankTransactions._BankTransactions.Count;

                    if (bankTransactions_BankTransactions_Count != 0)
                        page++;
                }

**Comment by jenksguo** [comment]
Hi @KenYarborough, thanks for raising the question. 

Most of our "GET all" apis are designed to return batch results so line details are hidden, if you use paging, it will return more details. If you get by id, it will return full details. 

Your question was answered in the [previous issue you raised](https://github.com/XeroAPI/Xero-NetStandard/issues/287). The issue was with our API documentation not with the SDK project itself, so I will close this issue for now. 

Please feel free to open a new issue if there are other bugs or questions related to the SDK. :-)
