### ISSUE TITLE
PayrollAuApi.GetPayItemsAsync returns null response if there is an earnings rate of Lump Sum E

### ISSUE THREAD

**Issue by jameslow261** [XeroAPI/Xero-NetStandard#291]
**SDK you're using (please complete the following information):**
 - Version 3.12.1

**Describe the bug**
If there is an earnings rate of 'Lump Sum E' in the Xero organisation, the PayrollAuApi.GetPayItemsAsync method returns a null response.

**Additional context**
The reason is because the SDK tries to map to this enum but the type does not exist.
![image](https://user-images.githubusercontent.com/28224287/103052042-3fce1180-45ec-11eb-9879-98d21cb4fcb3.png)

**Comment by JRising-Xero** [comment]
Hi @jameslow261 thanks for letting us know of the missing enum value. LUMPSUME has been added with the latest release (3.13.0).
You can view the change [here](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2/Model/PayrollAu/EarningsType.cs#L93)
