### ISSUE TITLE
Tenant.id and Tenant.TenantID

### ISSUE THREAD

**Issue by TOuhrouche** [XeroAPI/Xero-NetStandard#292]
**SDK you're using (please complete the following information):**
 - Version e.g. 3.12.1

**Describe the bug**
Tenant class has two identifiers, `id` and `TenantID`.
`XeroClient.DeleteConnectionAsync` uses `Tenant.id` as the identifier of the tenant. Ideally, it should use the TenantID instead.

**Comment by jenksguo** [comment]
Hi @TOuhrouche, happy new year! 

When you are disconnecting, you should use Tenant.ID which stands for connection ID. 

When you are firing API calls, you will need the tenantID. 

One is we used for identify the connection (e.g. re-auth action from the user will get you a new Tenant.ID but will return the same TanantID). :-) 

Let me know if you have more questions.

**Comment by TOuhrouche** [comment]
Thanks a lot for the follow up and the detailed explanation. 
As this property indicates a connection Id, wouldn’t it be better to name it ConnectionId or Connection.Id? 

Regards,
Tahar

**Comment by jenksguo** [comment]
Hi @TOuhrouche good point, I will send this feedback to our API product team for consideration. :-)
