### ISSUE TITLE
API status is not changing and it does not callback when GetInvoiceAsPdfAsync function is called

### ISSUE THREAD

**Issue by davarpanah** [XeroAPI/Xero-NetStandard#294]
Hi, 
I have created an invoive successfully and now I am going to email a copy of the invoice.  It is a part of our code for migration to oAuth2 version. However when I call GetInvoiceAsPdfAsync function with three non null arguments, the "Processing your payment..." message is shown and is not finished.
Thanks,
Hashem

var AccountingApi = new AccountingApi();
var invPdf = await AccountingApi.GetInvoiceAsPdfAsync(_xeroToken.AccessToken, _tenantID.TenantId.ToString(), Invoice.InvoiceID.GetValueOrDefault()).ConfigureAwait(false);

**Comment by jenksguo** [comment]
Hey @davarpanah, happy new year. 

Would you be able to share the complete response message you get from the GetInvoiceAsPdfAsync method? It should be returned a System.IO.Steam response rather than a message. 

I find the response hard to explain as it is not related to the pdf function.

**Comment by GraceYBR** [comment]
Hey @davarpanah, we're going to close this issue as we've not heard back from you. I hope you were able to resolve the problem you were encountering. Please reopen if you need to.
