### ISSUE TITLE
Documentation to migrate from XeroAPI/Xero-Net to XeroAPI/Xero-Net

### ISSUE THREAD

**Issue by InTouch-Developer** [XeroAPI/Xero-NetStandard#295]
Hello Xero Development Team, 

From end of March 2021, OAuth 1 is being depreciated by Xero.  

This means that anybody using the SDK [Xero-Net](https://developer.xero.com/documentation/oauth2/migrate), must change to using this repository of Xero-NetStandard, and change quickly. 

This new repository has a completely different API to Xero-Net; different classes, different naming conventions and utilises async & await extensively. 

This means a complete rewrite of our existing integration - and presumably exactly same for everyone else using Xero-Net - which must a be huge customer base. 

Moving forward,

1. Is this correct?
2. Is there any documentation that details how to migrate from Xero-Net to Xero-NetStandard?
3. Is there any leeway in the March 2021 deadline?

Looking forward to a response.

**Comment by wobinb** [comment]
1. Yes that is correct. We launched the OAuth 2.0 system in December 2019 and announced the deadlines for migrating at the same time. We're now towards the end of the migration process. At API level the same XML and JSON payloads are used, only the authentication is different. However as you've noted we've used the migration as an opportunity to re-launch the SDKs. These are now auto-generated based on our Open API specification and will be easier to maintain. 
2. The migration process will vary considerably depending on your existing implementation, as such we don't have a guide as such. We would suggest examining our sample apps to see how they work.
3. Existing Public and Partner apps will cease working 31/03/2021. For private apps we are currently finalising details of a premium form of custom connection. Our intention is to extend the deadline for Private Apps to provide extra time to implement the new form of connection.

**Comment by wobinb** [comment]
Some generic advice on migration can be found here: https://developer.xero.com/documentation/oauth2/migrate 

Please note that the migration endpoint can only be used by Partner Apps, however the background regarding the tokens applies to all forms of app.

**Comment by marvc1** [comment]
> as you've noted we've used the migration as an opportunity to re-launch the SDKs.

All the more challenging, as the new SDK hasn't been working on the .NET Framework until relatively recently 🤦‍♂️ 

We've got both Public & Partner apps set up. 

So to confirm, there is no shortcuts, or SDK migration docs - a rewrite of every usage of the Xero-Net SDK interaction is required, and that needs to be worked out from the examples and generic docs. 🙀

**Comment by InTouch-Developer** [comment]
> as you've noted we've used the migration as an opportunity to re-launch the SDKs.

All the more challenging, as the new SDK hasn't been working on the .NET Framework until relatively recently 🤦‍♂️ 

We've got both Public & Partner apps set up. 

So to confirm, there is no shortcuts, or SDK migration docs - a rewrite of every usage of the Xero-Net SDK interaction is required, and that needs to be worked on from the examples and generic docs. 🙀
