### ISSUE TITLE
GetInvoicesAsyncWithHttpInfo timing out

### ISSUE THREAD

**Issue by michaelruck138** [XeroAPI/Xero-NetStandard#296]
**SDK you're using (please complete the following information):**
 - Version 2.8.0 (latest as of 12/01/2021)

**Describe the bug**
This line within the GetInvoicesAsyncWithHttpInfo function is timing out
var response = await this.AsynchronousClient.GetAsync<Invoices>("/Invoices", requestOptions, this.Configuration);

The same line within the GetContactsAsyncWithHttpInfo function is not timing out and works fine.

**To Reproduce**
I've got the latest source
Called the GetContacts to ensure my link is open and active and all the contacts are returned, then called GetInvoices where the above line simply times out.

**Expected behavior**
Invoices should be returned.

**Comment by michaelruck138** [comment]
Just to add, I'm using windows 10 and visual studio 17

**Comment by michaelruck138** [comment]
Adding to this further, I've just installed visual studio 2019, exactly the same issue.

Just to be clear I've downloaded the latest from github, the code can connect to xero no problem, it gets a list of contacts no problem and with no modification to code...however, it will not get a list of invoices using this line

var response = await this.AsynchronousClient.GetAsync("/Invoices", requestOptions, this.Configuration);

I have been through the code and added .ConfigureAwait(false); to all the async calls but no joy at all.

**Comment by jenksguo** [comment]
Hi @michaelruck138, thanks for providing the details. 

Would you be able to let us know how long the time out is set to? On some occasions when a Xero user has many many invoices in the organisation, the API can be quite slow in replying with all details. Our API GET timeout is set to 5 minutes but many client side will timeout way before that time. 

I would suggest adding paging filter in the method to see if you still get time outs.

**Comment by AGenius** [comment]
https://github.com/AGenius/XeroAuth2API

Working on building a sync wrapper version at the moment. your welcome to use it

**Comment by michaelruck138** [comment]
thanks for that, I can see its in development and as the end of March is looming I'm trying to get a solid replacement in place before then so I'm trying to just stick to what xero provide, hence why I don't really want to go around adding ConfigureAwait to all their code because if I then pull the latest code...those mods will get lost (not that those mods work though).

If oauth1 gets turned off and I don't have a solid working replacement it'll cause a massive amount of manual work to be done.

thanks though :)

**Comment by AGenius** [comment]
The new "Premium" machine to machine method they are planning to provide will be an extra cost!

No details yet on how much but we will not pay for something that was taken away from the old version.

**Comment by jenksguo** [comment]
Hi @michaelruck138, we are unable to replicate the issue you have faced, but we would like to know if can make a simple GetInvoicesAsync without the filters? We have tried including ConfigureAwait(false) and without it.

**Comment by michaelruck138** [comment]
Hello! thanks for looking at this.

So first off I simply downloaded the source from github, ran it and it worked on contacts but not on invoices (no filters).
Then I added filters, still no luck.
Then I added ConfigureAwait in app the API calls and again the contact one worked, the invoice one didn't...with or without filters.

This is a base windows 10 machine with the latest service packs. The above was tried in visual studio 2017 and 2019.

I tried pretty much all of this before logging an issue here just to rule out user error :)

**Comment by jenksguo** [comment]
Hey @michaelruck138, do you know how many invoices this Xero organisation has?  Is it the size that causes the timeout.

**Comment by michaelruck138** [comment]
hello, that shouldn't really matter as im trying to get just 1 of them in my last example

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jenksguo** [comment]
Hey @michaelruck138, would you be able to share the request and the application client ID with me so I can dig in to the API logs to find out what happened? We are a bit lost on how to resolve this one for you at the moment.

So far it doesn't look like a problem with the SDK.

jenks.guo@xero.com

**Comment by michaelruck138** [comment]
Hello,

I’m afraid exposing the client ID on github isn’t something I’d want to be doing 😊

If you can setup a new xero account and let me have the client ID I can run the solution against that to see if I get the same problem?

Kind regards,

Mike

**Comment by jenksguo** [comment]
Hey @michaelruck138, do you mind if I close this issue and assist you via my email directly? api@xero.com. 😀

**Comment by jenksguo** [comment]
Hi @michaelruck138, I hope you were able to resolve this by now. I tried to find your email on our support queue but could not find it. 

Let us know if you still face the issues and we can resolve this via direct email.
