### ISSUE TITLE
Contact WebSite is Readonly

### ISSUE THREAD

**Issue by AGenius** [XeroAPI/Xero-NetStandard#297]
**SDK you're using (please complete the following information):**
 - Version 3.12.1

**Describe the bug**
When creating a contact either stand alone or for a new invoice. the WebSite property is Read Only. How are you supposed to add this value?

**Comment by jenksguo** [comment]
Hi @AGenius, thanks for raising questions here. 

I am afraid it is an API issue not an SDK issue. Xero API contacts endpoint does not yet offer the ability to create websites, it is read only for now. User must enter this field manually in Xero UI.

**Comment by jamie-hoffmann-xero** [comment]
Hey @AGenius, going to close this one. Thanks for raising the issue and feel free to reopen if you need further help on this topic.
