### ISSUE TITLE
Asset API appears to not be working

### ISSUE THREAD

**Issue by AGenius** [XeroAPI/Xero-NetStandard#298]
**SDK you're using (please complete the following information):**
 - Version 3.12.1

**Describe the bug**
The Assets API fails with an Unauthorized response yet the Accounting API with the same token/tenant works fine
`ApiException: Xero API error calling GetAssets: {"Type":null,"Title":"Unauthorized","Status":401,"Detail":"AuthorizationUnsuccessful","Instance":"2f3c568c-8d99-40c3-af5e-ba06f76fb23d","Extensions":{}}`

**To Reproduce**
```
Xero.NetStandard.OAuth2.Api.AssetApi xeroAPI_Assets = new Xero.NetStandard.OAuth2.Api.AssetApi();
var task = Task.Run(() => xeroAPI_Assets.GetAssetsAsync(AccessToken, TenantID, Xero.NetStandard.OAuth2.Model.Asset.AssetStatusQueryParam.REGISTERED));
task.Wait();
```

**Expected behavior**
List of Assets should be returned in the task.Result

**Comment by jamie-hoffmann-xero** [comment]
Hi @AGenius, I just wanted to gather some further information so I can assist you with this issue. First up, can you look at your `Scopes` configuration variable and check whether it has either `assets` or `assets.read` somewhere in the string.

If you are using `appsettings.json`, this should be in the section called `XeroConfiguration`.

**Comment by jenksguo** [comment]
Hi @AGenius, thanks for raising the issue. Looking at your error closely, I think it might be related to the tenant ID not being correct or null. 

401 AuthorisationUnsuccessful is related to the tenant, while 403 AuthorisationUnsuccessful might be related to the service or scope not being available.

**Comment by AGenius** [comment]
Hi,  

The issue was in fact the scope for assets was missing.  totally missed that thanks.

No longer an issue
