### ISSUE TITLE
ContactPersons collection on a contact always returns empty

### ISSUE THREAD

**Issue by jalley3** [XeroAPI/Xero-NetStandard#299]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]
Latest

**Describe the bug**
When running GetContactsAsync, i get my list of contacts but all of them have 0 contactpersons listed. I used the api previewer to create a contact with a contact person, this worked. I then verified in my contacts that this creation had succeeded and was able to see the contact person in the contact's page. However when i call GetContactsAsync() it gets the contact list but the contactpersons collection is always empty. Updating a contact w/ a contact person DOES work, it is just not getting them on the get. 

**Expected behavior**
Im able to see the contactpersons collection for a contact...

**Comment by jalley3** [comment]
It doesnt have the info in "GetContacts" but it is in GetContact singular, causing us to have to make N more calls where N is the number of contacts an org has

**Comment by AGenius** [comment]
Just to note, this is normal and is the same for other calls where there are additional collections

e.g. Invoices will not return all the LineItems when you fetch using the GetInvoices you have to perform a GetInvoice for each item!

I am planning on dealing with this with my own API Wrapper to allow a switch to be passed in an the GetInvoices will fetch the list and then fetch each one. 

This is ok for a small list but is not practical for a huge list.

It really depends on what you are doing

Ultimately I feel the Xero API needs the ability to request the additional detail in the calls

**Comment by jamie-hoffmann-xero** [comment]
Hi all, going to close this one. Feel free to reopen if the problem persists.
