### ISSUE TITLE
Potential issue with manage user secrets - appSettings

### ISSUE THREAD

**Issue by markogrady** [XeroAPI/Xero-NetStandard#3]
Not sure whether you will see this as an issue.
I use the manage user secrets so not to store my settings into source control which is best practice.
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio
if you include the appsettings.json into your output directory the configs won't be added.

I usually use DI and inject my settings as per the documentation
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration

https://github.com/XeroAPI/Xero-NetStandard/blob/4b710283811b7d28d7bb6eacc753369d006a5718/Xero.Api/ApplicationSettings.cs#L11

**Comment by MJMortimer** [comment]
Hey @markogrady, I've initially set it up this way as the other SDK had config stored on app.config files. I'm open to changing it however, so would you like to open a PR with your desired changes, and I'll take a look?
