### ISSUE TITLE
Unable to use Moq on "Where"

### ISSUE THREAD

**Issue by pajohns** [XeroAPI/Xero-NetStandard#30]
I'm attempting to unit test my xero implementation within a .NET API and it's failing when I use Moq to mock the Xero API as a dependency injection. When it hits this line...

`            mockXeroApi
                .Setup(xero => xero.Contacts.Where(It.IsAny<string>()).FindAsync())
                .ReturnsAsync(contactsEnum);`

where mockXeroApi is of type Mock<IXeroCoreApi>. I'm using Moq version 4.8.2 and xunit 2.3.1 for testing.

it fails having thrown a System.NotSupportedException stating "Parent does not have a default constructor. The default constructor must be explicitly defined". It only appears to throw this exception on the inclusion of the "Where" function.

**Comment by MJMortimer** [comment]
Hey @pajohns, is this something you can improve and fix in a pull request?

**Comment by MJMortimer** [comment]
Closing this one due to inactivity
