### ISSUE TITLE
Not really a bug but still needs to be tidied up

### ISSUE THREAD

**Issue by AGenius** [XeroAPI/Xero-NetStandard#304]
**SDK you're using (please complete the following information):**
 - Version 3.13.0

**Describe the bug**
Lots of warning messages about missing XML parameters

I have turned on the XML Documentation option in the project so now I see lots of places the XML comments aneed fixing
e.g.
\Api\AccountingApi.cs -  warning CS1573: Parameter 'accessToken' has no matching param tag in the XML comment for 'AccountingApi.GetInvoiceAttachmentByFileNameAsync(string, string, Guid, string, string)' (but other parameters do)

There are 1709 warnings for this parameter alone!

**To Reproduce**
Turn on the XML Documentation option

**Expected behaviour** <<< CORRECT SPELLING behaviour not behavior :)
No XML Warnings

**Screenshots**
N/A

**Additional context**
Needs correcting for tidiness

**Comment by jamie-hoffmann-xero** [comment]
Hi @AGenius, these warnings are likely to be addressed as part of some modernisation work we are attempting. Can update here when it's ready.
As for the spelling of behaviour/behavior, you'll have to take that up with our North American colleagues ;)

**Comment by jamie-hoffmann-xero** [comment]
Hi @AGenius, these warnings are resolved in SDK version 3.14.0. Thanks for drawing our attention to them.

**Comment by jenksguo** [comment]
Hey @AGenius, could you please reach out to me via jenks.guo@xero.com? I need to send you some Xero developer swags to thank you for your contribution lately. ❤️
