### ISSUE TITLE
How to use where condition while calling Payments API

### ISSUE THREAD

**Issue by rahulDev10** [XeroAPI/Xero-NetStandard#305]
Xero-NetStandard

Probably not a bug but a question, that how do we use a where condition while calling API?

To give moe context, I am using the below method to get all payments of PaymentType = ACCRECPAYMENT

**var paymentCondition = "PaymentType == \"ACCRECPAYMENT\" AND Date >= DateTime(" + fromDate.Year + "," + fromDate.Month + "," + fromDate.Day + ") AND Date <= DateTime(" + toDate.Year + "," + toDate.Month + "," + toDate.Day + ")";

payments = Task.Run(async () => (Payments)await api.GetPaymentsAsync(_accessToken, _xeroTenantID, null, condition)).Result;**

Now the issue is **PaymentType** property is not in the Payments model but withing payments model its in Payment property
like this: public List<Payment> _Payments { get; set; }

How do I access the PaymentType to pass in where condition?

If I use the above condition it gives me the following error:

![WhereCondition](https://user-images.githubusercontent.com/75336025/106542056-f916f400-6567-11eb-8999-18b1065503fa.png)

Thanks

**Comment by jamie-hoffmann-xero** [comment]
Hi @rahulDev10, thanks for reporting. I just want to clarify some details before diving into this issue.

I noticed that in your screenshot, you pass `condition` to the `GetPaymentsAsync` method instead of `paymentCondition`.
Could you double check the error message when passing `paymentCondition` as the argument?

**Comment by rahulDev10** [comment]
Hi @jamie-hoffmann-xero, yes I did check it again today with the right condition. But the error is the same.

**Comment by jamie-hoffmann-xero** [comment]
Hi @rahulDev10, could you post the new code and error message when using the correct condition? It'd help us out a lot for diagnosing the issue. Thanks :)

**Comment by SidneyAllen** [comment]
@rahulDev10 - checking to see if this is still an active issue for you?

**Comment by GraceYBR** [comment]
Hey @rahulDev10 if you still need help on this please feel free to reopen.
