### ISSUE TITLE
GetOrganisationCISSettingsAsyncWithHttpInfo returned empty/default CISOrgSetting

### ISSUE THREAD

**Issue by wiljoetradify** [XeroAPI/Xero-NetStandard#307]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2 3.11.2

**Describe the bug**
AccountingApi.cs > GetOrganisationCISSettingsAsyncWithHttpInfo returned default csharp CISOrgSetting object (rate: null, CISContractorEnabled: null, CISSubContractorEnabled: null) even though the API returned the correct JSON response.

**To Reproduce**
1. Integrate with Xero
2. Make sure that i can call the Xero API with my access token and tenant id
3. call GetOrganisationCISSettingsAsyncWithHttpInfo method

**Expected behavior**
It supposes to return an object CISOrgSettings with CISOrgSetting wrapped in a list as it is current returning a default object of CISOrgSetting

**Comment by jamie-hoffmann-xero** [comment]
Hi @wiljoetradify, thanks for reporting the issue. I've confirmed that there's a mismatch between the API response and our schema -- working on a solution now.

**Comment by wiljoetradify** [comment]
thanks @jamie-hoffmann-xero

**Comment by jamie-hoffmann-xero** [comment]
Hi @wiljoetradify, issue should be resolved in [v3.13.1](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.13.1). Thanks again for reporting, feel free to reopen if the problem persists.
