### ISSUE TITLE
[Feature Request] add ability to extract Aged Payables for all contacts at one API call

### ISSUE THREAD

**Issue by Ma3yTa** [XeroAPI/Xero-NetStandard#309]
**SDK**
 - Version 3.13.0

**Is your feature request related to a problem? Please describe.**
The problem is that it requires a long time to call https://developer.xero.com/documentation/api/reports#AgedPayablesByContact for all contacts.

**Describe the solution you'd like**
I want to extract all aged payables in one request for all contacts as you have on Xero website.

**Describe alternatives you've considered**
With the current implementation, I need to request aged payables for every contact. Requires many API calls.

**Comment by Ma3yTa** [comment]
good to have the same ability to extract aged receivables for all contacts at one API call https://api.xero.com/api.xro/2.0/Reports/AgedReceivablesByContact

**Comment by Albert-Xero** [comment]
Hi @Ma3yTa, 
Thanks for your feedback, the API does not currently have an endpoint to get all Aged Payables for all Contacts in one API call. If you would like to request this feature you can vote for it or add a comment on our [UserVoice](https://xero.uservoice.com/forums/5528-accounting-api/suggestions/16785307-aged-receivables-payables-by-all-contacts-in-api). I will close this issue and we will keep track of it on UserVoice.

**Comment by ahmadzunair987** [comment]
You can retrieve the same data from the Invoices table using the type attribute. This attribute has two possible values: ACCREC and ACCPAY.

- ACCREC represents Aged Receivables data, which corresponds to the AgedReceivable API. 
- ACCPAY represents Aged Payables data, which corresponds to the AgedPayable API.

By querying the Invoices table, you can differentiate between these two types and retrieve the relevant data for either Aged Receivables (ACCREC) or Aged Payables (ACCPAY).
