### ISSUE TITLE
[enhancement] Created by my app

### ISSUE THREAD

**Issue by saluton-mundo** [XeroAPI/Xero-NetStandard#31]
Hi Team Xero, 

So great to see an API which can be coded in a fluent manner i.e. .And() .Or etc. 

However, is it possible to abstract away the "createdByMyApp" see: https://developer.xero.com/documentation/api/invoices 

![image](https://user-images.githubusercontent.com/7760994/38836570-8af0df9e-41c6-11e8-915d-b3d57770d098.png)

Then we could chain it 

`api.Invoices..Where("Status == \"DRAFT\"").CreatedByMyApp();`

Trying to solve a potential issue of a client app creates invoices using the API and back office staff are also creating invoices manually.

**Comment by MJMortimer** [comment]
Would you like to open a pull request with this new functionality included? 
If not, I'll get to it when I get a bit of time. 

I assume we'll just need a new method on the [InvoicesEndpoint like this](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.Api/Core/Endpoints/InvoicesEndpoint.cs#L35-L38)

**Comment by MJMortimer** [comment]
This has been resolved in #35
