### ISSUE TITLE
Add RateLimit information return from API Calls

### ISSUE THREAD

**Issue by BTPDarren** [XeroAPI/Xero-NetStandard#310]
**SDK you're using (please complete the following information):**
 - Version [e.g. 3.13.1]

**Is your feature request related to a problem? Please describe.**
Problem is that extracting the Rate limit information is buried in the ApiClient calls to the API

**Describe the solution you'd like**
The Api should expose the last Rate Limit information returned from any call to the API

**Describe alternatives you've considered**
n/a

**Additional context**
I have implemented a working solution in my own .NET SDK and now have to merge my changes into any updates to this SDK.
My solution works very well and has only a small change required. a new RateLimitInfo model and a minor change to the ApiClient code.

## Model

```
  /// <summary>
    /// Returned Rate Limit Information
    /// </summary>
    public class RateLimitInfo
    {
        /// <summary>
        /// App Minute Limit: 10,000 calls per minute for the Connected App (ClientID)
        /// </summary>
        public int AppMinuteLimitRemaining { get; set; }
        /// <summary>
        /// Daily Limit: 5000 calls per day
        /// </summary>
        public int DayLimitRemaining { get; set; }
        /// <summary>
        /// Minute Limit: 60 calls per minute
        /// </summary>
        public int MinuteLimitRemaining { get; set; }
        /// <summary>
        /// DateTime stamp of when this information was last updated
        /// </summary>
        public DateTime WhenUpdated { get; set; }
        /// <summary>
        /// If you have exceed the minute or daily limit, this will have how many seconds to wait before making another request. 
        /// It is important to use the Retry-After to know when you can start making calls again.
        /// </summary>
        public int RetryAfter { get; set; }
    }
```

## Interface changes (IAsynchronousClient)
Add in the new property descriptor
```
/// <summary>
/// Stores the Returned Rate information from the API Call header
/// </summary>
Model.RateLimitInfo RateInfo { get; set; }
```
## Code change (ApiClient)
```
/// <summary>
/// Returned Rate Limit Information
/// </summary>
public Model.RateLimitInfo RateInfo { get; set; }
```
```
/// <summary>
/// Allows for extending result processing for <see cref="ApiClient"/> generated code.
/// </summary>
/// <param name="result">The result object</param>        
protected virtual void InterceptResult(IApiResponse result)
{
    RateInfo = new Model.RateLimitInfo();
    try
    {
        RateInfo.AppMinuteLimitRemaining = int.Parse(result.Headers["X-AppMinLimit-Remaining"][0]);
        RateInfo.DayLimitRemaining = int.Parse(result.Headers["X-DayLimit-Remaining"][0]);
        RateInfo.MinuteLimitRemaining = int.Parse(result.Headers["X-MinLimit-Remaining"][0]);
        RateInfo.WhenUpdated = DateTime.Parse(result.Headers["Date"][0]);
        RateInfo.RetryAfter = int.Parse(result.Headers["Retry-After"][0]);
    }
    catch (Exception)
    {
        // Do nothing for now?  Raise error?
    }
}
```
Finally add a call to the InterceptResult method to extract the returned Rate Limit information

in :-
`private async Task<ApiResponse<T>> Exec<T>(RestRequest req, IReadableConfiguration configuration)`

Add call before 
`return result;`

With 
```
InterceptResult(result);

return result;
```

**Comment by jenksguo** [comment]
Hey @BTPDarren, thanks very much for the suggestion. 

We had a chat on this today, the introduction of InterceptResult is a good idea however, we would like to leave the implementation details to the developers. We will implement this on our next release. 

Can we collaborate to get your implementation as an example in our SDK documentation? (in a form of a PR to the readme.md)

**Comment by BTPDarren** [comment]
My solution is what I am using, I only posted it to show how I think it could be implemented. more than happy for any alternative options.

**Comment by Albert-Xero** [comment]
Hi @BTPDarren ,
Thanks for sharing your solution here, as this is not an active bug we will close the issue and it will remain in the closed issue category. Developers will still be able to find your suggestion there.
