### ISSUE TITLE
CancellationToken 

### ISSUE THREAD

**Issue by joyhguan** [XeroAPI/Xero-NetStandard#316]
**SDK you're using (please complete the following information):**
 - Version [e.g. whatever the latest version on nuget]

**Is your feature request related to a problem? Please describe.**
Yes...This is no CancellationToken so even if an operation is cancelled the app will still wait xero api to return
:(

**Describe the solution you'd like**
Add CancellationToken as an argument and also use it in ApiClient 
change your SDK code from 
```
var response = await client.ExecuteAsync<T>(req);
```
to be something like 
```
var response = await client.ExecuteAsync<T>(req, cancellationToken);
```
:(

**Comment by jenksguo** [comment]
Hey @joyhguan we would like to follow your advice to add this cancellationToken in. However, I am a bit stuck on getting am example to work as a test. Could you please share an implementation example? e.g. start an Async API method and cancel it?

**Comment by JRising-Xero** [comment]
Cancellation tokens have now been added to all async methods with the 3.31.0 SDK release.

**Comment by joyhguan** [comment]
Yay!!!!
