### ISSUE TITLE
issue of accept unit price upto 4 decimal points

### ISSUE THREAD

**Issue by harshdesai** [XeroAPI/Xero-NetStandard#322]
I am using XeroAPI.Net nuget package of version 1.1.0.34.
Project url: https://github.com/XeroAPI/XeroAPI.Net
Here When I post invoice to xero i am sending item's unit price in 4 decimal points. but when xero uploading invoice its converting into 2 decimal points,So  I am getting my invoice total issue.
Can you please tell me any settings so that my unitprice will be recognize upto 4 decimal places..
By using api I know unitdp=4 i have to pass in Querystring But how to do same thing when i use XeroAPI.Net sdk

**Comment by AGenius** [comment]
The old API is no longer supported. The new API allows you to pass the unit dpi as a parameter in your calls now

**Comment by GraceYBR** [comment]
Hi @harshdesai, as stated above that SDK is no longer supported as it is for OAuth 1.0a which is scheduled for deprecation. The newer SDK (which is where you've raised this issue) does support unitdp as a query parameter. 

To learn more about how our OAuth 2.0 flow works and how to use the OAuth 2.0 client, check out our Xero developer blog post: [Up and running with .NET and Xero OAuth 2.0](https://devblog.xero.com/getting-started-with-net-xero-oauth2-0-763ba468a916).

If you want to have a go then I recommend you download a starter app so you can play around with the new SDK. A dotnet core 3.1 MVC one is available [here](https://github.com/XeroAPI/xero-netstandard-oauth2-starter-dotnet-core). A .NET Framework 4.6.1 one is available [here](https://github.com/XeroAPI/xero-netstandard-oauth2-starter-app-dotnet-framework).
