### ISSUE TITLE
Xero API 400 Error calling CreateInvoices

### ISSUE THREAD

**Issue by f3d3rica** [XeroAPI/Xero-NetStandard#327]
**SDK you're using (please complete the following information):**
- Xero.NETStandard.OAuth2 version v4.0.30319

**Describe the bug**
When I try to post invoice I get following error: Xero API 400 Error calling CreateInvoices

**To Reproduce**
This worked when I was connecting with one account. When I changed account, I got this error

**Comment by GraceYBR** [comment]
Hi @f3d3rica, thanks for raising an issue. 

Usually with 400 errors there will be an error that has more detail, do you have one you can share with us?

Additionally any code or more clear instructions on how to replicate the issue would be really helpful as it's not 100% clear at the moment.

When you said you changed account are you referring to changing Xero user accounts or changing Xero organisations within your Xero user account?

**Comment by GraceYBR** [comment]
Hey @f3d3rica I'm closing this issue as we've not heard back from you. Please re-open if you need to :)
