### ISSUE TITLE
The Xero.NetStandard.OAuth2.Api.PayrollNzApi returns null response

### ISSUE THREAD

**Issue by azhilt** [XeroAPI/Xero-NetStandard#334]
Version 3.15.0

PayrollNzApi.GetEmployeeSalaryAndWagesAsync(...)._SalaryAndWages throws 'object reference not set to an instance of an object'. Using GetEmployeeSalaryAndWagesAsyncWithHttpInfo returns the error "Error converting value "History" to type 'Xero.NetStandard.OAuth2.Model.PayrollNz.SalaryAndWage+StatusEnum'. Path 'salaryAndWages[0].status', line 1, position XXX."
Response content:
{
    "id": "XXX",
    "providerName": "XXX",
    "dateTimeUTC": "2021-03-22T11:23:37.3911924",
    "httpStatusCode": "OK",
    "pagination": {
        "page": 1,
        "pageSize": 100,
        "pageCount": 1,
        "itemCount": 3
    },
    "problem": null,
    "salaryAndWages": [
        {
            "salaryAndWagesID": "XXX",
            "earningsRateID": "XXX",
            "numberOfUnitsPerWeek": 45,
            "ratePerUnit": 18,
            "numberOfUnitsPerDay": 9,
            "daysPerWeek": 5,
            "effectiveFrom": "2016-03-14T00:00:00",
            "annualSalary": null,
            "status": "History",
            "paymentType": "Hourly"
        },
...

It seems some design changes are needed to prevent such errors when Xero adds new items to their enums. Or is there a way in API to prevent this?

**Comment by jenksguo** [comment]
Hi @azhilt looks like this "History" status is a new enum and we will need to add this into our SDK. We will fix this on the next release hopefully in a few days. :-)

**Comment by jenksguo** [comment]
This is resolved with release of [v3.16.0](https://www.nuget.org/packages/Xero.NetStandard.OAuth2/), thanks for reporting the issues @azhilt.
