### ISSUE TITLE
The Xero.NetStandard.OAuth2.Api.PayrollNzApi returns null response

### ISSUE THREAD

**Issue by azhilt** [XeroAPI/Xero-NetStandard#336]
Version 3.15.0
GetTimesheetsAsync returns null. GetTimesheetsAsyncWithHttpInfo displays the error 'Error converting value "Requested" to type 'Xero.NetStandard.OAuth2.Model.PayrollNz.Timesheet+StatusEnum'. Path 'timesheets[46].status', line 1, position XXX.'
Response contents:
{
    "id": "XXX",
    "providerName": "XXX",
    "dateTimeUTC": "2021-03-23T10:48:32.9443165",
    "httpStatusCode": "OK",
    "pagination": {
        "page": 3,
        "pageSize": 100,
        "pageCount": 9,
        "itemCount": 852
    },
    "problem": null,
    "timesheets": [
...
        {
            "timesheetID": "XXX",
            "payrollCalendarID": "XXX",
            "employeeID": "XXX",
            "startDate": "2018-05-21T00:00:00",
            "endDate": "2018-05-27T00:00:00",
            "status": "Requested",
            "totalHours": 44.5,
            "updatedDateUTC": "2018-05-25T05:01:27"
        },

**Comment by SidneyAllen** [comment]
@jenksguo @AlbertGromek @GraceYBR 

This has been addressed in version 2.10.2 of OAS
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.10.2

**Comment by jenksguo** [comment]
This is resolved now with [v3.16.0](https://www.nuget.org/packages/Xero.NetStandard.OAuth2/).
