### ISSUE TITLE
IXeroClient is missing RevokeAccessTokenAsync

### ISSUE THREAD

**Issue by BradMclain** [XeroAPI/Xero-NetStandard#337]
**SDK you're using (please complete the following information):**
 - Version 1.3.0

**Describe the bug**
`IXeroClient` is missing `RevokeAccessTokenAsync` and possibly also some of the variants of `BuildLoginUri` and `BuildLoginUriPkce`.

**Expected behavior**
Interface contains all public methods of implementation.

**Additional context**
Mocking of these methods for unit testing is not possible unless they are part of the interface.

**Comment by jenksguo** [comment]
Hi @BradMclain Thanks for reminding us of the missing methods in the interface. I have added it now in the [latest release](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.3.1).

**Comment by BradMclain** [comment]
Thanks @jenksguo
