### ISSUE TITLE
PaymentID returned by GetInvoice(s) can actually be the BatchPaymentID

### ISSUE THREAD

**Issue by benedict-odonovan** [XeroAPI/Xero-NetStandard#340]
**SDK you're using (please complete the following information):**
 - Version 3.14.4

**Describe the bug**
The PaymentID property within the nested list of payments returned from GetInvoicesAsync and GetInvoiceAsync can be a BatchPaymentID. If you use GetPaymentAsync with the returned "PaymentID" it will throw an error as no payment exists with that ID. 

**To Reproduce**
1. Create two invoices in Xero
2. Create a batch payment for those two invoices
3. Query either of those invoices using `var invoice = (await xeroApi.Api.GetInvoiceAsync(xeroApi.AccessToken, xeroApi.XeroTenantId, xeroInvoiceGuid))._Invoices.FirstOrDefault();`
5. Note that `invoice.Payments[0].PaymentID.Value` is the ID for a Batch Payment
6. Use that PaymentID to search for a payment `(await xeroApi.Api.GetPaymentAsync(xeroApi.AccessToken, xeroApi.XeroTenantId, invoice.Payments[0].PaymentID.Value))._Payments.FirstOrDefault();`
7. Receive an error message as no payment exists with that ID.

**Expected behavior**
The nested PaymentID should be the actual PaymentID, not the parent BatchPaymentID - or the object returned by GetInvoice(s) should show the payment type (batch or individual payment).

**Comment by jenksguo** [comment]
Hey @benedict-odonovan, Thanks for reporting this API behaviour. The SDK is behaving as expected but there is ambiguity in the PaymentID in Invoice object when it is coming from BatchPayment. 

I will provide feedback back to API team so this can be fixed accordingly.

**Comment by jenksguo** [comment]
Hey @benedict-odonovan thanks for reporting this. 

I have managed to put this on our development team's backlog. I will close this issue on the repo but we will update once it is addressed.
