### ISSUE TITLE
[OAuth1] Missing pagination on Payment endpoint breaking existing integration following API changes

### ISSUE THREAD

**Issue by Tyf0x** [XeroAPI/Xero-NetStandard#352]
**SDK you're using (please complete the following information):**
 - Version 1.1.4

**Describe the bug**
Our software is regularly polling the payments endpoint to get data. According to [this issue](https://github.com/XeroAPI/xero-php-oauth2-app/issues/31#issuecomment-790993513), the API endpoint changed recently to block inefficient queries.
Since the SDK doesn't support paging, we're stuck.

**Expected behavior**
The `Page(int page)` method should be implemented on the Payments endpoint

**Additional context**
We still use the SDK v1.1.4 since we were historically integrating through private apps. Migration to OAuth2 isn't possible in our case and we're waiting on [Custom Connections](https://developer.xero.com/announcements/custom-integrations-are-coming) to finally migrate to the new structure.

**Comment by SidneyAllen** [comment]
Hi @Tyf0x 

As of March 31st, 2021 OAuth 1.0a was officially deprecated.  Custom connections are coming and we will be focused on updating our OA2 SDKs to support those in the coming weeks.

I'm sorry to say we won't be prioritizing any updates to our OA1 codebases going forward.

You are free to fork this codebase and make updates in the interm if you wish.
