### ISSUE TITLE
Time entry missing INVOICED status

### ISSUE THREAD

**Issue by oharper** [XeroAPI/Xero-NetStandard#355]
**SDK you're using (please complete the following information):**
 - Commit 2168291

**Describe the bug**
The 'StatusEnum' is missing the 'INVOICED' status. This causes any time entries with status 'INVOICED' to not be returned.

**To Reproduce**
1. Get all TimeEntries
2. Only ACTIVE and LOCKED are returned, no INVOICED

**Expected behavior**
All Time entries should be returned including INVOICED

**Comment by AlbertGromek** [comment]
Hey @oharper,

Thanks for bringing this up. Looks like this has already been fixed in version 2.11.0 of the OpenAPI spec which we use to generate these SDKs, I will make a new release of the SDK with the updates.

Albert

**Comment by Abhisha1** [comment]
Hey @oharper 
Just following up that we have verified this issue has been resolved and subsequently closing off this issue. Thanks 😁
