### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by dwanless79** [XeroAPI/Xero-NetStandard#357]
**SDK you're using (please complete the following information):**
 - Version 3.16.1

**Describe the bug**
When trying to generate the LoginURI I am receiving the following error message System.MissingMethodException

**To Reproduce**
            var clientId = "XXXXXXXXXXXXXXXXXXXXXXX";
            var clientSecret = "XXXXXXXXXXXXXXXXXXXXXXX";

            XeroConfiguration xconfig = new XeroConfiguration();
            xconfig.ClientId = clientId;
            xconfig.ClientSecret = clientSecret;
            xconfig.CallbackUri = new Uri("XXXXXXXXXXXXXXXXXXXXXXX"); //default for standard webapi template
            xconfig.Scope = "openid profile email offline_access files accounting.transactions accounting.contacts";

            var client = new XeroClient(xconfig);

            var uri = client.BuildLoginUri().ToString();

**Expected behavior**
  The variable uri should contain the redirect uri

**Screenshots**
![Capture](https://user-images.githubusercontent.com/28442862/118400518-dcf01c00-b659-11eb-9356-997fd85a875f.PNG)

**Additional context**

**Comment by RettBehrens** [comment]
@dwanless79 We've had another issue opened regarding the same exception - wondering if you resolved this? #384 @RileyJamesXero

**Comment by batesyx** [comment]
> @dwanless79 We've had another issue opened regarding the same exception - wondering if you resolved this? #384 @RileyJamesXero

This issue is still existing on the latest versions. Why was it closed without a fix?

**Comment by rjaus** [comment]
Hey @RettBehrens, fyi this is my account on github.  Will delete that older one.

I have not resolved this issue as yet.

@batesyx it looks like the submitted closed the issue immediately, unsure why.  Possibly they found the existing issue.

**Comment by rjaus** [comment]
@batesyx are you having this issue as well?  If so, can you submit a sample which produces the error?

We've been unable to reproduced the error, as documented above.  Seems to work fine.

**Comment by rjaus** [comment]
This has now been reproduced.  A resolution is incoming
