### ISSUE TITLE
Api Rate Limit Error not response back 429 

### ISSUE THREAD

**Issue by hardik-technobrains** [XeroAPI/Xero-NetStandard#359]
**SDK you're using (please complete the following information):**
 - Version [3.16.1]

**Describe the bug**
I have concerned that I had called API ( Ex. PayrollAuApi().GwtEmploeesAsyncWithHttpInfo) for getting a response in .Net SDK. But when the API limit is reached (60 calls per minute), I got an exception with 429 errors. I should aspects response with 429 status code instead of the exception. I cannot get headers in the exception. Why it is thrown exception instead of responding back with 429 status code and headers. 

**To Reproduce**
You have to hit the 60 calls API limit given any API calls of SDK. In my case, I'm using the PayRollAuApi Methods. You will get an exception with the 429 error code. 

**Expected behavior**
Should return a response back if API limit is reached instead of the exception.

**Comment by 8to5Developer** [comment]
We have the same issue, any plan to solve this ?

A simple fix would be to create a new exception class that inherits from the ApiException which provides the HTTP headers, sth like:

```
public class ApiExceptionWithHttpInfo : ApiException
{
        private Multimap<string, string> Headers { get; }

        public ApiExceptionWithHttpInfo(Multimap<string, string> headers, int errorCode, string message, object errorContent = null) : base(
            errorCode,
            message,
            errorContent)
        {
            Headers = headers;
        }
    }

```
I can send a PR for it if you accept pull requests.
