### ISSUE TITLE
Creating ACCRECCREDIT credit note with AccountCode="200" returns error: "Account code '200' is not a valid code for this document"

### ISSUE THREAD

**Issue by DevelopmentDan** [XeroAPI/Xero-NetStandard#364]
**SDK you're using (please complete the following information):**
 - Version 3.17.0

**Describe the bug**
Creating ACCRECCREDIT credit note with AccountCode="200" returns error: "Account code '200' is not a valid code for this document"

**To Reproduce**
Using the demo company, in XERO, add a "ACCRECCREDIT " credit note with account code 200 "Income for any normal sales activity" - TAX: OUTPUT2 - everything works fine - so 200 is perfectly valid for ACCRECCREDIT 

Now try to do it through the API: 

Dim C As New Model.Accounting.CreditNote
  C.Type = Model.Accounting.Invoice.TypeEnum.ACCRECCREDIT
  C.CreditNoteID = Guid.Empty
  C.Date = DATE.TODAY
  C.Reference = "TEST INVOICE"
  C.Status = Model.Accounting.Invoice.StatusEnum.AUTHORISED
  C.Contact = New Model.Accounting.Contact With {.ContactID = R("ClientXeroContactID")} ' CONTACT OF YOUR CHOICE
  C.LineItems = New List(Of Model.Accounting.LineItem)
  Dim li = New Model.Accounting.LineItem
  li.Description = "TEST INVOICE LING"
  li.Quantity = 1
  li.UnitAmount = NET
  li.DiscountRate = Nothing
  li.TaxType = "OUTPUT2"
  li.AccountCode = "200"
  C.LineItems.Add(li)
  ' POST CREDIT NOTES
  Dim CreditNotes = New Model.Accounting.CreditNotes
  CreditNotes._CreditNotes = New List(Of Model.Accounting.CreditNote)
  CreditNotes._CreditNotes.Add(C)
  Dim Temp = Await XeroAccountingAPI.CreateCreditNotesAsync(XeroTokenX.Token, XeroTenantId.ToString, CreditNotes)
  C = Temp._CreditNotes(0)

**Expected behavior**
For it to create the credit note without complaint (it works fine for ACCPAY with AccountCode="310")

**Screenshots**
n/a

**Additional context**
Xero API 400 error calling CreateCreditNotes :{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements": [
    {
      "CreditNoteID": "00000000-0000-0000-0000-000000000000",
      "ID": "00000000-0000-0000-0000-000000000000",
      "HasErrors": true,
      "Type": "6",
      "Reference": "2",
      "Contact": {
        "ContactID": "85ea8919-6358-4514-b494-6365e5a0912f",
        "ContactNumber": "C-10339",
        "Addresses": [],
        "Phones": [],
        "ContactGroups": [],
        "ContactPersons": [],
        "HasValidationErrors": false,
        "ValidationErrors": []
      },
      "DateString": "2021-06-28T00:00:00",
      "Date": "\/Date(1624838400000+0000)\/",
      "Status": "AUTHORISED",
      "LineAmountTypes": "Exclusive",
      "LineItems": [
        {
          "Description": "Credit Note - Legal Fees",
          "UnitAmount": 1000.00,
          "TaxType": "OUTPUT2",
          "TaxAmount": 200.00,
          "LineAmount": 1000.00,
          "AccountCode": "200",
          "Tracking": [],
          "Quantity": 1.0000,
          "ValidationErrors": []
        }
      ],
      "SubTotal": 1000.00,
      "TotalTax": 200.00,
      "Total": 1200.00,
      "CurrencyCode": "GBP",
      "ValidationErrors": [
        {
          "Message": "Credit note not of valid type for creation"
        },
        {
          "Message": "Account code '200' is not a valid code for this document."
        }
      ]
    }
  ]
}

**Comment by wobinb** [comment]
I suspect the issue here is the TaxType being used. Assuming the default chart of accounts is being used 200 is an income account, and as such should be used with a tax rate for sales (typically the OUTPUT rates). You wouldn't be able to use one of the INPUT rates.

Are you able to re-attempt the call using the same OUTPUT2 tax rate?

**Comment by DevelopmentDan** [comment]
Sorry, my bad - no it does not work with "OUTPUT2" or "INPUT2" - you get the same error message either way.

**Comment by DevelopmentDan** [comment]
Model.Accounting.Invoice.TypeEnum. THIS ENUM NEEDS FIXING - I believe it should **not contain** ACCRECCREDIT and ACCPAYCREDIT - They should only exist against Model.Accounting.CreditNote.TypeEnum - that's why the code wasn't working.
