### ISSUE TITLE
The SDK configuration page on https://developer.xero.com/myapps/ is missing the Consumer Key

### ISSUE THREAD

**Issue by davidglassborow** [XeroAPI/Xero-NetStandard#37]
If you add an app, go into the details, and choose .NET core under the SDK configuration the screen will show the app settings, but will be missing the Consumer Key (the other choices like Java do not have this issue)

![xero](https://user-images.githubusercontent.com/55509/39880866-ebf0a46a-5476-11e8-898f-701fb74fcc26.png)

**Comment by philals** [comment]
Thanks for the bringing this oversight to our attention @davidglassborow 

We (mainly @MJMortimer) has fixed the issue.
