### ISSUE TITLE
GetBudgetsAsync has problem with Amount datatype in BudgetBalance Model

### ISSUE THREAD

**Issue by tuanphongvo** [XeroAPI/Xero-NetStandard#377]
We are using OAuth2 v3.18.1
I get an error with get single Budget (GetBudgetsAsync). The **Amount** field in Model defined as **Integer**. But Data return decimal values. It make error while convert number.

Ex: "Input string '9608.0000' is not a valid integer. Path 'Budgets[0].BudgetLines[0].BudgetBalances[0].Amount', line 20, position 33."

**Comment by wobinb** [comment]
This looks like an issue within our OpenAPI specification which is used to generate this (and the other) SDK. Once the change has been made here: https://github.com/XeroAPI/Xero-OpenAPI/pull/454 it will flow through to the SDK the next time it is generated.
