### ISSUE TITLE
Get Invoice as PDF

### ISSUE THREAD

**Issue by Lee337** [XeroAPI/Xero-NetStandard#38]
Is there any way to retrieve an invoice as a PDF using Xero-NetStandard?

**Comment by MJMortimer** [comment]
Yep, you can see some examples how in these example tests: https://github.com/XeroAPI/Xero-NetStandard/blob/master/CoreTests/Integration/Pdf/Get.cs

**Comment by Lee337** [comment]
Perfect! Thanks!
