### ISSUE TITLE
Xero.NetStandard.OAuth2Client

### ISSUE THREAD

**Issue by conradmicallef** [XeroAPI/Xero-NetStandard#384]
**SDK you're using (please complete the following information):**
 - net482

**Describe the bug**
OAuth2Client is not compatible with IdentityModel 5.x.x but only with 4.x.x

**To Reproduce**
1. updated identitymodel to 5.x.x ex 5.1.0
2. perform the authentication
3. it fails to generate the URL because of missing method in identitymodel 5.1.0

**Expected behavior**
To work seamlessly with upgraded identitymodel 5.x.x

*** Stack Trace ***
<html>
<body>

Method not found: 'System.String IdentityModel.Client.RequestUrlExtensions.CreateAuthorizeUrl(IdentityModel.Client.RequestUrl, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.Nullable`1<Int32>, System.String, System.String, System.Object)'.
--
Type | System.MissingMethodException
Stack Trace | at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri(String state, String scope)    at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri(String state)    at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri()

</body>
</html>

**Comment by AlbertGromek** [comment]
Hey @conradmicallef,

I was unable to reproduce your error.
Could you elaborate on what you are doing here? You have updated the IdentityModel package in the Xero Client to version 5.x.x and it's no longer working?

![image](https://user-images.githubusercontent.com/79074721/133545707-890aaab4-9dc4-43c0-abad-685dda756fdf.png)
![1](https://user-images.githubusercontent.com/79074721/133545714-23204a59-789e-40e8-a4f0-dec4d99cba5d.png)

I have tested that and it is still working. There doesn't seem to be any changes in the CreateAuthorizeUrl method that I can see between versions 4 and 5.

If you provide more details I can try to look into this further.

Cheers
Albert

**Comment by conradmicallef** [comment]
On 16/09/2021 05:42, AlbertGromek wrote:
>
> Could you elaborate on what you are doing here? You have updated the 
> IdentityModel package in the Xero Client to version 5.x.x and it's no 
> longer working?
>
Correct, it compiles, but fails to perform the authentication
>
> If you provide more details I can try to look into this further.
>
How can I better assist in you recreating the problem.

**Comment by batesyx** [comment]
> Hey @conradmicallef,
> 
> I was unable to reproduce your error.
> Could you elaborate on what you are doing here? You have updated the IdentityModel package in the Xero Client to version 5.x.x and it's no longer working?
> 
> ![image](https://user-images.githubusercontent.com/79074721/133545707-890aaab4-9dc4-43c0-abad-685dda756fdf.png)
> ![1](https://user-images.githubusercontent.com/79074721/133545714-23204a59-789e-40e8-a4f0-dec4d99cba5d.png)
> 
> I have tested that and it is still working. There doesn't seem to be any changes in the CreateAuthorizeUrl method that I can see between versions 4 and 5.
> 
> If you provide more details I can try to look into this further.
> 
> Cheers
> Albert

Hi Albert,

Just to follow up on @conradmicallef I have reproduced the same runtime error with the project compiling fine.

By downgrading IdentityModel to version 4.6.0 it runs and authenticates as expected.

**Comment by rjaus** [comment]
Hey @conradmicallef & @batesyx, appreciate your efforts.  

We've now resolve the issue thanks to @AlbertGromek's PR.  

A release will be going out shortly.
