### ISSUE TITLE
Contact Discount Property Is Readonly

### ISSUE THREAD

**Issue by mattpawson** [XeroAPI/Xero-NetStandard#388]
**SDK you're using (please complete the following information):**
 - Latest

**Describe the bug**
When creating a new contact, you are not able to set the 'Discount' property. Error message reads "The default discount rate for the contact (read only). Property or indexer 'Contact.Discount' cannot be assigned to -- it is read only"

**To Reproduce**
contact = new Contact();
contact.Discount = 5;

**Expected behavior**
In the old SDK it was possible to update this value.

Can anyone explain why we can't now set the default discount code for the contact through the SDK?

**Comment by JRising-Xero** [comment]
Hi mattpawson,
Unfortantely, the accounting api does not support setting the discount property when creating a new contact at this stage. For this reason it is a `private set` in the sdk. 
If you wish for this ability to be added to the api you can raise a request on our [feature request page](https://xero.uservoice.com/forums/5528-accounting-api/suggestions/5010244-make-the-brandingtheme-for-a-contact-customizable).
Thanks.
