### ISSUE TITLE
Add CreatePayslipAsync(), can currently only UpdatePaySlip

### ISSUE THREAD

**Issue by humphrey** [XeroAPI/Xero-NetStandard#392]
**SDK you're using (please complete the following information):**
 - Version [e.g. 0.1.0]

**Is your feature request related to a problem? Please describe.**
I have until tomorrow to finish switching from v 1.0.5 to lastest SDK with OAuth2 before our integration stops working.  However, our code depends on creating payslips, which is missing from the latest SDK

**Describe the solution you'd like**
New `CreatePayslipAsync` method 

**Describe alternatives you've considered**
- Copy and pasting `UpdatePayslipAsync`, modifying it, and adding CreatePayslipAsync to my own code.
- Not using the SDK at all, but I no longer have enough time to switch.

**Additional context**
This is a regression to from v1.0.5  and makes the SDK provide less functionality than your Raw API provides.

**Comment by JRising-Xero** [comment]
Hi humphrey,
The creation of pay slips is not supported by our payroll APIs, it is expected that pay slips will automatically be generated by Xero from employee salaries.
You can raise a feature request [here](https://xero.uservoice.com/), if you believe that this decision should be reconsidered.
Thanks.

**Comment by humphrey** [comment]
@JRising-Xero I don't mind this being closed, as we never ended up using this SDK. We tried, but it was too much work to port our solution from the previous SDK (especially since this feature was missing) to this version.  Instead we adapted the old SDK we had already been using (Xero.Api.SDK.Core 1.1.4) to work with the newer authentication.

> The creation of pay slips is not supported by our payroll APIs, it is expected that pay slips will automatically be generated by Xero from employee salaries.

Your REST API's (and previous SDK's) absolutely supported Creating Payslips using the API.  

Our integration has been doing this for years - and it still creates payslips every week.  When we initially wrote this integration, there was no indication in the API documentation that you should use it as you have specified.  For historical reasons, and because extra data is needed beyond what can be stored in Xero, employee time-sheets are entered into our integration, and then sync'ed up to Xero.

**Comment by JRising-Xero** [comment]
Thanks for the additional context @humphrey. With a bit more digging it seems that the API does support pay slip creation via a POST request. Unfortunately, this is not documented anywhere which definitely makes investigating the matter confusing.
 I'll notify the API team to update the official documentation as well as make a change to our current SDK to support this endpoint.
 Thanks again raising this issue :)
