### ISSUE TITLE
GetContacts, missing optional "searchTerm" parameter

### ISSUE THREAD

**Issue by uniquelau** [XeroAPI/Xero-NetStandard#393]
**SDK you're using (please complete the following information):**
 - 3.19.0 (NuGet)

**Is your feature request related to a problem? Please describe.**
The Xero GetContacts API has been updated to have an additional optional parameter `searchTerm`
https://developer.xero.com/documentation/api/accounting/contacts#get-contacts

**Describe the solution you'd like**
Add the additional parameter into the generated API.
Happy to make a PR, but I couldn't figure out where the API specification comes from.

Many thanks, L

**Comment by Abhisha1** [comment]
Sorry for the delay in getting back to you @uniquelau, but the SDK has been regenerated with the changes you've mentioned.
Thanks for submitting this issue😄
