### ISSUE TITLE
Unauthorized Response When Using DateTime Where Clause in Invoices Endpoint

### ISSUE THREAD

**Issue by ckapatch** [XeroAPI/Xero-NetStandard#40]
Hello I'm testing out the Xero api and have ran into an interesting issue with the Invoices endpoint. I wanted to query using a date field and have used the following code to do so (following the example test project):

    var invoices = await _api.Invoices
      .Where(string.Format("DueDate > DateTime({0},{1},{2})", today.Year, today.Month, today.Day))            
      .OrderByDescending("DueDate")
      .FindAsync();

However this returns an unauthorized exception (Fiddler trace):
```
GET https://api.xero.com/api.xro/2.0/Invoices?where=Date%20%3E%20DateTime(2018%2C6%2C9)&order=DueDate%20DESC&unitdp=4&page=1 HTTP/1.1
Accept: application/json
Authorization: OAuth oauth_consumer_key="1WAFXDGUOLYDBJ6WIBAONFB0ARBK3T", oauth_token="1WAFXDGUOLYDBJ6WIBAONFB0ARBK3T", oauth_signature_method="RSA-SHA1", oauth_signature="Vgb8o%2FydTVNHwCaUPGy1A7iIkFDLAAoJVOyu8xZ0Xnp6TIhe3QgjAbllkmxMxnJBU28Jeo1%2FtxnvL54DjkNHecXhQxQw5bmX%2BR8NOVC23JrBXDCpcMjIhe05kLPjKjmxkupMvYey7xN9dsAIEjxF5BQIXLGPesi3OYl97NdWCMk%3D", oauth_timestamp="1528563743", oauth_nonce="cb5be1f7-9eaa-4edc-a106-d9ca38324893", oauth_version="1.0"
User-Agent: Xero-NetStandard%20-%201WAFXDGUOLYDBJ6WIBAONFB0ARBK3T
Host: api.xero.com
Request-Context: appId=cid-v1:6e14d65f-d2ce-45c6-ba7d-e1d67cc912d0
x-ms-request-root-id: btMeQAEVmlw=
x-ms-request-id: |btMeQAEVmlw=.b1e08d08_4.
Request-Id: |btMeQAEVmlw=.b1e08d08_4.
Accept-Encoding: gzip, deflate


HTTP/1.1 401 Unauthorized
Cache-Control: private
Content-Type: text/html; charset=utf-8
Date: Sat, 09 Jun 2018 17:02:23 GMT
Strict-Transport-Security: max-age=31536000
WWW-Authenticate: OAuth Realm="10.144.135.155"
Content-Length: 87
Connection: keep-alive

oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature
```

The interesting thing is that if I remove the DateTime clause:

    var invoices = await _api.Invoices             
      .OrderByDescending("DueDate")
      .FindAsync();

Everything seems to work fine:

```
GET https://api.xero.com/api.xro/2.0/Invoices?order=DueDate%20DESC&unitdp=4&page=1 HTTP/1.1
Accept: application/json
Authorization: OAuth oauth_consumer_key="1WAFXDGUOLYDBJ6WIBAONFB0ARBK3T", oauth_token="1WAFXDGUOLYDBJ6WIBAONFB0ARBK3T", oauth_signature_method="RSA-SHA1", oauth_signature="S%2F2JnhTG%2F35cmDgN4IAC9qh%2FvkR%2B0p34UG82PazVWg1CC3HS7Quf734bg%2FFC9rmO%2Bi2XE94xq4RUz3L%2BqYAuWffXZhvOYkwSFv6ap2sL%2FwFfpD1zKZ67lbErbr7k9uML3%2BaJOowr9Pnm5D8vDq0ktofWSKOBrSbqGMibhzOPbRc%3D", oauth_timestamp="1528563911", oauth_nonce="cd5edf34-fd9d-4d5e-b074-e93ccde47159", oauth_version="1.0"
User-Agent: Xero-NetStandard%20-%201WAFXDGUOLYDBJ6WIBAONFB0ARBK3T
Host: api.xero.com
x-ms-request-root-id: f3fdt/Mr7IY=
x-ms-request-id: |f3fdt/Mr7IY=.4afe478e_4.
Request-Id: |f3fdt/Mr7IY=.4afe478e_4.
Accept-Encoding: gzip, deflate


HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Date: Sat, 09 Jun 2018 17:05:10 GMT
Strict-Transport-Security: max-age=31536000
WWW-Authenticate: OAuth Realm="api.xero.com"
Xero-Cell: favorit
Content-Length: 129629
Connection: keep-alive
 
{...}

```

I'm not quite sure what's going on or why I'm getting the exception. Does anyone have any idea?

Thanks for the great library!

**Comment by MJMortimer** [comment]
Hey @ckapatch,

I can't seem to reproduce the issue. Is there any more context you could give me around how/where you're running your project?

**Comment by MJMortimer** [comment]
Actually, looking at my fiddler trace my URL looks like this:
```
https://api.xero.com/api.xro/2.0/Invoices?where=DueDate%20%3E%20DateTime%282018%2C6%2C9%29&order=DueDate%20DESC&unitdp=4&page=1
```

Note how the parenthesis in the DateTime construction have been encoded for mine but not for yours. I'll have to have a dig around and see where that logic is derived from

**Comment by MJMortimer** [comment]
Hey @ckapatch, 
The SDK uses [Uri.EscapeDataString(string)](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.Api/Common/QueryGenerator.cs#L35) to encode the query parameters and it seems that it's choosing to not encode the parenthesis for you.

Are you able to give me more details on the environment that your application runs in that results in this issue?

**Comment by ckapatch** [comment]
Sorry @MJMortimer I've been away for about a month, much needed break. Not sure what you mean by environment? Give me some more clarity and I'll provide what I can to help.

**Comment by MJMortimer** [comment]
I think some details about the operating system etc might be useful. I'm wondering whether Uri.EscapeDataString has different functionality depending on which system the code is being executed on. Clutching at straws a bit to be fair though haha

**Comment by ckapatch** [comment]
Hey @MJMortimer. Just using a windows 10 version 1803

**Comment by MJMortimer** [comment]
Hey @ckapatch, I'm yet to be able to diagnose the issue. 
Have you had any discoveries on your side?

**Comment by MJMortimer** [comment]
Are you using the SDK in an app running on netcoreapp2.0 or something different?

Is there a chance you could set up a git repository I can pull down, with a runnable solution that I can plug my own consumer key details into to see if using the same code, we can both reproduce the problem?

**Comment by fireeeye** [comment]
I just had the same issue, the problem atleast in my case was that .net handles EscapeDataString in [two different](https://stackoverflow.com/questions/26309731/why-does-uri-escapedatastring-return-a-different-result-on-my-ci-server-compared) ways based on if it is below 4.5 or less than 4.5. 

It also [defaults to 4.0](https://stackoverflow.com/questions/41006873/uri-escapedatastring-behaves-different-in-nunit-test-vs-asp-net-webservice) if nothing is specified in httpRuntime's targetFramework even if its specified in compilation tag. 

Obviously far too late for original issue, but just in case someone else has same issue in future.
