### ISSUE TITLE
GetContactsAsync - if-modified-since is not working

### ISSUE THREAD

**Issue by redware** [XeroAPI/Xero-NetStandard#400]
I am using the latest version of the Standard API and seem to have a new problem in that all contacts are being returned despite the fact that I am specifying the if-modified-since date. I am using DEMO Database but have had code working well previously. The date works on INVOICE. 

I wonder - is this a problem with the latest version of the Xero .NET Standard API or something else ? Is there a workaround to specify a query for the date modified until this is fixed ?

            **Task<Xero.NetStandard.OAuth2.Model.Accounting.Contacts> task = Task.Run<Xero.NetStandard.OAuth2.Model.Accounting.Contacts>(async () => await AccountingApi.GetContactsAsync(caccesstoken, ctenantid, dtmodified, cwhere, page: npage));
            Contacts oxerocontacts = oxerocontacts = task.Result;**

**Comment by Abhisha1** [comment]
Hi @redware 
Sorry for the delay in looking into this, but I have investigated this and have not been able to reproduce the issue mentioned in the latest version of the SDK. Could you please provide more details as to what parameters are being passed into the call (dtmodified, cwhere, npage) if you are still having this issue?

**Comment by Abhisha1** [comment]
Hi @redware 
I am going to close this issue as the latest version of the SDK doesn't have this issue. Feel free to reopen this issue if required. Thanks :)
