### ISSUE TITLE
RestSharp 107.0.0+ breaking changes

### ISSUE THREAD

**Issue by alexthekid07** [XeroAPI/Xero-NetStandard#401]
It seems that in RestSharp 107.0.0 they switched to using HttpClient which swapped around some interfaces and functions that this Xero library uses. Some things we're trying to do like UpdateInvoiceAsync no longer work properly as they throw exceptions not being able to locate certain RestSharp functions anymore.
Downgrading RestSharp to the most recent version prior to 107.0.0 fixes this.

https://github.com/restsharp/RestSharp/releases/tag/107.0.0

**Comment by wizzardmr42** [comment]
Not sure if anything else is required, but I think Client/ApiClient.cs line 329 needs fixing as that RestRequest constructor doesn't seem to be available anymore

**Comment by nanosoftlk** [comment]
Is there any fix available yet? I just realized that I am too late to downgrade RestShart to 106.x.x

**Comment by david-buzz** [comment]
Yes, this is also a problem for me.  I will have to work out how to downgrade too.  Can the Xero.NetStandard package be changed to specify only works for 106.x.x?  To prevent NuGet from upgrading RestSharp to 107.x?  BTW, my bug is calling the RestRequest constructor (method not found).  I am using Xero.NetStandard.OAuth2 v3.23.0 and RestSharp 107.3.0.

**Comment by alexthekid07** [comment]
The recent release led me to believe they fixed this, but instead it's just targeting a significantly outdated version still

**Comment by KonnectSalon** [comment]
Any News with this?

**Comment by david-buzz** [comment]
Ditto.  What are the plans with this?  When can I use the wrapper and have it include the correct version of RestSharp?

**Comment by RettBehrens** [comment]
@Abhisha1 @rlayhbrian the next release should resolve this, yes? The fix was merged yesterday? #439

**Comment by Abhisha1** [comment]
Hi all 👋🏾 
Sorry for the delay but as @RettBehrens is correct. We just pushed an update to move to RestSharp v108 which should fix this and it'll be available in our next release.

**Comment by Abhisha1** [comment]
We've just released these changes in version 3.28.1 🎉! Thanks all
