### ISSUE TITLE
AustralianPayroll constructor config missing extra parameters

### ISSUE THREAD

**Issue by dan-harris** [XeroAPI/Xero-NetStandard#41]
Firstly, thanks for the Xero-Net libraries... makes working with the Xero API pretty easy!

I'm having the problem that the Xero core library `AustralianPayroll` doesnt allow config (namely `baseUrl`, `consumerKey` & `consumerSecret`) to be passed directly through the constructor;

https://github.com/XeroAPI/Xero-NetStandard/blob/fe67496f3302981ebdd2424ad7ac092b8bf88397/Xero.Api/Payroll/AustralianPayroll.cs#L14

https://github.com/XeroAPI/Xero-NetStandard/blob/fe67496f3302981ebdd2424ad7ac092b8bf88397/Xero.Api/Payroll/Common/PayrollApi.cs#L12

The Xero-Net library does allow this:

https://github.com/XeroAPI/Xero-Net/blob/75b2dc63b2ed25d215e3c8bdc4ea66ddc5ea4f7c/Xero.Api/Payroll/AustralianPayroll.cs#L19

Is there any reason for the difference? at the moment, our workaround is to create `CustomPayrollApi` & `CustomAustralianPayroll` classes with constructors that allow these configs.

If its an oversight, I'm happy to raise a PR to fix these constructors (or provide an overload constructor).

**Comment by dan-harris** [comment]
@MJMortimer - apologies to single you out, but you're the last to update on this repo.... any response to the above?

**Comment by dan-harris** [comment]
Awesome. Thanks mate, will do.

**Comment by MJMortimer** [comment]
Thanks for your contributions @dan-harris!
