### ISSUE TITLE
EarningsType LUMPSUMW

### ISSUE THREAD

**Issue by tdieguez** [XeroAPI/Xero-NetStandard#411]
**SDK you're using (please complete the following information):**
- Xero.NetStandard.OAuth2 / [3.18.1]

**Describe the bug**
Missing value in enumeration.
**LUMPSUMW**

**To Reproduce**
1. Go to Xero AU Organisation > Settings > Payroll Settings > Pay Items > Earnings > Add > Lump Sum W
2. Call IPayrollAuApiAsync.GetPayItemsAsyncWithHttpInfo in a client using the SDK
3. Exception thrown
   * Error converting value "LUMPSUMW" to type 'Xero.NetStandard.OAuth2.Model.PayrollAu.EarningsType'.

**Expected behavior**
LUMPSUMW should be included in EarningsType.

**Comment by RettBehrens** [comment]
Hi @tdieguez confirming `LUMPSUMW` is available in the latest version 3.22.1 along with a number of other [updates](https://github.com/XeroAPI/Xero-NetStandard/releases) to the AU Payroll API

https://github.com/XeroAPI/Xero-NetStandard/blob/21cedf78a522c2721454cb0f85c47dcf0aea41f9/Xero.NetStandard.OAuth2/Model/PayrollAu/EarningsType.cs#L95-L99
