### ISSUE TITLE
Purchase Orders now fail validation

### ISSUE THREAD

**Issue by simonlaszcz** [XeroAPI/Xero-NetStandard#412]
- Version: latest

The following validation error is now raised when creating/updating a purchase order:
The line total 0 does not match the expected line total N

This is new behaviour as the exact same code worked yesterday (21 Feb 2022) in the UK

**Comment by Sallyhornet** [comment]
Please could you raise a case with Xero Support by emailing api@xero.com.

Could you include your client id, the connected tenant name as it appears in Xero and the date and time of the error and then we can check the logs for you

**Comment by simonlaszcz** [comment]
Hi, thanks for answering. I've now fixed the problem in our code by supplying null values (instead of zero) for discount rate and amount
