### ISSUE TITLE
GetOrganisationsAsync failing to parse OrganisationTypeEnum

### ISSUE THREAD

**Issue by davidmcgill-bf** [XeroAPI/Xero-NetStandard#415]
GetOrganisationsAsync is returning null although data is coming through. Using GetOrganisationsAsyncWithHttpInfo the ErrorText 
is 
`Error converting value "INDIVIDUAL" to type 'Xero.NetStandard.OAuth2.Model.Accounting.Organisation+OrganisationTypeEnum'. Path 'Organisations[0].OrganisationType', line 13, position 38.`

Has this Enum been updated as I cannot see the "Individual" type in the documentation. This has only recently started occurring recently.

**Comment by Sallyhornet** [comment]
I believe https://github.com/XeroAPI/Xero-OpenAPI/pull/479 will resolve this as it adds the Individual entity type to the library
