### ISSUE TITLE
Error for BAS or GST Report for Custom Integration Machine to Machine Implementation

### ISSUE THREAD

**Issue by MonAwasthi** [XeroAPI/Xero-NetStandard#423]
**SDK you're using (please complete the following information):**
 -Using  Xero NetStandard SDK
upgraded version to "Xero.NetStandard.OAuth2Client" version="1.5.3"

**Describe the bug**
I am implementing Machine to machine integration for Xero in my .net application. As soon as I upgraded the xero packages it threw me an error for GetReportBASorGSTListAsync report endpoint in IAccounting API.. Is the endpoint for GetReportBASorGSTListAsync has been changed?

Below is the error-> 'IAccountingApi' does not contain a definition for 'GetReportBASorGSTListAsync' and no accessible extension method 'GetReportBASorGSTListAsync' accepting a first argument of type 'IAccountingApi' could be found (are you missing a using directive or an assembly reference?

I am using Demo company AU in Xero to test my app. 

![image](https://user-images.githubusercontent.com/105791271/169035143-b11f19e2-5c76-4c87-9f91-c300dd68aa1d.png)

**Comment by RettBehrens** [comment]
Hi @MonAwasthi could you confirm which version you upgraded from?

**Comment by RettBehrens** [comment]
Ah, never mind, sorry. I've identified where the issue stems from. The methods were renamed about a year ago https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v3.17.0
