### ISSUE TITLE
ifModifiedSince not working

### ISSUE THREAD

**Issue by kalebraid** [XeroAPI/Xero-NetStandard#428]
await accountingApi.GetBankTransactionsAsync(xeroToken.AccessToken, xeroToken.Tenants[0].TenantId.ToString(), ifModifiedSince: waterMark.Value, where: "Type==\"RECEIVE\"", page: currentPage);

Expected
Only items that have changed since the DateTime <waterMark.Value>

Actual 

Every Bank Transaction of Type==RECEIVE

Xero.NetStandard.OAuth2Client v 1.6.0

**Comment by Abhisha1** [comment]
Hi @kalebraid 👋🏾 
Sorry for the delay but I've had a look and can't reproduce the issue you mentioned above using the latest version of the SDK.

Using the detail you provided, I made a call to the API like so below and only see bank transactions of type receive that were created or modified after the ifModifiedSince argument.
```c#
var response = await AccountingApi.GetBankTransactionsAsync(accessToken, xeroTenantId, DateTime.Parse("2022-09-08T01:15:54.943Z"), "Type ==\"RECEIVE\"", page: 1);
```

Let me know if you are still encountering this issue when using the latest version of the SDK.

**Comment by Abhisha1** [comment]
Hi @kalebraid As I haven't heard back from you and the latest version of the SDK doesn't have this problem, I am going to close this issue.
Feel free to re-open if needed.
Thanks :)
