### ISSUE TITLE
GetPayItemsAsync returns null

### ISSUE THREAD

**Issue by x86digital** [XeroAPI/Xero-NetStandard#429]
Calling this method returns null object, it would seem this error has occurred before due to a type mismatch but not sure what type is now being returned causing the issue. Is only happening with 1 Xero company so assume they have made a change to a PayItem or similar which is now causing the method to return null?

var _xeroPayItems = await apiInstance.GetPayItemsAsync(accessToken, xeroTenantId, null, null, null, null);
returns null

**Expected behavior**
Should return filled object

**Comment by Abhisha1** [comment]
Hi @x86digital 👋
Sorry for the delay in getting back to you. 

Using the information provided, I did a quick look into this and I suspect the problem may be related to the paid parental leave type in earnings for pay items. We added the `PAIDPARENTALLEAVE` type in version 3.27.0 (which was released in August). I would recommend upgrading to the latest version and then please let me know if you are still facing this issue.

Thanks

**Comment by Abhisha1** [comment]
Hi @x86digital 
I am going to close this issue as it is working correctly in the current version. Feel free to reopen this issue if required.
Thanks
