### ISSUE TITLE
RenewToken/GetRequestToken/GetAuthorization deadlock

### ISSUE THREAD

**Issue by Quppa** [XeroAPI/Xero-NetStandard#43]
The methods `RenewToken` (in `PartnerAuthenticatorBase`), `GetToken` and `GetRequestToken` (in `TokenStoreAuthenticatorBase`) cause deadlocks when called from applications with a `SynchronizationContext` (e.g. an ASP.NET Web Forms/MVC/Web API application).

This can be worked around by adding `ConfigureAwait(false)` all the way down (which I've done in #42), which is a good idea, anyway, but can we make these methods `async`, too?

**Comment by MJMortimer** [comment]
As mentioned in the comment on #42, chances are the .Results are still hangovers from the initial porting of the Xero-Net SDK. If you'd like, feel free to make that change and I'll review

**Comment by Quppa** [comment]
All right - I've prepared a branch with that change [here](https://github.com/XeroAPI/Xero-NetStandard/compare/master...Quppa:ITokenStoreAsync). This will be a breaking change, however, since some methods will now be `async` where they weren't previously (and I changed the signatures to include the suffix `Async` to be clear).

I can either merge those changes with #42 or leave them separate.

**Comment by MJMortimer** [comment]
I think you may as well merge into #42 and I'll release it all with a version bump large enough to allow for the small breaking changes. Cheers

**Comment by MJMortimer** [comment]
Actually open it as a separate PR. There's a couple questions I have about the refactor of the autheticators

**Comment by Quppa** [comment]
Sure: I opened #47.

I might need to rebase if #42 is merged first.

**Comment by MJMortimer** [comment]
Thanks for your contributions @Quppa, the PR has been merged and released
