### ISSUE TITLE
New not supported type 'NONEINPUT' in ReportTaxTypeEnum

### ISSUE THREAD

**Issue by SergeyPiskov** [XeroAPI/Xero-NetStandard#430]
Hi,

I have got issue with new unsupported type 'NONEINPUT' in ReportTaxTypeEnum

![image](https://user-images.githubusercontent.com/4173143/179676351-628b0d76-7337-4577-8ac9-f3fec2ecfe21.png)

**Comment by SergeyPiskov** [comment]
It happens on Xero organisation from Canada

**Comment by Abhisha1** [comment]
Hi @SergeyPiskov 
I've started to look into this issue and it would be great if you could provide some steps as to how to reproduce the error. Thanks :)

**Comment by SergeyPiskov** [comment]
Hi @Abhisha1 

I can't provide any details. we got the issue with our Canadian client. He is using Xero we were unable to load data from Xero due to the error. 
Debugging allowed to us fix source code and add required values to enums.

**Comment by Abhisha1** [comment]
Hey @SergeyPiskov 
Thanks again for reporting this issue! Just wanted to follow up and let you know we have added the missing enums into the SDK and it is now available in our latest release (3.28.0)
