### ISSUE TITLE
Method not found: RestSharp.RestRequestExtensions.AddFile

### ISSUE THREAD

**Issue by Yahya0007** [XeroAPI/Xero-NetStandard#442]
**SDK you're using (please complete the following information):**
- Xero.NetStandard.OAuth2 - Version 3.28.1
- Xero.NetStandard.OAuth2Client - Version 1.6.0.
- ResetSharp - Version 108.0.2.0

**Describe the bug**
apiInstance.GetInvoicesAsync(xeroToken.AccessToken, xeroTenantId,, where) was working fie but recently has stopped working with below exception;

`-		ex	{"Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String)'."}	System.Exception {System.MissingMethodException}
		ClassName	Nothing	String
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2146233069	Integer
		HelpLink	Nothing	String
+		InnerException	Nothing	System.Exception
		MemberName	Nothing	String
		Message	"Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String)'."	String
		Signature	Nothing	Byte()
		Source	"Xero.NetStandard.OAuth2"	String
		StackTrace	"   at Xero.NetStandard.OAuth2.Client.ApiClient.newRequest(HttpMethod method, String path, RequestOptions options, IReadableConfiguration configuration)" & vbCrLf & "   at Xero.NetStandard.OAuth2.Client.ApiClient.<GetAsync>d__9`1.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & "   at Xero.NetStandard.OAuth2.Api.AccountingApi.<GetInvoicesAsyncWithHttpInfo>d__262.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & "   at Xero.NetStandard.OAuth2.Api.AccountingApi.<GetInvoicesAsync>d__261.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & "   at EMS.BusinessObjects.modAccountsExport.VB$StateMachine_18_XeroCompareInvoice.MoveNext() in G:\MyProject\Library\modAccountsExport.vb:line 1475"	String
+		TargetSite	{RestSharp.RestRequest newRequest(Xero.NetStandard.OAuth2.Client.HttpMethod, System.String, Xero.NetStandard.OAuth2.Client.RequestOptions, Xero.NetStandard.OAuth2.Client.IReadableConfiguration)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
`

**To Reproduce**
Call apiInstance.GetInvoicesAsync(xeroToken.AccessToken, xeroTenantId,, where)

**Comment by RettBehrens** [comment]
Hi @Yahya0007 we recently released an [update](https://github.com/XeroAPI/Xero-NetStandard/pull/439/files) that included upgrading from 106.12.0 to 108.0.1.

I just just tested GetInvoicesAsync using our [sample app](https://github.com/XeroAPI/xero-netstandard-oauth2-app) running the latest SDK and was unable to replicate the issue locally.

Even though I'm unable to replicate using the sample app I do believe the issue stems from this update. Is there anything in #439 that stands out to you?

**Comment by Abhisha1** [comment]
Hi @Yahya0007 

Just following up on this issue, it might be that the mismatch of the RestSharp versions may be the issue here as we are using 108.0.1 but you are using 108.0.2.

As we are unable to replicate this, if you are still facing this issue when you use RestSharp version 108.0.1, could you try put together a minimal project that replicates the issue (without including your client id/secret ) and share it with us. This would be  helpful in trying to solve what is causing the issue you face given we cannot reproduce the issue.
Thanks

**Comment by Yahya0007** [comment]
Hi

 

When we use 108.0.1 then it says error loading 108.0.2.

 

Regards

 

Yahya

**Comment by Abhisha1** [comment]
hi @Yahya0007 
Thanks for letting me know. In that case, is it possible for you to spin up a minimal project without your secrets that replicates this issue? I have tried again and still cannot reproduce this particular issue here so creating a project would be really helpful.

**Comment by Abhisha1** [comment]
Hi @Yahya0007 
Just wanted to follow up on this issue. Were you able to recreate the issue in a small project?

If not, could you perhaps provide the package references used in your project. There may be a mismatch of RestSharp versions that might be causing the issue. 

Thanks

**Comment by Yahya0007** [comment]
Hi Abhisha

 

The project is large and intertwined so hard to turn into a small project. References in the project with Xero code attached.

 

Thanks

 

Regards

 

Yahya

**Comment by Abhisha1** [comment]
Thanks @Yahya0007. Just wanted to check where you seeing that error when you ran our sample app and called the same endpoint?

This is the link to the sample app: https://github.com/XeroAPI/xero-netstandard-oauth2-app

**Comment by CyanideMonkey** [comment]
Ola!
Is there any word on if Xero will be updated to work with any newer versions of RestSharp than 108.1?
I had RestSharp 110.2 in my project (which is the latest) so I was glad to find this workaround, but it would be good to not be concerned about if any references get updated at some point.
Thanks!
