### ISSUE TITLE
AccountingApi does not follow .NET naming conventions

### ISSUE THREAD

**Issue by lloydjatkinson** [XeroAPI/Xero-NetStandard#447]
**SDK you're using (please complete the following information):**
```
    <PackageReference Include="Xero.NetStandard.OAuth2" Version="3.29.1" />
    <PackageReference Include="Xero.NetStandard.OAuth2Client" Version="1.6.0" />
```
**Describe the bug**
The `Contacts` property has an underscore prefix which is not a conventional name for a property. Following idioms of a language should be an expected feature.

```cs
        [DataMember(Name = "Contacts", EmitDefaultValue = false)]
        public List<Contact> _Contacts { get; set; }
```

**Comment by JRising-Xero** [comment]
Hi @lloydjatkinson,
Completely agree with you, unfortunately, aligning our SDK with correct conventions would be a major breaking change. As such changes to correct this will have to be postponed until a complete overhaul of the SDK occurs.
Apologies for the inconvenience.
