### ISSUE TITLE
DateTimeUTC is missing in the response object class

### ISSUE THREAD

**Issue by thusithagh** [XeroAPI/Xero-NetStandard#448]
Xero.NetStandard.OAuth2            3.29.1
Xero.NetStandard.OAuth2Client   1.6.0

No property to hold the `DateTimeUTC `which seems to be the request processed by the API server, in any of the response object classes in _Xero.NetStandard.OAuth2_.

**To Reproduce**
1. Go to [API explorer](https://api-explorer.xero.com/accounting/accounts/getaccounts)
2. Make any API request against the Demo org (eg: Accounting/GetAccounts)
3. Notice the "DateTimeUTC" in the response
![image](https://user-images.githubusercontent.com/7278737/200556173-b03db6d4-dd06-4db8-8084-bab380f0f5cb.png)

4. Use Xero.NetStandard.OAuth2 to make the same request.
5. Notice that there isn't any property to hold the "DateTimeUTC" within the object class

![image](https://user-images.githubusercontent.com/7278737/200556924-7ceac55d-f0df-4219-982c-cf6e2aed8900.png)

**Expected behavior**
There should be a proper `DateTime `property to hold the `DateTimeUTC `returned.

This timestamp is needed, so we don't have a mismatch between the time actually the request got processed by the API server, and the time we started requesting. Please see if we can add that property to all the response object classes.

Best regards,
Thusitha H

**Comment by JRising-Xero** [comment]
Hi Thusitha,
You can use the `GetAccountsAsyncWithHttpInfo()` method to retrieve this additional response data. 
This method will return a `ApiResponse<T>` wrapping the standard model you get using `GetAccountsAsync()`. You will find the date time under `Content`, note, you will have to manually parse this information, i.e. something like:
```c#
var response = await _accountingApi.GetAccountsAsyncWithHttpInfo(xeroAccessToken, xeroTenantId);
var datetime = (DateTime)JObject.Parse(response.Content.ToString()).GetValue("DateTimeUTC");
```
Let me know if this solves your issue or if you have any other questions :)

**Comment by thusithagh** [comment]
Thanks for that @JRising-Xero 
I'll try out and let you know.

**Comment by thusithagh** [comment]
@JRising-Xero That works. Thanks!
However, it'd be a great help if the object classes itself had a property with this info populated.
