### ISSUE TITLE
BatchPayment info is missing inside the payment response object

### ISSUE THREAD

**Issue by thusithagh** [XeroAPI/Xero-NetStandard#449]
Xero.NetStandard.OAuth2 3.29.1
Xero.NetStandard.OAuth2Client 1.6.0

No property to hold batch payment information, within the `Xero.NetStandard.OAuth2.Model.Accounting.Payment` class.

**To Reproduce**
1. Go to [API explorer](https://api-explorer.xero.com/accounting/accounts/getaccounts)
2. Make a request to Accounting/GetPayments endpoint against the Demo org
3. Notice the `BatchPayment` property under each `Payment`
![image](https://user-images.githubusercontent.com/7278737/200558973-0988780c-8cfc-46de-b3dc-7cc83e617ff5.png)

4. Use Xero.NetStandard.OAuth2 to make the same request.
5. Notice that the `BatchPayment` is not captured in Xero.NetStandard.OAuth2.Model.Accounting.Payment` class, and there isn't even a property to hold this information.

![image](https://user-images.githubusercontent.com/7278737/200559973-dfe31716-86a4-4e63-a352-223d1b892b0d.png)

**Expected behavior**
There should be a property to hold batch payment information, under each payment. This is readily available in the API, so it should be about just having a new property and the values assigned to it on successful response.

It will be great help if we have all the information received via the API, in all the response objects in `Xero.NetStandard.OAuth2.Model.Accounting`

Best regards,
Thusitha H

**Comment by JRising-Xero** [comment]
Hi Thusitha,
Thanks for raising this issue, we agree that the batch payment property should be apart of the payment model.
We have gone ahead and released this change in the latest SDK release (3.29.2), view the [release notes here](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/3.29.2) for more details.

![image](https://user-images.githubusercontent.com/74580808/201793975-a56747e1-0bf0-47b9-884c-f4db6b1df126.png)


Thanks.
