### ISSUE TITLE
Log out process?

### ISSUE THREAD

**Issue by ezileave** [XeroAPI/Xero-NetStandard#468]
Hi,
We have to make connections to different accounts via our app but are unable to find a seamless way to log out the current account so another can log in.
So far the only way we have found is to direct the user to https://go.xero.com/logout which will log out the user, however they are left at the xero login page and not back in our app.

Is there any official way to do a log out and redirect back to our app?

Thanks

**Comment by RettBehrens** [comment]
Hi @ezileave could you provide more details describing your use case? 

Does your user have multiple Xero accounts each with access to one Xero org or one Xero account with access to multiple Xero orgs?

**Comment by ezileave** [comment]
Hi,
We have users that have multiple accounts, each with their own Xero org. so they may have 2 or more independant accounts they need to sign in to. 

so as an example, a user will connect and authorise to account1 and link to their org. but now we need to be able to connect to and authorise to account2 (a totally seperate account with different orgs) - when doing this we are still linked to account1 and don't get an option to log into account2. 
Going to the logout url looks to remove the cookies to account1 from the browser and allows us to login using account2... 

hopefully that makes sense?

**Comment by RettBehrens** [comment]
Ah thanks for the additional explanation. Unfortunately for the scenario you're describing there isn't a way to redirect on log out from Xero
