### ISSUE TITLE
Bankfeed scopes not allowed

### ISSUE THREAD

**Issue by pngan** [XeroAPI/Xero-NetStandard#475]
Hi Guys, 
I registered my app for testing using https://localhost/* for the company url and redirect_url.
It seems that the client created is not permitted to use the finance scopes. When the app runs, and after the button "Connect to Xero" is pressed, the user receives a 500 error, "Invalid scopes for client". Receiving a 500 error is off-putting for a new dev trying out the app.

I would suggest removing the bank feeds parts from the demo. I.e. removing
- `finance.*` scope from `appsettings.json`
- the finance controllers
- the finance views.

In a similar vein, the bank feeds parts of the app return 401 `AuthorizationUnsuccessful` probably for a similar reason.

**Comment by rlayhbrian** [comment]
Hello @pngan thank you for the suggestion.
I believe you are talking about the sample app for dotnet sdk.
I will make a quick update on this and remove the finance scopes in the appsettings.json file.
However, we won't remove the bankfeed and finance controllers and views as there are some finance app developers who would like to have access to those example codes once they are qualified as financial app partners.
