### ISSUE TITLE
Issue with item requested not found when calling endpoing

### ISSUE THREAD

**Issue by AGenius** [XeroAPI/Xero-NetStandard#490]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]
 - Version 3.33

**Describe the bug**
When updating my API Wrapper I was testing a call to get a random bank transfer. 
I was calling the wrong path (BankTransaction instead of BankTransfer) but passing a bank transfer guid. 
When this was called I was getting an ApiException from the ApiClient code
` throw new ApiException(500, e.Message);` of **_"Unexpected character encountered while parsing value: T. Path '', line 0, position 0."_**
I would expect a clean "item not found" response from your ApiClient call when it received "The resource you're looking for cannot be found" but it does not
It should detect a StatusCode = "NotFound" and continue .

**To Reproduce**
Call the BankTransaction endpoint with a Guid that does not exist. I have tested not found items with other endpoints and they are the same issue

**Expected behaviour**
Return the correct error response as "Not Found" 

**Screenshots**
![image](https://github.com/XeroAPI/Xero-NetStandard/assets/7373283/b0e9d6c1-eb6d-4755-9bb1-e3f1e66cff84)

**Additional context**
Not sure if this has always been this way

**Comment by thomas-anu** [comment]
Updated Xero-NetStandard SDK v3.34.5 with changes to throw specific exceptions with the status code and actual message instead of 500. Please verify.
