### ISSUE TITLE
GetReportProfitAndLossAsync Return Null JSON

### ISSUE THREAD

**Issue by TechJarr** [XeroAPI/Xero-NetStandard#502]
When using the GetReportProfitAndLossAsync function to receive the JSON response, we received a status code of 200. However, upon deserializing the JSON to text, we discovered that there was no data present in the JSON. Additionally, we checked the History log in the Xero developer platform and found no record of this call.

**Sample null json:**
[
  {
    "Filtered": true,
    "TrackingCategoryId": "xxx",
    "ReportData": null
  },
  {
    "Filtered": false,
    "TrackingCategoryId": null,
    "ReportData": null
  }
]

**Comment by thomas-anu** [comment]
Hi @TechJarr Can you please provide the details of the SDK version that you are using? We have tested the method with latest SDK and could not reproduce the issue. Can you give details on any additional parameters if you have used?

**Comment by thomas-anu** [comment]
Hi @TechJarr , can you please check the Xero dashboard with the same filters and the API explorer to check what data is being returned? We are still not able to reproduce the issue. Please find the screenshots attached. 

To check on Xero dashboard, navigate to Accounting --> Profit and Loss
To check using API explorer, https://api-explorer.xero.com/ 

<img width="1232" alt="Screenshot 2024-02-19 at 15 14 17" src="https://github.com/XeroAPI/Xero-NetStandard/assets/106374900/ee3395c6-1249-432a-8f54-b98856c6ea84">
<img width="1224" alt="Screenshot 2024-02-19 at 15 14 48" src="https://github.com/XeroAPI/Xero-NetStandard/assets/106374900/8d7d8096-f6ca-4515-8c3e-5d4216ea13a1">

**Comment by TechJarr** [comment]
Thanks @thomas-anu 

After testing the API explorer, it returned a normal JSON response. However, when switching to send a request using the SDK, it produced a null JSON response. The sample JSON data is different from the normal response, indicating that this is one of its behaviors. I checked with the Xero Developer Platform, and although the server did not record the JSON call, it did produce a response similar to the one shown in the image you provided.

![image](https://github.com/XeroAPI/Xero-NetStandard/assets/117668918/a9b41014-8740-4202-ac7a-7a1f9a8b6019)

Let me know if there's anything else I can help you with!

**Comment by ankushkhandare95** [comment]
Hi @TechJarr,

Apologies for the inconvenience caused.

We tried reproducing the same issue, called GetReportProfitAndLossAsync() with "Xero.NetStandard.OAuth2": "3.34.5" as specified by you, however we were getting valid report data with success response. Can you please verify the parameters/filters you are using on API explorer and developer dashboard match with your GetReportProfitAndLossAsync() method arguments. If you face the same issue post verifying it, give us some more idea about the filters you are using to call GetReportProfitAndLossAsync()
