### ISSUE TITLE
Getting this error-  FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0

### ISSUE THREAD

**Issue by walnut-co** [XeroAPI/Xero-NetStandard#506]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.3.10]
`<PackageReference Include="Xero.NetStandard.OAuth2" Version="4.0.1" />
<PackageReference Include="Xero.NetStandard.OAuth2Client" Version="1.6.0" />`

**Describe the bug**
Throws an error when running this integration with Azure Functions.

![image](https://github.com/XeroAPI/Xero-NetStandard/assets/13636878/d3fa6fa6-3688-4613-8ae4-185953ee4704)

**To Reproduce**

Please see image

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ankushkhandare95** [comment]
We were not able to reproduce the issue for the given SDK versions. We don't have any references for System.Text.Json  package in Xero.NetStandard.OAuth2 and Xero.NetStandard.OAuth2Client SDK. Could you please verify it on your side and let us know?
