### ISSUE TITLE
AccountingAPI, GetInvoices method, "where" parameter, SearchTerm is not working

### ISSUE THREAD

**Issue by onuryavuzmeral** [XeroAPI/Xero-NetStandard#512]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2 5.0

**Describe the bug**
AccountingAPI, getinvoices method has a "where" parameter where you can filter invoices.
if I use Type=="ACCREC" it has no problem, but if I use  SearchTerm=="abc" it throws an error as below:

Xero API 400 error calling GetInvoices :{
  "ErrorNumber": 16,
  "Type": "QueryParseException",
  "Message": "No property or field 'SearchTerm' exists in type 'Invoice'"
}

**Expected behavior**
Filter incoming invoices by searchterm case-insensitive.

**Comment by ankushkhandare95** [comment]
For GET /invoice endpoint SearchTerm is supported as a separate GetInvoices method parameter from Xero.NetStandard.OAuth version = 8.0. Please consider using version 8.0 or higher to use SearchTerm filter in AccountingAPI, GetInvoices method.

Please use SearchTerm with single "="  and outside of the where clause parameter. Do let us know if this works for you.
Thanks..
