### ISSUE TITLE
Issue with Xero Dependencies and RestSharp Version 111.2.0 Causing Integration Failures

### ISSUE THREAD

**Issue by developervisualapprovals** [XeroAPI/Xero-NetStandard#517]
Hi team,

In the NuGet package for Xero Dependencies, it is stated that the SDK supports RestSharp >= 110.2.0. However, when I updated RestSharp to the latest stable version 111.2.0, it caused all my Xero integrations to crash. Please advise on how to fix this issue. For your information, I am using Xero.NetStandard.OAuth2 version 5.0.0.

**To Reproduce**
![image (1)](https://github.com/XeroAPI/Xero-NetStandard/assets/145664759/4170657b-4b17-4f33-9181-bc6645b49334)
 See error in image

**Screenshots**
added screenshots to help explain your problem.

**Comment by yosefmah** [comment]
Hi @sangeet-joy-tw .  Could we have an update on this please?  I have raised a PR #514 for this and other deprecated packages.

**Comment by sangeet-joy-tw** [comment]
Hey @yosefmah,

We have replaced `RestSharp` with core `httpClient` library in our new Dotnet SDK version 9.0.0

Please install the latest version and hopefully `RestSharp` issue will not occur anymore.

Closing this card for now as this card was particularly for `RestSharp` issue.

Please feel free to raise separate issue cards for other vulnerabilities.
