### ISSUE TITLE
Get attachment doesn't return unique results

### ISSUE THREAD

**Issue by pajohns** [XeroAPI/Xero-NetStandard#52]
Currently the endpoint to get attachments is
`https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/Attachments`
which retrieves a list of attachments. If I want to retrieve an individual attachment I would use the endpoint
`https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/Attachments/{Filename}`
So I would use the first endpoint to retrieve a list of attachments against an attachment endpoint (in our instance invoice) and then use the second query to retrieve a particular file that's been uploaded against this object. The problem is that you can re-upload the same file as many times as you want, yet there is no endpoint that will retrieve that particular file as the filename is not a unique identifier to the attachment. The endpoint for an attachment should be
`https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/Attachments/{AttachmentGuid}`
or even better
`https://api.xero.com/api.xro/2.0/Attachments/{AttachmentGuid}`
as we have a guid as the unique identifier.

**Comment by MJMortimer** [comment]
Hey @pajohns
You should be able to use the stringified attachmentID in the current method available to download attachments instead of the filename. 

Can you please try that and let me know if you have any issues?

**Comment by pajohns** [comment]
Hi @MJMortimer , I'm able to retrieve a list of all the attachments associated with an invoice, which does address the issue and is how I've implemented a solution on our end - however if an endpoint is provided to retrieve 'an attachment' as specified in your documentation then I would assume that it would provide a unique reference to a single object. As it is I have a unique identifier but I can't use it to retrieve a unique result - only to query a list for a result within it. But yes, we're not completely stuck without a solution.

**Comment by pajohns** [comment]
Further to my last comment, it seems that retrieving a list isn't sorting the issue. Retrieving a list retrieves a list of references to each of the attachments associated with an invoice, but the byte arrays are all empty - as they should be given that it wouldn't make sense to have all attachments being downloaded as part of a response. However that takes us back to the original problem whereby the only way to download an attachment is to refer to the filename which is not unique. I have a workaround solution which is to first retrieve a list of attachments and then to refer to the ID of the attachment to retrieve the correct filename to do a second request, but this is less than ideal as it is not a unique reference to the attachment.

**Comment by pajohns** [comment]
Got you - sorry I misunderstood. That works fine. One thing however is that doing a get using the ID then returns a file with a FileName field that is the same as the attachment Guid ID rather than the file name so I still need to two gets - one for the list to get the file name and another to get the content. This works, but I'd assume that it wouldn't be too much to return the correct filename rather than the ID? I'd be happy to look into this if there are no resources to do this change.

Additionally I agree with you that it would be nice if the get by guid was documented.

**Comment by MJMortimer** [comment]
It sounds like we may need an overload for [this method](https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.Api/Core/Endpoints/AttachmentsEndpoint.cs#L36) so that we can load the attachment by guid but still create the in memory object with a specific filename. 

If you're happy to make those changes, I'll be more than happy to review and push them?

**Comment by pajohns** [comment]
I've created a pull request with changes. Have a look and let me know.

**Comment by pajohns** [comment]
Hi @MJMortimer, awaiting your review to my changes. It'd be great to be able to incorporate these changes so we can use it in our implementation.

**Comment by MJMortimer** [comment]
I assume the changes have been pulled in. I cannot see a still open PR for this, or a linked PR in here, so I'm going to close this. Please reopen if this is not the case
