### ISSUE TITLE
CreateInvoicesAsync results are not coming back in the order they were sent

### ISSUE THREAD

**Issue by oaktechnology** [XeroAPI/Xero-NetStandard#532]
**SDK you're using (please complete the following information):**
 - Version [1.6.0]

**Describe the bug**
Before this update when sending a BATCH of invoices using CreateInvoicesAsync the returning result (list of invoices) were in the order that they were sent (matching the source list order).   
It would now appear that the returning result is in date order which means I have no way of knowing which invoice matches what was sent.   Is it possible to revert this back to how it was in previous versions as I am now unable to match invoice posting with the source data.

**To Reproduce**
Batch send invoices in a random date order and the posted results  return in date order and not the original sent order.

**Expected behavior**
Batch posted invoices return results in the order that they were sent.

If there was a way of knowing the GUID of an invoice before it was posted I could use this but this appears to only get created when the posting is done which by then the result order is lost.

**Comment by oaktechnology** [comment]
Please close for now as I have something working I believe.  Will reopen if still a problem,

**Comment by Garand-Gary** [comment]
@oaktechnology Would you mind sharing how you resolved or moved past this issue?

**Comment by oaktechnology** [comment]
I ended up having to just process what came back but checking my references to work out which one was which. Not sure whether this has been updated since.   
If you are struggling with the same and can't work past please let me know.
Command used for posting was pretty standard and then had to loop the results.
retval.postedinvoices = await accapi.CreateInvoicesAsync(inXeroAccessToken, inCompanyTenantId, postinvoices, false);

**Comment by Garand-Gary** [comment]
We've hacked together a solution by putting a Guid in the Reference property, getting the response, mapping it to our objects, then taking a second pass to update the reference to either blank or a PO number as applicable. An absolute hack - there must be a better way.
