### ISSUE TITLE
Null reference on Organisation._Organisations from GetOrganisationsAsync

### ISSUE THREAD

**Issue by beeyee0401** [XeroAPI/Xero-NetStandard#535]
**SDK you're using (please complete the following information):**
 - Version [3.34.2]

**Describe the bug**
Some of our clients are getting a null reference exception when calling GetOrganisationsAsync then calling Organisations._Organisations but most are not.
We've confirmed that some of these clients have the Comprehensive plan (no other plans listed thus far)
This gets called on the initial connection to our application, and we're not able to recreate this issue using our Xero accounts.
These are the scopes they're requesting:
- openid profile email offline_access accounting.settings accounting.transactions accounting.contacts accounting.attachments
- accounting.attachments is relatively recent and clients who did not have this scope originally had to disconnect from our application and reconnect to get the new token with the updated scope. One of the customers running into this issue did this, but again, not most of our clients

Do Comprehensive plan Xero accounts not have access to that scope?
Wondering if anyone could provide any insight or has any ideas

**Expected behavior**
Clients can call GetOrganisationsAsync if they have a valid organization and connection

**Screenshots**
Here's our code snippet, we haven't switched everything to async yet but this works for all of our clients except these few.
![image](https://github.com/user-attachments/assets/44ecb10f-346c-40a5-8cfd-6a63ebcb1661)

**Additional context**
This is the best log we have, which doesn't tell us a lot for the reason of this error.

{
  "insertId": "b4ef170d-d835-4be9-9333-5fd79f7645d8:3439",
  "jsonPayload": {
    "Message": "Error establishing connection to accounting integration. Exception: {\"ClassName\":\"System.NullReferenceException\",\"Message\":\"Object reference not set to an instance of an object.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Handlers.Accounting.Xero.XeroAccountingApi.GetOrganization(String token, String tenantId) in C:\\\\adoBuild1\\\\_work\\\\13\\\\s\\\\Handlers.Accounting\\\\Xero\\\\XeroAccountingApi.cs:line 2812\\r\\n   at Handlers.Accounting.Xero.XeroAccountingApi.PrepareInitialConnection(OAuthData oauthData) in C:\\\\adoBuild1\\\\_work\\\\13\\\\s\\\\Handlers.Accounting\\\\Xero\\\\XeroAccountingApi.cs:line 2900\\r\\n   at BusinessLogic.Managers.AccountingManager.FinalizeConnectionToAccounting(IBuilders builder, IBTLogins l, IntegrationTypes integrationType, OAuthData oauthData, Boolean skipSalesTax) in C:\\\\adoBuild1\\\\_work\\\\13\\\\s\\\\BusinessLogic.Managers\\\\AccountingManager.cs:line 267\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nGetOrganization\\nHandlers.Accounting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\nHandlers.Accounting.Xero.XeroAccountingApi\\nXero.NetStandard.OAuth2.Model.Accounting.Organisation GetOrganization(System.String, System.String)\",\"HResult\":-2147467261,\"Source\":\"Handlers.Accounting\",\"WatsonBuckets\":null}, InitialConnectionData: null",
    "LoggingEventException": {
      "Message": "Object reference not set to an instance of an object.",
      "Source": "Handlers.Accounting",
      "StackTrace": "   at Handlers.Accounting.Xero.XeroAccountingApi.GetOrganization(String token, String tenantId) in C:\\adoBuild1\\_work\\13\\s\\Handlers.Accounting\\Xero\\XeroAccountingApi.cs:line 2812\r\n   at Handlers.Accounting.Xero.XeroAccountingApi.PrepareInitialConnection(OAuthData oauthData) in C:\\adoBuild1\\_work\\13\\s\\Handlers.Accounting\\Xero\\XeroAccountingApi.cs:line 2900\r\n   at BusinessLogic.Managers.AccountingManager.FinalizeConnectionToAccounting(IBuilders builder, IBTLogins l, IntegrationTypes integrationType, OAuthData oauthData, Boolean skipSalesTax) in C:\\adoBuild1\\_work\\13\\s\\BusinessLogic.Managers\\AccountingManager.cs:line 267"
    }
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "instance_id": "4261442364922910689",
      "zone": "us-central1-f"
    }
  },
  "timestamp": "2024-08-13T21:08:15.041921800Z",
  "severity": "ERROR",
  "receiveTimestamp": "2024-08-13T21:08:15.068878528Z",
  "errorGroups": [
    {
      "id": "CLWhq4aIie7uigE"
    }
  ]
}

**Comment by tomwaltersBCS** [comment]
I think we had the same issue. You'll need to update your SDK to at least [6.0.0](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v6.0.0) to be compatible with the new plans that were introduced in early July. 

SDK 6.0.0 updated the enums for the organisation class to include the new comprehensive plan.

From the release notes:

> Updates Accounting with new Organisation classes (IGNITE, GROW, COMPREHENSIVE)

**Comment by beeyee0401** [comment]
@tomwaltersBCS 
Thanks for the answer! We'll try that

**Comment by mar72vin** [comment]
> @beeyee0401
> 
> I think we had the same issue. You'll need to update your SDK to at least [6.0.0](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v6.0.0) to be compatible with the new plans that were introduced in early July.
> 
> SDK 6.0.0 updated the enums for the organisation class to include the new comprehensive plan.
> 
> From the release notes:
> 
> > Updates Accounting with new Organisation classes (IGNITE, GROW, COMPREHENSIVE)

This worked for me.  Thanks!

**Comment by beeyee0401** [comment]
@tomwaltersBCS 
Thanks so much! Confirmed this worked for our Comprehensive plan clients!
