### ISSUE TITLE
Invoice hexadecimal value 0x1F, is an invalid character.

### ISSUE THREAD

**Issue by GKirk84** [XeroAPI/Xero-NetStandard#61]
Hi, we have a work flow application for our production facilitiy which has tied into xero for approx 4 years now.
Now today for some reason we are unable to access the Invoices data to which has worked all this time.
using vb.net demo code below and error result.

Public Function GetInvoiceNumbersForClient(ByVal ContactID As Guid, ByVal BusinessID As Integer)

Dim session = New XeroApi.OAuth.XeroApiPrivateSession(PrintUserAgent, PrintconsumerKey, New X509Certificate2(PrintCertFileLocation, PrintCertFilePassword))

Dim res = New Repository(session)

Dim Invoices = res.Invoices.Where(Function(f) f.Contact.ContactID = ContactID).OrderByDescending(Function(x) x.Date)

Invoices results in the following:

InnerException = {"'" & ChrW(31) & "', hexadecimal value 0x1F, is an invalid character. Line 1, position 1."}

Any help much appreciated as we cannot mark work off as completed in our application without assigning it to the xero invoice data.

Thanks

**Comment by MJMortimer** [comment]
Hi @GKirk84, your issue seems to be related to our [very old deprecated SDK](https://github.com/XeroApi/XeroApi.net). 
We no longer maintain that SDK and suggest upgrading to this one.
