### ISSUE TITLE
Retrieving files from a specific folder

### ISSUE THREAD

**Issue by alvaromarithompson** [XeroAPI/Xero-NetStandard#64]
Neither the NetStandard nor the Net version of the library has support for retrieving files from a specific folder, as described in the documentation:

    GET https://api.xero.com/files.xro/1.0/Folders/414b3040-2829-4385-b458-3ead98fc69ca/Files

Any plans to implement this?

**Comment by MJMortimer** [comment]
Hey @alvaromarithompson, sorry that we've missed this functionality for so long. Is this something you'd be comfortable adding back to the SDK in a pull request?

**Comment by corientdev** [comment]
+1

**Comment by MJMortimer** [comment]
Hey @alvaromarithompson ,

As the OAuth1.0a Xero-NetStandard SDK is now in a strict maintenance phase, we won't be looking to make changes to add this feature.

Cheers,
Matt
