### ISSUE TITLE
Void/Delete Invoices endpoint is missing

### ISSUE THREAD

**Issue by jimjja** [XeroAPI/Xero-NetStandard#79]
Currently there is not endpoint for Deleting or Voiding an Invoice. This makes it impossible to delete/void an invoice through the Nuget package.

**Comment by MJMortimer** [comment]
Hey @jimjja, as mentioned in our documentation https://developer.xero.com/documentation/api/Invoices under the **Deleting and Voiding Invoices** heading, voiding and deleting invoices is achieved by updating the invoice to have the desired status. On that documentation page you'll also find a list of the valid status changes

**Comment by jimjja** [comment]
Hi @MJMortimer ,
If you see the examples of a Delete/Void invoice, you can see that we need to specify the invoice number in the request url. 
Unfortunately when you do a normal update/post request to change the status of the invoice to Draft/Delete, you will get an error message saying that the status of the invoice is invalid for this type of request.

**Comment by MJMortimer** [comment]
I've just tried this myself and can indeed perform valid status changes to void/delete invoices. What's the exact validation message you're seeing? If it's `Invoice not of valid status for modification` then you're trying to perform an invalid status change between two statuses that an invoice cannot move between.

**Comment by jimjja** [comment]
I am trying to update invoice status from AUTHORISED to VOID and I am getting the error message you mentioned. When I try to do it with the example given in the documentation, it works.
Can you provide me an example request you are doing via the nuget package to change an invoice status?

**Comment by MJMortimer** [comment]
This works for me:
```
var invoice = await api.Invoices.CreateAsync(new Invoice
{
    Contact = new Contact { Name = "Name" },
    Type = InvoiceType.AccountsPayable,
    Date = DateTime.UtcNow,
    DueDate = DateTime.UtcNow.AddDays(90),
    LineAmountTypes = LineAmountType.Inclusive,
    Status = InvoiceStatus.Authorised,
    LineItems = new List<LineItem>
    {
        new LineItem
        {
            AccountCode = "200",
            Description = "Description",
            LineAmount = 100m
        }
    }
});

invoice.Status = InvoiceStatus.Voided;

var updatedInvoice = await api.Invoices.UpdateAsync(invoice);
```

**Comment by jimjja** [comment]
This worked for me too. Thank you very much!

**Comment by jimjja** [comment]
Is it possible to update an invoice's status without having all it's details. For example in my case I need to get the invoice details by calling Invoice.FindAsync(), update the invoice object that the method returned and then update it. In the example shown in the documentation it is being done only by sending the invoice number and the status.
Is that possible with the current state of the implementation?
