### ISSUE TITLE
Missing PaymentServices endpoint

### ISSUE THREAD

**Issue by bjsaust** [XeroAPI/Xero-NetStandard#80]
There doesn't seem to be an endpoint for the PaymentServices in the nuget project. There are GET and PUT endpoints on the REST API for these. Is there any plan to add these to the project?

**Comment by SidneyAllen** [comment]
@bjsaust - sorry for the slow response - with OAuth 1.0a scheduled for deprecation in December 2020 our resources are focused on our new OAuth 2.0 based SDKs.  

These new SDKs are built off our OpenAPI specs which does include the PaymentServices endpoints.  I do want to mention that the PaymentService endpoints require a conversation around the commercial terms for using this endpoint to add a payment service.

https://developer.xero.com/documentation/api-guides/payment-services-integration-with-xero

The steps to become a certified Xero App partner are outlined in our partner page - ­ once you register for the partner program, we’ll connect you with the regional Financial Web team to discuss commercial terms.

https://developer.xero.com/partner
