### ISSUE TITLE
Change access modifiers on XeroHttpClient

### ISSUE THREAD

**Issue by mattdone01** [XeroAPI/Xero-NetStandard#81]
I am currently implementing a Bank Feeds Client and subclassing the XeroHttpClient. The calls to Bankfeeds are Json and the Response is different to that of the Accounting Api. I'd like to Subclass the XeroHttpClient class and add my own methods to facilitate the calls to Bank Feeds. I only require changes to the access modifiers of 2 functions and a field which I have a pull request ready to go. I don't seem to have push access to the repo to upload my branch and issue the PR. Can I get access? Thanks

**Comment by MJMortimer** [comment]
Hey @mattdone01,

The OAuth1.0a SDK is now in a strict maintenance phase, and so we unfortunately won't be looking to make any changes for this. 

Apologies for any inconvenience,
Matt
