### ISSUE TITLE
ArgumentOutOfRangeException: AppType did not match one of: private, public, partner

### ISSUE THREAD

**Issue by agrath** [XeroAPI/Xero-NetStandard#82]
Xero.Api 1.1.4.0
Core 2.2
Private application, certificate expires 2023

Our private synchronisation application has recently stopped working, when we try to call the constructor for XeroApiSettings, it throws with an error.
This is happening in both dev & production, so seems to be an issue in either the api or the library.

The error we're getting is ArgumentOutOfRangeException: AppType did not match one of: private, public, partner
Full stack trace in the image below

![image](https://user-images.githubusercontent.com/78284/64083251-b5b3c700-cd70-11e9-84da-aa9f72b3333b.png)

**Comment by agrath** [comment]
Fixed it...

The AppType was not specified in the appsettings.{Environment}.json file, perhaps it previously defaulted and something upstream has changed since the app has not been redeployed in quite some time.
Regardless, after setting the type, the error no longer occurs.
I will put a PR in to improve the error messaging here.

```
private void Load(IConfiguration config)
        {
            var apiSettings = config.GetSection("XeroApi");

            BaseUrl = apiSettings["BaseUrl"];
            CallbackUrl = apiSettings["CallbackUrl"];
            ConsumerKey = apiSettings["ConsumerKey"];
            ConsumerSecret = apiSettings["ConsumerSecret"];
            SigningCertificatePath = apiSettings["SigningCertPath"];
            SigningCertificatePassword = apiSettings["SigningCertPassword"];

            if (!Enum.TryParse(apiSettings["AppType"], true, out XeroApiAppType appType))
            {
                throw new ArgumentOutOfRangeException(nameof(apiSettings), apiSettings["AppType"], "AppType did not match one of: private, public, partner");
            }

            AppType = appType;        
        }
````

**Comment by agrath** [comment]
Pull request raised to handle null/empty AppType with an error to remind developer to check appsettings
https://github.com/XeroAPI/Xero-NetStandard/pull/83

**Comment by MJMortimer** [comment]
The pull request for this is in a closed state, with instructions to open if required. If reopening the pull request, please feel free to reopen this issue
