### ISSUE TITLE
Create Private app with external json file

### ISSUE THREAD

**Issue by michalfalat** [XeroAPI/Xero-NetStandard#87]
Current version of Xero API does not provide external settings when create Private app.
Forexample , I want to store all xero data outside of my appsettings.json. But when creating Private app there is no way to load external settings , but implicit from appsettings.json only:

https://github.com/XeroAPI/Xero-NetStandard/blob/568fda1121e0f85c9320fc9716010a6e38d1535d/Xero.Api/Infrastructure/Applications/Private/Core.cs

`var settings = new XeroApiSettings("my_xero_data.json");`
`this._xeroApi = new Xero.Api.Infrastructure.Applications.Private.Core  // error thrown  - no data in appsettings.json`

Suggestion: Add another constructor with possibility to pass  external XeroApiSettings as  an argument

**Comment by MJMortimer** [comment]
Hey @michalfalat,

As the OAuth1.0a Xero-NetStandard SDK is now in a strict maintenance phase, we won't be looking to make changes regarding this.

Apologies for any inconvenience,
Matt
