### ISSUE TITLE
Missing Bank Statement Report endpoint on OAuth2 branch

### ISSUE THREAD

**Issue by ThirstyJarek** [XeroAPI/Xero-NetStandard#89]
The endpoint for bank statement reports doesn't seem to exist anymore on the oauth2 branch? Is this endpoint being excluded from this branch on purpose, or has it simply been forgotten about?

Cheers

**Comment by SidneyAllen** [comment]
@ThirstyJarek We have plans to deprecate this report in the future and don't wish to promote it. For this reason, it's been omitted from our documentation and SDKs. If you do roll your own code to connect to this report be aware of it's current status and that any replacement report may not have all the same data.
