### ISSUE TITLE
Static HttpClient member is initialized in instance constructor

### ISSUE THREAD

**Issue by andrew-kuzovov** [XeroAPI/Xero-NetStandard#93]
https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.Api/Infrastructure/Http/XeroHttpClient.cs

**Comment by jenksguo** [comment]
This bug is related to OAuth 1.0 version of the SDK.

**Comment by MJMortimer** [comment]
Hey @andrew-kuzovov,

As the OAuth1.0a Xero-NetStandard SDK is now in a strict maintenance phase, we won;t be looking to make any changes regarding this.

Apologies for an inconvenience caused,
Matt
