### ISSUE TITLE
How to use this on C# webform app

### ISSUE THREAD

**Issue by corientdev** [XeroAPI/Xero-NetStandard#95]
How to use this on C# webform app

**Comment by jenksguo** [comment]
Hi @corientdev, unfortunately, as we move to ASP.NET Core, ASP.NET webform will no longer be supported. 

Please read the following link as it explains the alternative solution in Core, all of them should work with our current OAuth 2.0 SDK:
https://stackoverflow.com/questions/42599341/the-equivalent-to-web-forms-in-asp-net-core

**Comment by corientdev** [comment]
Sorry,

I was to ask about windows form. By mistake i wrote web form.

How to use it in windows form app
