### ISSUE TITLE
GetTaxRatesAsync

### ISSUE THREAD

**Issue by TimBish61** [XeroAPI/Xero-NetStandard#98]
I am successfully querying most endpoints but the TaxRates doesn't seem to return anything. I have tried with and without where:= and taxType:= parameters

Thanks
Tim

**Comment by elev8sam** [comment]
I'm also getting this issue when connecting to the Demo Company.

calling GetTaxRatesAsync returns NULL.

However, when calling GetTaxRatesAsyncWithHttpInfo, I get the following ErrorText :
"Error converting value \"GSTONCAPITALIMPORTS\" to type 'Xero.NetStandard.OAuth2.Model.TaxRate+ReportTaxTypeEnum'. Path 'TaxRates[7].ReportTaxType', line 157, position 44."

**Comment by carbyrock** [comment]
Getting the same result from the following:-

 var thisTenant = await _accountingApi.GetTaxRatesAsync(token.AccessToken, tenantId);

Returns Null

**Comment by jcook-abcom** [comment]
you can add a where clause to exclude the offending tax type. The api will then return the current active tax rates.
var taxRates = await _accountingApi.GetTaxRatesAsync(accessToken, tenantId, "Status=\"ACTIVE\"");

**Comment by SidneyAllen** [comment]
@TimBish61 @elev8sam 

Sorry for the slow response.  This was a missing ENUM for Tax Report Type in our OpenAPI specs we use to generate our SDKs.

This should be resolved.  Please check version 0.4.2 of Xero-NetStandard.
