### ISSUE TITLE
Support attachment IncludeOnline parameter in OAuth2 branch

### ISSUE THREAD

**Issue by PaulKlein** [XeroAPI/Xero-NetStandard#99]
**SDK you're using (please complete the following information):**
 - Xero.NetStandard.OAuth2 v0.0.2

**Is your feature request related to a problem? Please describe.**
In the old API, when uploading an attachment, there was an option to specify IncludeOnline when uploading an attachment.

**Describe the solution you'd like**
On the OAuth2 version, I can't see how to set this parameter. The closest function I can see is CreateInvoiceAttachmentByFileNameAsync() however this only allows to specify the file name + contents.

**Describe alternatives you've considered**
The old API also had a required mime-type field, which doesn't seem to be supported here. The attachment upload does work without specifying the mime-type but I'm not sure if this would also be needed in some cases.

**Additional context**
N/A

Thanks for any help or ideas here.

**Comment by SidneyAllen** [comment]
Hi @PaulKlein - thanks for the feedback.

This param was missing from our OpenAPI spec.  We've added IncludeOnline param.  This mean the next time we generate the .NET sdk, this should be resolved.

**Comment by PaulKlein** [comment]
Hi SidneyAllen, thanks a lot for checking on this for me, I appreciate the help.
